// Code generated by sqlgen dev. DO NOT EDIT.
package models

import (
	"context"
	"fmt"
	"io"
	"sync"
	"time"

	"github.com/teandresmith/sqlgen/cache"
	"github.com/teandresmith/sqlgen/database"
	"github.com/teandresmith/sqlgen/hook"
	"golang.org/x/sync/singleflight"
)

// Per-table schema fingerprint constants. Baked at codegen
// time from the table's column names, Go types, struct tags, PK order, and
// serializer identity. Any struct-shape change regenerates these; old-fingerprint
// keys naturally orphan.
const fingerprintArticle = "94de2016"
const fingerprintOrderItem = "5a3c1305"
const fingerprintProduct = "e5ebff56"
const fingerprintProfile = "97f7e749"
const fingerprintUser = "93173c80"
const fingerprintProductSummary = "688dc16f"

// cacheOptions captures runtime-injectable overrides for a Cache instance.
// All per-table TTL, serializer, key prefix, hydration, and circuit-breaker
// defaults are baked in at codegen time; options are runtime-only overrides
// (consumer-supplied objects, not config values).
type cacheOptions struct {
	invalidationSource cache.InvalidationSource
	metricsRecorder    cache.MetricsRecorder
	serializer         cache.Serializer
	breaker            *cache.Breaker
	onError            cache.OnErrorFunc
}

// CacheOption configures a Cache instance at construction time.
type CacheOption func(*cacheOptions)

// WithInvalidationSource wires a cross-instance invalidation source (e.g.,
// cache.FromEventSubscriber for sqlgen's event bus, or a custom Kafka/CDC
// adapter).
func WithInvalidationSource(src cache.InvalidationSource) CacheOption {
	return func(o *cacheOptions) { o.invalidationSource = src }
}

// WithMetricsRecorder wires a MetricsRecorder implementation. Nil is a
// zero-cost path.
func WithMetricsRecorder(r cache.MetricsRecorder) CacheOption {
	return func(o *cacheOptions) { o.metricsRecorder = r }
}

// WithSerializer overrides the default serializer baked in at codegen time.
// Required when cache.serializer is "custom" in sqlgen.yml.
func WithSerializer(s cache.Serializer) CacheOption {
	return func(o *cacheOptions) { o.serializer = s }
}

// WithCircuitBreaker overrides the default circuit breaker.
func WithCircuitBreaker(b *cache.Breaker) CacheOption {
	return func(o *cacheOptions) { o.breaker = b }
}

// WithOnError overrides the textual cache-error callback.
func WithOnError(fn cache.OnErrorFunc) CacheOption {
	return func(o *cacheOptions) { o.onError = fn }
}

// Cache is the generated cache facade. Instances are safe for concurrent use
// after construction. Cache is wired into the generated client via WithCache.
type Cache struct {
	backend          cache.Backend
	prefix           string
	serializer       cache.Serializer
	metrics          cache.MetricsRecorder
	breaker          *cache.Breaker
	onError          cache.OnErrorFunc
	hydrationEnabled bool
	hydrationTimeout time.Duration
	sf               singleflight.Group
	hydrating        sync.Map
	invalidationSub  cache.InvalidationSubscription
}

// NewCache constructs a Cache backed by backend with runtime overrides in opts.
// Returns an error when a required option is missing (e.g. cache.serializer:
// custom without WithSerializer).
func NewCache(backend cache.Backend, opts ...CacheOption) (*Cache, error) {
	options := cacheOptions{}
	for _, opt := range opts {
		opt(&options)
	}

	if options.serializer == nil {
		options.serializer = cache.JSONSerializer{}
	}
	if options.breaker == nil {
		breakerCfg := cache.BreakerConfig{
			FailureThreshold:  3,
			ProbeInterval:     time.Duration(50000000),
			HalfOpenMaxProbes: 1,
		}
		if options.metricsRecorder != nil {
			m := options.metricsRecorder
			breakerCfg.OnStateChange = func(from, to cache.CircuitState) {
				m.CircuitBreakerStateChange(from, to)
			}
		}
		options.breaker = cache.NewBreaker(breakerCfg)
	}

	if options.onError == nil {
		options.onError = cache.DefaultOnCacheError
	}

	c := &Cache{
		backend:          backend,
		prefix:           "sqlgen",
		serializer:       options.serializer,
		metrics:          options.metricsRecorder,
		breaker:          options.breaker,
		onError:          options.onError,
		hydrationEnabled: true,
		hydrationTimeout: time.Duration(5000000000),
	}

	if options.invalidationSource != nil {
		sub, err := options.invalidationSource.Subscribe(c.handleInvalidation)
		if err != nil {
			return nil, fmt.Errorf("cache: subscribe invalidation source: %w", err)
		}
		c.invalidationSub = sub
	}

	return c, nil
}

// handleInvalidation is the InvalidationSource handler: it dispatches signals
// to InvalidateTable (when the signal carries no PKs), the precise
// tenant-scoped per-PK path for tenanted tables, or
// InvalidateMany.
func (c *Cache) handleInvalidation(ctx context.Context, signal cache.InvalidationSignal) error {
	if len(signal.PKs) == 0 {
		return c.InvalidateTable(ctx, signal.Table)
	}
	return c.InvalidateMany(ctx, signal.Table, signal.PKs)
}

// keyForArticle builds the cache key for Article by PK.
func (c *Cache) keyForArticle(pk int64) string {
	return cache.BuildKey(c.prefix, "", "articles", fingerprintArticle, pk)
}

// ttlForArticle returns the resolved TTL for Article cache entries.
func (c *Cache) ttlForArticle() time.Duration {
	return time.Duration(3600000000000)
}

// hasAnyRelationshipArticle reports whether fo has any relationship-typed
// flag set. Returns false when fo is nil or when only column flags are set.
func hasAnyRelationshipArticle(fo any) bool {
	if fo == nil {
		return false
	}
	typed, ok := fo.(*ArticleFieldOptions)
	if !ok || typed == nil {
		return false
	}
	_ = typed
	return false
}

// fullParentFieldOptionsArticle returns a FieldOptions with every column
// flag set to true and every relationship flag nil — used by hydration to
// guarantee parent-only results regardless of nil-FieldOptions semantics
// elsewhere.
func fullParentFieldOptionsArticle() *ArticleFieldOptions {
	return &ArticleFieldOptions{
		ID:        true,
		Title:     true,
		Body:      true,
		Author:    true,
		CreatedAt: true,
		DeletedAt: true,
	}
}

// readThroughArticle implements the cache read-through path for Article:
// probe cache → hit returns decoded entity, miss runs the DB query under
// singleflight dedup and populates cache. Every backend call is breaker-gated;
// errors are routed through cache.RouteError and fall through to the DB so
// a cache outage never breaks the caller.
func (c *Cache) readThroughArticle(ctx context.Context, pk int64, q *hook.QueryContext, next hook.QueryHandler) (any, error) {
	key := c.keyForArticle(pk)
	schema := ""

	if c.breaker == nil || c.breaker.Allow() {
		getStart := time.Now()
		entity, hit, err := cache.GetAs[*Article](ctx, c.backend, c.serializer, key)
		if c.metrics != nil {
			c.metrics.GetLatency(schema, TableArticles, time.Since(getStart))
		}
		if err != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "get", schema, TableArticles, err)
		} else if hit {
			if c.metrics != nil {
				c.metrics.Hit(schema, TableArticles)
			}
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
			return entity, nil
		} else {
			if c.metrics != nil {
				c.metrics.Miss(schema, TableArticles)
			}
			// A clean miss is a successful backend round-trip — it resets
			// the consecutive-failure counter and closes a HalfOpen probe.
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
		}
	} else if c.metrics != nil {
		c.metrics.Miss(schema, TableArticles)
	}

	// Partial fetches must not write back to cache (invariant:
	// only full entities). On miss, run the DB through `next` with the
	// caller's partial FieldOptions, kick off fire-and-forget hydration to
	// refill the cache with the full entity, and return the
	// partial result directly. The partial + hydration-disabled case is
	// filtered out earlier in QueryHook.
	if extractFieldOptions(q.CallOptions) != nil {
		result, err := next(ctx, q)
		if err != nil {
			return nil, err
		}
		c.hydrateArticle(pk, next)
		return result, nil
	}

	ch := c.sf.DoChan(key, func() (any, error) {
		// In-flight cache re-check: a sibling flight may have populated the
		// cache between this caller's outer Get-miss and entering the flight.
		// Without this, late stragglers that arrive after the sibling flight
		// completed would register a new flight and run a duplicate DB query.
		// The outer probe already recorded the Miss / breaker success; this
		// inner re-check is dedup machinery, not an observable cache event, so
		// it emits no metrics.
		if c.breaker == nil || c.breaker.Allow() {
			if entity, hit, err := cache.GetAs[*Article](ctx, c.backend, c.serializer, key); err == nil && hit {
				return entity, nil
			}
		}
		result, fetchErr := next(ctx, q)
		if fetchErr != nil {
			return nil, fetchErr
		}
		entity, ok := result.(*Article)
		if !ok || entity == nil {
			return result, nil
		}
		if c.breaker != nil && !c.breaker.Allow() {
			return result, nil
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForArticle())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableArticles, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableArticles, setErr)
			return result, nil
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableArticles)
		}
		return result, nil
	})

	select {
	case res := <-ch:
		return res.Val, res.Err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// setArticle caches a full Article entity. Called by the mutation hook
// after a successful Create / CreateMany to populate the cache with the new
// entity. The PK is read from the entity itself so this never
// depends on parallel ordering with m.AffectedPKs (GetMany does not guarantee
// result order). Failures route through cache.RouteError and never surface to
// the caller path; a cache outage can delay the next Get but never breaks a
// mutation.
func (c *Cache) setArticle(ctx context.Context, entity *Article) {
	if entity == nil {
		return
	}
	if c.breaker != nil && !c.breaker.Allow() {
		return
	}
	key := c.keyForArticle(entity.ID)
	schema := ""
	setStart := time.Now()
	err := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForArticle())
	if c.metrics != nil {
		c.metrics.SetLatency(schema, TableArticles, time.Since(setStart))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableArticles, err)
		return
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Set(schema, TableArticles)
	}
}

// hydrateArticle launches at most one background hydration per (table, pk).
// Runs with a fresh context.Background() timeout — does NOT inherit the
// caller's ctx. Re-runs the Get through the
// downstream chain with full-parent FieldOptions (every column true, every
// relationship nil) and SkipHooks: true so the refill pulls a full entity,
// then serializes and populates the cache under the full-entity key. Errors
// surface via metrics.HydrationComplete + cache.RouteError; the caller path
// is never affected.
func (c *Cache) hydrateArticle(pk int64, next hook.QueryHandler) {
	if !c.hydrationEnabled {
		return
	}
	key := c.keyForArticle(pk)
	if _, loaded := c.hydrating.LoadOrStore(key, struct{}{}); loaded {
		return
	}
	go func() {
		defer c.hydrating.Delete(key)
		ctx, cancel := context.WithTimeout(context.Background(), c.hydrationTimeout)
		defer cancel()
		schema := ""
		if c.metrics != nil {
			c.metrics.HydrationStart(schema, TableArticles)
		}

		q := &hook.QueryContext{
			Op:     hook.OpGet,
			Table:  TableArticles,
			Schema: schema,
			PK:     pk,
			CallOptions: CallOptions[ArticleFieldOptions]{
				FieldOptions: fullParentFieldOptionsArticle(),
				SkipHooks:    true,
			},
		}
		result, err := next(ctx, q)
		if err != nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableArticles, err)
			}
			return
		}
		entity, ok := result.(*Article)
		if !ok || entity == nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableArticles, nil)
			}
			return
		}

		if c.breaker != nil && !c.breaker.Allow() {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableArticles, nil)
			}
			return
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForArticle())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableArticles, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableArticles, setErr)
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableArticles, setErr)
			}
			return
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableArticles)
			c.metrics.HydrationComplete(schema, TableArticles, nil)
		}
	}()
}

// keyForOrderItem builds the cache key for OrderItem with composite PK.
// The []any is constructed in DDL PRIMARY KEY column order inside this one
// function — call sites never reorder (key-order invariant).
func (c *Cache) keyForOrderItem(pk OrderItemPK) string {
	return cache.BuildCompositeKey(c.prefix, "", "order_items", fingerprintOrderItem, []any{
		pk.OrderID,
		pk.ProductID,
	})
}

// ttlForOrderItem returns the resolved TTL for OrderItem cache entries.
func (c *Cache) ttlForOrderItem() time.Duration {
	return time.Duration(3600000000000)
}

// hasAnyRelationshipOrderItem reports whether fo has any relationship-typed
// flag set. Returns false when fo is nil or when only column flags are set.
func hasAnyRelationshipOrderItem(fo any) bool {
	if fo == nil {
		return false
	}
	typed, ok := fo.(*OrderItemFieldOptions)
	if !ok || typed == nil {
		return false
	}
	_ = typed
	return false
}

// fullParentFieldOptionsOrderItem returns a FieldOptions with every column
// flag set to true and every relationship flag nil — used by hydration to
// guarantee parent-only results regardless of nil-FieldOptions semantics
// elsewhere.
func fullParentFieldOptionsOrderItem() *OrderItemFieldOptions {
	return &OrderItemFieldOptions{
		OrderID:   true,
		ProductID: true,
		Quantity:  true,
		UnitPrice: true,
	}
}

// readThroughOrderItem implements the cache read-through path for OrderItem:
// probe cache → hit returns decoded entity, miss runs the DB query under
// singleflight dedup and populates cache. Every backend call is breaker-gated;
// errors are routed through cache.RouteError and fall through to the DB so
// a cache outage never breaks the caller.
func (c *Cache) readThroughOrderItem(ctx context.Context, pk OrderItemPK, q *hook.QueryContext, next hook.QueryHandler) (any, error) {
	key := c.keyForOrderItem(pk)
	schema := ""

	if c.breaker == nil || c.breaker.Allow() {
		getStart := time.Now()
		entity, hit, err := cache.GetAs[*OrderItem](ctx, c.backend, c.serializer, key)
		if c.metrics != nil {
			c.metrics.GetLatency(schema, TableOrderItems, time.Since(getStart))
		}
		if err != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "get", schema, TableOrderItems, err)
		} else if hit {
			if c.metrics != nil {
				c.metrics.Hit(schema, TableOrderItems)
			}
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
			return entity, nil
		} else {
			if c.metrics != nil {
				c.metrics.Miss(schema, TableOrderItems)
			}
			// A clean miss is a successful backend round-trip — it resets
			// the consecutive-failure counter and closes a HalfOpen probe.
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
		}
	} else if c.metrics != nil {
		c.metrics.Miss(schema, TableOrderItems)
	}

	// Partial fetches must not write back to cache (invariant:
	// only full entities). On miss, run the DB through `next` with the
	// caller's partial FieldOptions, kick off fire-and-forget hydration to
	// refill the cache with the full entity, and return the
	// partial result directly. The partial + hydration-disabled case is
	// filtered out earlier in QueryHook.
	if extractFieldOptions(q.CallOptions) != nil {
		result, err := next(ctx, q)
		if err != nil {
			return nil, err
		}
		c.hydrateOrderItem(pk, next)
		return result, nil
	}

	ch := c.sf.DoChan(key, func() (any, error) {
		// In-flight cache re-check: a sibling flight may have populated the
		// cache between this caller's outer Get-miss and entering the flight.
		// Without this, late stragglers that arrive after the sibling flight
		// completed would register a new flight and run a duplicate DB query.
		// The outer probe already recorded the Miss / breaker success; this
		// inner re-check is dedup machinery, not an observable cache event, so
		// it emits no metrics.
		if c.breaker == nil || c.breaker.Allow() {
			if entity, hit, err := cache.GetAs[*OrderItem](ctx, c.backend, c.serializer, key); err == nil && hit {
				return entity, nil
			}
		}
		result, fetchErr := next(ctx, q)
		if fetchErr != nil {
			return nil, fetchErr
		}
		entity, ok := result.(*OrderItem)
		if !ok || entity == nil {
			return result, nil
		}
		if c.breaker != nil && !c.breaker.Allow() {
			return result, nil
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForOrderItem())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableOrderItems, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableOrderItems, setErr)
			return result, nil
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableOrderItems)
		}
		return result, nil
	})

	select {
	case res := <-ch:
		return res.Val, res.Err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// setOrderItem caches a full OrderItem entity. Called by the mutation hook
// after a successful Create / CreateMany to populate the cache with the new
// entity. The PK is read from the entity itself so this never
// depends on parallel ordering with m.AffectedPKs (GetMany does not guarantee
// result order). Failures route through cache.RouteError and never surface to
// the caller path; a cache outage can delay the next Get but never breaks a
// mutation.
func (c *Cache) setOrderItem(ctx context.Context, entity *OrderItem) {
	if entity == nil {
		return
	}
	if c.breaker != nil && !c.breaker.Allow() {
		return
	}
	key := c.keyForOrderItem(OrderItemPK{
		OrderID:   entity.OrderID,
		ProductID: entity.ProductID,
	})
	schema := ""
	setStart := time.Now()
	err := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForOrderItem())
	if c.metrics != nil {
		c.metrics.SetLatency(schema, TableOrderItems, time.Since(setStart))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableOrderItems, err)
		return
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Set(schema, TableOrderItems)
	}
}

// hydrateOrderItem launches at most one background hydration per (table, pk).
// Runs with a fresh context.Background() timeout — does NOT inherit the
// caller's ctx. Re-runs the Get through the
// downstream chain with full-parent FieldOptions (every column true, every
// relationship nil) and SkipHooks: true so the refill pulls a full entity,
// then serializes and populates the cache under the full-entity key. Errors
// surface via metrics.HydrationComplete + cache.RouteError; the caller path
// is never affected.
func (c *Cache) hydrateOrderItem(pk OrderItemPK, next hook.QueryHandler) {
	if !c.hydrationEnabled {
		return
	}
	key := c.keyForOrderItem(pk)
	if _, loaded := c.hydrating.LoadOrStore(key, struct{}{}); loaded {
		return
	}
	go func() {
		defer c.hydrating.Delete(key)
		ctx, cancel := context.WithTimeout(context.Background(), c.hydrationTimeout)
		defer cancel()
		schema := ""
		if c.metrics != nil {
			c.metrics.HydrationStart(schema, TableOrderItems)
		}

		q := &hook.QueryContext{
			Op:     hook.OpGet,
			Table:  TableOrderItems,
			Schema: schema,
			PK:     pk,
			CallOptions: CallOptions[OrderItemFieldOptions]{
				FieldOptions: fullParentFieldOptionsOrderItem(),
				SkipHooks:    true,
			},
		}
		result, err := next(ctx, q)
		if err != nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableOrderItems, err)
			}
			return
		}
		entity, ok := result.(*OrderItem)
		if !ok || entity == nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableOrderItems, nil)
			}
			return
		}

		if c.breaker != nil && !c.breaker.Allow() {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableOrderItems, nil)
			}
			return
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForOrderItem())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableOrderItems, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableOrderItems, setErr)
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableOrderItems, setErr)
			}
			return
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableOrderItems)
			c.metrics.HydrationComplete(schema, TableOrderItems, nil)
		}
	}()
}

// keyForProduct builds the cache key for Product by PK.
func (c *Cache) keyForProduct(pk int64) string {
	return cache.BuildKey(c.prefix, "", "products", fingerprintProduct, pk)
}

// ttlForProduct returns the resolved TTL for Product cache entries.
func (c *Cache) ttlForProduct() time.Duration {
	return time.Duration(3600000000000)
}

// hasAnyRelationshipProduct reports whether fo has any relationship-typed
// flag set. Returns false when fo is nil or when only column flags are set.
func hasAnyRelationshipProduct(fo any) bool {
	if fo == nil {
		return false
	}
	typed, ok := fo.(*ProductFieldOptions)
	if !ok || typed == nil {
		return false
	}
	_ = typed
	return false
}

// fullParentFieldOptionsProduct returns a FieldOptions with every column
// flag set to true and every relationship flag nil — used by hydration to
// guarantee parent-only results regardless of nil-FieldOptions semantics
// elsewhere.
func fullParentFieldOptionsProduct() *ProductFieldOptions {
	return &ProductFieldOptions{
		ID:        true,
		Name:      true,
		SKU:       true,
		Price:     true,
		Stock:     true,
		CreatedAt: true,
	}
}

// readThroughProduct implements the cache read-through path for Product:
// probe cache → hit returns decoded entity, miss runs the DB query under
// singleflight dedup and populates cache. Every backend call is breaker-gated;
// errors are routed through cache.RouteError and fall through to the DB so
// a cache outage never breaks the caller.
func (c *Cache) readThroughProduct(ctx context.Context, pk int64, q *hook.QueryContext, next hook.QueryHandler) (any, error) {
	key := c.keyForProduct(pk)
	schema := ""

	if c.breaker == nil || c.breaker.Allow() {
		getStart := time.Now()
		entity, hit, err := cache.GetAs[*Product](ctx, c.backend, c.serializer, key)
		if c.metrics != nil {
			c.metrics.GetLatency(schema, TableProducts, time.Since(getStart))
		}
		if err != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "get", schema, TableProducts, err)
		} else if hit {
			if c.metrics != nil {
				c.metrics.Hit(schema, TableProducts)
			}
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
			return entity, nil
		} else {
			if c.metrics != nil {
				c.metrics.Miss(schema, TableProducts)
			}
			// A clean miss is a successful backend round-trip — it resets
			// the consecutive-failure counter and closes a HalfOpen probe.
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
		}
	} else if c.metrics != nil {
		c.metrics.Miss(schema, TableProducts)
	}

	// Partial fetches must not write back to cache (invariant:
	// only full entities). On miss, run the DB through `next` with the
	// caller's partial FieldOptions, kick off fire-and-forget hydration to
	// refill the cache with the full entity, and return the
	// partial result directly. The partial + hydration-disabled case is
	// filtered out earlier in QueryHook.
	if extractFieldOptions(q.CallOptions) != nil {
		result, err := next(ctx, q)
		if err != nil {
			return nil, err
		}
		c.hydrateProduct(pk, next)
		return result, nil
	}

	ch := c.sf.DoChan(key, func() (any, error) {
		// In-flight cache re-check: a sibling flight may have populated the
		// cache between this caller's outer Get-miss and entering the flight.
		// Without this, late stragglers that arrive after the sibling flight
		// completed would register a new flight and run a duplicate DB query.
		// The outer probe already recorded the Miss / breaker success; this
		// inner re-check is dedup machinery, not an observable cache event, so
		// it emits no metrics.
		if c.breaker == nil || c.breaker.Allow() {
			if entity, hit, err := cache.GetAs[*Product](ctx, c.backend, c.serializer, key); err == nil && hit {
				return entity, nil
			}
		}
		result, fetchErr := next(ctx, q)
		if fetchErr != nil {
			return nil, fetchErr
		}
		entity, ok := result.(*Product)
		if !ok || entity == nil {
			return result, nil
		}
		if c.breaker != nil && !c.breaker.Allow() {
			return result, nil
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForProduct())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableProducts, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableProducts, setErr)
			return result, nil
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableProducts)
		}
		return result, nil
	})

	select {
	case res := <-ch:
		return res.Val, res.Err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// setProduct caches a full Product entity. Called by the mutation hook
// after a successful Create / CreateMany to populate the cache with the new
// entity. The PK is read from the entity itself so this never
// depends on parallel ordering with m.AffectedPKs (GetMany does not guarantee
// result order). Failures route through cache.RouteError and never surface to
// the caller path; a cache outage can delay the next Get but never breaks a
// mutation.
func (c *Cache) setProduct(ctx context.Context, entity *Product) {
	if entity == nil {
		return
	}
	if c.breaker != nil && !c.breaker.Allow() {
		return
	}
	key := c.keyForProduct(entity.ID)
	schema := ""
	setStart := time.Now()
	err := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForProduct())
	if c.metrics != nil {
		c.metrics.SetLatency(schema, TableProducts, time.Since(setStart))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableProducts, err)
		return
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Set(schema, TableProducts)
	}
}

// hydrateProduct launches at most one background hydration per (table, pk).
// Runs with a fresh context.Background() timeout — does NOT inherit the
// caller's ctx. Re-runs the Get through the
// downstream chain with full-parent FieldOptions (every column true, every
// relationship nil) and SkipHooks: true so the refill pulls a full entity,
// then serializes and populates the cache under the full-entity key. Errors
// surface via metrics.HydrationComplete + cache.RouteError; the caller path
// is never affected.
func (c *Cache) hydrateProduct(pk int64, next hook.QueryHandler) {
	if !c.hydrationEnabled {
		return
	}
	key := c.keyForProduct(pk)
	if _, loaded := c.hydrating.LoadOrStore(key, struct{}{}); loaded {
		return
	}
	go func() {
		defer c.hydrating.Delete(key)
		ctx, cancel := context.WithTimeout(context.Background(), c.hydrationTimeout)
		defer cancel()
		schema := ""
		if c.metrics != nil {
			c.metrics.HydrationStart(schema, TableProducts)
		}

		q := &hook.QueryContext{
			Op:     hook.OpGet,
			Table:  TableProducts,
			Schema: schema,
			PK:     pk,
			CallOptions: CallOptions[ProductFieldOptions]{
				FieldOptions: fullParentFieldOptionsProduct(),
				SkipHooks:    true,
			},
		}
		result, err := next(ctx, q)
		if err != nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProducts, err)
			}
			return
		}
		entity, ok := result.(*Product)
		if !ok || entity == nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProducts, nil)
			}
			return
		}

		if c.breaker != nil && !c.breaker.Allow() {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProducts, nil)
			}
			return
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForProduct())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableProducts, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableProducts, setErr)
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProducts, setErr)
			}
			return
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableProducts)
			c.metrics.HydrationComplete(schema, TableProducts, nil)
		}
	}()
}

// keyForProfile builds the cache key for Profile by PK.
func (c *Cache) keyForProfile(pk int64) string {
	return cache.BuildKey(c.prefix, "", "profiles", fingerprintProfile, pk)
}

// ttlForProfile returns the resolved TTL for Profile cache entries.
func (c *Cache) ttlForProfile() time.Duration {
	return time.Duration(3600000000000)
}

// hasAnyRelationshipProfile reports whether fo has any relationship-typed
// flag set. Returns false when fo is nil or when only column flags are set.
func hasAnyRelationshipProfile(fo any) bool {
	if fo == nil {
		return false
	}
	typed, ok := fo.(*ProfileFieldOptions)
	if !ok || typed == nil {
		return false
	}
	if typed.Users != nil {
		return true
	}
	return false
}

// fullParentFieldOptionsProfile returns a FieldOptions with every column
// flag set to true and every relationship flag nil — used by hydration to
// guarantee parent-only results regardless of nil-FieldOptions semantics
// elsewhere.
func fullParentFieldOptionsProfile() *ProfileFieldOptions {
	return &ProfileFieldOptions{
		ID:     true,
		UserID: true,
		Bio:    true,
	}
}

// readThroughProfile implements the cache read-through path for Profile:
// probe cache → hit returns decoded entity, miss runs the DB query under
// singleflight dedup and populates cache. Every backend call is breaker-gated;
// errors are routed through cache.RouteError and fall through to the DB so
// a cache outage never breaks the caller.
func (c *Cache) readThroughProfile(ctx context.Context, pk int64, q *hook.QueryContext, next hook.QueryHandler) (any, error) {
	key := c.keyForProfile(pk)
	schema := ""

	if c.breaker == nil || c.breaker.Allow() {
		getStart := time.Now()
		entity, hit, err := cache.GetAs[*Profile](ctx, c.backend, c.serializer, key)
		if c.metrics != nil {
			c.metrics.GetLatency(schema, TableProfiles, time.Since(getStart))
		}
		if err != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "get", schema, TableProfiles, err)
		} else if hit {
			if c.metrics != nil {
				c.metrics.Hit(schema, TableProfiles)
			}
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
			return entity, nil
		} else {
			if c.metrics != nil {
				c.metrics.Miss(schema, TableProfiles)
			}
			// A clean miss is a successful backend round-trip — it resets
			// the consecutive-failure counter and closes a HalfOpen probe.
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
		}
	} else if c.metrics != nil {
		c.metrics.Miss(schema, TableProfiles)
	}

	// Partial fetches must not write back to cache (invariant:
	// only full entities). On miss, run the DB through `next` with the
	// caller's partial FieldOptions, kick off fire-and-forget hydration to
	// refill the cache with the full entity, and return the
	// partial result directly. The partial + hydration-disabled case is
	// filtered out earlier in QueryHook.
	if extractFieldOptions(q.CallOptions) != nil {
		result, err := next(ctx, q)
		if err != nil {
			return nil, err
		}
		c.hydrateProfile(pk, next)
		return result, nil
	}

	ch := c.sf.DoChan(key, func() (any, error) {
		// In-flight cache re-check: a sibling flight may have populated the
		// cache between this caller's outer Get-miss and entering the flight.
		// Without this, late stragglers that arrive after the sibling flight
		// completed would register a new flight and run a duplicate DB query.
		// The outer probe already recorded the Miss / breaker success; this
		// inner re-check is dedup machinery, not an observable cache event, so
		// it emits no metrics.
		if c.breaker == nil || c.breaker.Allow() {
			if entity, hit, err := cache.GetAs[*Profile](ctx, c.backend, c.serializer, key); err == nil && hit {
				return entity, nil
			}
		}
		result, fetchErr := next(ctx, q)
		if fetchErr != nil {
			return nil, fetchErr
		}
		entity, ok := result.(*Profile)
		if !ok || entity == nil {
			return result, nil
		}
		if c.breaker != nil && !c.breaker.Allow() {
			return result, nil
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForProfile())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableProfiles, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableProfiles, setErr)
			return result, nil
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableProfiles)
		}
		return result, nil
	})

	select {
	case res := <-ch:
		return res.Val, res.Err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// setProfile caches a full Profile entity. Called by the mutation hook
// after a successful Create / CreateMany to populate the cache with the new
// entity. The PK is read from the entity itself so this never
// depends on parallel ordering with m.AffectedPKs (GetMany does not guarantee
// result order). Failures route through cache.RouteError and never surface to
// the caller path; a cache outage can delay the next Get but never breaks a
// mutation.
func (c *Cache) setProfile(ctx context.Context, entity *Profile) {
	if entity == nil {
		return
	}
	if c.breaker != nil && !c.breaker.Allow() {
		return
	}
	key := c.keyForProfile(entity.ID)
	schema := ""
	setStart := time.Now()
	err := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForProfile())
	if c.metrics != nil {
		c.metrics.SetLatency(schema, TableProfiles, time.Since(setStart))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableProfiles, err)
		return
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Set(schema, TableProfiles)
	}
}

// hydrateProfile launches at most one background hydration per (table, pk).
// Runs with a fresh context.Background() timeout — does NOT inherit the
// caller's ctx. Re-runs the Get through the
// downstream chain with full-parent FieldOptions (every column true, every
// relationship nil) and SkipHooks: true so the refill pulls a full entity,
// then serializes and populates the cache under the full-entity key. Errors
// surface via metrics.HydrationComplete + cache.RouteError; the caller path
// is never affected.
func (c *Cache) hydrateProfile(pk int64, next hook.QueryHandler) {
	if !c.hydrationEnabled {
		return
	}
	key := c.keyForProfile(pk)
	if _, loaded := c.hydrating.LoadOrStore(key, struct{}{}); loaded {
		return
	}
	go func() {
		defer c.hydrating.Delete(key)
		ctx, cancel := context.WithTimeout(context.Background(), c.hydrationTimeout)
		defer cancel()
		schema := ""
		if c.metrics != nil {
			c.metrics.HydrationStart(schema, TableProfiles)
		}

		q := &hook.QueryContext{
			Op:     hook.OpGet,
			Table:  TableProfiles,
			Schema: schema,
			PK:     pk,
			CallOptions: CallOptions[ProfileFieldOptions]{
				FieldOptions: fullParentFieldOptionsProfile(),
				SkipHooks:    true,
			},
		}
		result, err := next(ctx, q)
		if err != nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProfiles, err)
			}
			return
		}
		entity, ok := result.(*Profile)
		if !ok || entity == nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProfiles, nil)
			}
			return
		}

		if c.breaker != nil && !c.breaker.Allow() {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProfiles, nil)
			}
			return
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForProfile())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableProfiles, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableProfiles, setErr)
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableProfiles, setErr)
			}
			return
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableProfiles)
			c.metrics.HydrationComplete(schema, TableProfiles, nil)
		}
	}()
}

// keyForUser builds the cache key for User by PK.
func (c *Cache) keyForUser(pk int64) string {
	return cache.BuildKey(c.prefix, "", "users", fingerprintUser, pk)
}

// ttlForUser returns the resolved TTL for User cache entries.
func (c *Cache) ttlForUser() time.Duration {
	return time.Duration(3600000000000)
}

// hasAnyRelationshipUser reports whether fo has any relationship-typed
// flag set. Returns false when fo is nil or when only column flags are set.
func hasAnyRelationshipUser(fo any) bool {
	if fo == nil {
		return false
	}
	typed, ok := fo.(*UserFieldOptions)
	if !ok || typed == nil {
		return false
	}
	if typed.Profile != nil {
		return true
	}
	return false
}

// fullParentFieldOptionsUser returns a FieldOptions with every column
// flag set to true and every relationship flag nil — used by hydration to
// guarantee parent-only results regardless of nil-FieldOptions semantics
// elsewhere.
func fullParentFieldOptionsUser() *UserFieldOptions {
	return &UserFieldOptions{
		ID:    true,
		Name:  true,
		Email: true,
	}
}

// readThroughUser implements the cache read-through path for User:
// probe cache → hit returns decoded entity, miss runs the DB query under
// singleflight dedup and populates cache. Every backend call is breaker-gated;
// errors are routed through cache.RouteError and fall through to the DB so
// a cache outage never breaks the caller.
func (c *Cache) readThroughUser(ctx context.Context, pk int64, q *hook.QueryContext, next hook.QueryHandler) (any, error) {
	key := c.keyForUser(pk)
	schema := ""

	if c.breaker == nil || c.breaker.Allow() {
		getStart := time.Now()
		entity, hit, err := cache.GetAs[*User](ctx, c.backend, c.serializer, key)
		if c.metrics != nil {
			c.metrics.GetLatency(schema, TableUsers, time.Since(getStart))
		}
		if err != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "get", schema, TableUsers, err)
		} else if hit {
			if c.metrics != nil {
				c.metrics.Hit(schema, TableUsers)
			}
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
			return entity, nil
		} else {
			if c.metrics != nil {
				c.metrics.Miss(schema, TableUsers)
			}
			// A clean miss is a successful backend round-trip — it resets
			// the consecutive-failure counter and closes a HalfOpen probe.
			if c.breaker != nil {
				c.breaker.RecordSuccess()
			}
		}
	} else if c.metrics != nil {
		c.metrics.Miss(schema, TableUsers)
	}

	// Partial fetches must not write back to cache (invariant:
	// only full entities). On miss, run the DB through `next` with the
	// caller's partial FieldOptions, kick off fire-and-forget hydration to
	// refill the cache with the full entity, and return the
	// partial result directly. The partial + hydration-disabled case is
	// filtered out earlier in QueryHook.
	if extractFieldOptions(q.CallOptions) != nil {
		result, err := next(ctx, q)
		if err != nil {
			return nil, err
		}
		c.hydrateUser(pk, next)
		return result, nil
	}

	ch := c.sf.DoChan(key, func() (any, error) {
		// In-flight cache re-check: a sibling flight may have populated the
		// cache between this caller's outer Get-miss and entering the flight.
		// Without this, late stragglers that arrive after the sibling flight
		// completed would register a new flight and run a duplicate DB query.
		// The outer probe already recorded the Miss / breaker success; this
		// inner re-check is dedup machinery, not an observable cache event, so
		// it emits no metrics.
		if c.breaker == nil || c.breaker.Allow() {
			if entity, hit, err := cache.GetAs[*User](ctx, c.backend, c.serializer, key); err == nil && hit {
				return entity, nil
			}
		}
		result, fetchErr := next(ctx, q)
		if fetchErr != nil {
			return nil, fetchErr
		}
		entity, ok := result.(*User)
		if !ok || entity == nil {
			return result, nil
		}
		if c.breaker != nil && !c.breaker.Allow() {
			return result, nil
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForUser())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableUsers, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableUsers, setErr)
			return result, nil
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableUsers)
		}
		return result, nil
	})

	select {
	case res := <-ch:
		return res.Val, res.Err
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}

// setUser caches a full User entity. Called by the mutation hook
// after a successful Create / CreateMany to populate the cache with the new
// entity. The PK is read from the entity itself so this never
// depends on parallel ordering with m.AffectedPKs (GetMany does not guarantee
// result order). Failures route through cache.RouteError and never surface to
// the caller path; a cache outage can delay the next Get but never breaks a
// mutation.
func (c *Cache) setUser(ctx context.Context, entity *User) {
	if entity == nil {
		return
	}
	if c.breaker != nil && !c.breaker.Allow() {
		return
	}
	key := c.keyForUser(entity.ID)
	schema := ""
	setStart := time.Now()
	err := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForUser())
	if c.metrics != nil {
		c.metrics.SetLatency(schema, TableUsers, time.Since(setStart))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableUsers, err)
		return
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Set(schema, TableUsers)
	}
}

// hydrateUser launches at most one background hydration per (table, pk).
// Runs with a fresh context.Background() timeout — does NOT inherit the
// caller's ctx. Re-runs the Get through the
// downstream chain with full-parent FieldOptions (every column true, every
// relationship nil) and SkipHooks: true so the refill pulls a full entity,
// then serializes and populates the cache under the full-entity key. Errors
// surface via metrics.HydrationComplete + cache.RouteError; the caller path
// is never affected.
func (c *Cache) hydrateUser(pk int64, next hook.QueryHandler) {
	if !c.hydrationEnabled {
		return
	}
	key := c.keyForUser(pk)
	if _, loaded := c.hydrating.LoadOrStore(key, struct{}{}); loaded {
		return
	}
	go func() {
		defer c.hydrating.Delete(key)
		ctx, cancel := context.WithTimeout(context.Background(), c.hydrationTimeout)
		defer cancel()
		schema := ""
		if c.metrics != nil {
			c.metrics.HydrationStart(schema, TableUsers)
		}

		q := &hook.QueryContext{
			Op:     hook.OpGet,
			Table:  TableUsers,
			Schema: schema,
			PK:     pk,
			CallOptions: CallOptions[UserFieldOptions]{
				FieldOptions: fullParentFieldOptionsUser(),
				SkipHooks:    true,
			},
		}
		result, err := next(ctx, q)
		if err != nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableUsers, err)
			}
			return
		}
		entity, ok := result.(*User)
		if !ok || entity == nil {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableUsers, nil)
			}
			return
		}

		if c.breaker != nil && !c.breaker.Allow() {
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableUsers, nil)
			}
			return
		}
		setStart := time.Now()
		setErr := cache.SetAs(ctx, c.backend, c.serializer, key, entity, c.ttlForUser())
		if c.metrics != nil {
			c.metrics.SetLatency(schema, TableUsers, time.Since(setStart))
		}
		if setErr != nil {
			cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "set", schema, TableUsers, setErr)
			if c.metrics != nil {
				c.metrics.HydrationComplete(schema, TableUsers, setErr)
			}
			return
		}
		if c.breaker != nil {
			c.breaker.RecordSuccess()
		}
		if c.metrics != nil {
			c.metrics.Set(schema, TableUsers)
			c.metrics.HydrationComplete(schema, TableUsers, nil)
		}
	}()
}

// patternsForSourceTable returns the view BuildTablePattern strings that the
// mutation hook must invalidate after a mutation on source table.
func (c *Cache) patternsForSourceTable(table hook.TableName) []string {
	switch table {
	case hook.TableName("products"):
		return []string{
			"sqlgen:product_summary:*",
		}
	}
	return nil
}

// Invalidate clears a single cached entry. pk must match the table's PK type
// (scalar or generated XXXPK struct value).
func (c *Cache) Invalidate(ctx context.Context, table hook.TableName, pk any) error {
	return c.InvalidateMany(ctx, table, []any{pk})
}

// InvalidateMany clears multiple cached entries for the given table. pk
// elements must match the table's PK type — wrong-type elements return the
// descriptive error from cache.KeysFromAny.
//
// Tenanted tables require a tenant scope to construct keys
// and are not callable through this path — use the cache hook
// auto-invalidation (mutations resolve tenant once and invalidate
// automatically) or InvalidateTable / BuildTenantTablePattern for
// pattern-based clears.
func (c *Cache) InvalidateMany(ctx context.Context, table hook.TableName, pks []any) error {
	var (
		keys []string
		err  error
	)
	switch table {
	case TableArticles:
		keys, err = cache.KeysFromAny(pks, c.keyForArticle)
	case TableOrderItems:
		keys, err = cache.KeysFromAny(pks, c.keyForOrderItem)
	case TableProducts:
		keys, err = cache.KeysFromAny(pks, c.keyForProduct)
	case TableProfiles:
		keys, err = cache.KeysFromAny(pks, c.keyForProfile)
	case TableUsers:
		keys, err = cache.KeysFromAny(pks, c.keyForUser)
	default:
		return fmt.Errorf("cache: unknown or non-cached table %q", table)
	}
	if err != nil {
		return fmt.Errorf("cache: InvalidateMany(%q): %w", table, err)
	}
	return c.invalidateKeys(ctx, table, keys)
}

// InvalidateTable clears every cached entry for the given table, including
// orphaned prior-generation entries (BuildTablePattern is fingerprint-agnostic).
func (c *Cache) InvalidateTable(ctx context.Context, table hook.TableName) error {
	schema, name, ok := cacheRelationFor(table)
	if !ok {
		return fmt.Errorf("cache: unknown or non-cached table %q", table)
	}
	pattern := cache.BuildTablePattern(c.prefix, schema, name)
	return c.invalidatePattern(ctx, table, pattern)
}

// cacheRelationFor resolves the static key segments for a cached table or
// view: its schema and its bare SQL name. The name is not string(table) — a
// hook.TableName value carries the schema too ("public.orders"), and
// the key grammar joins the two itself. The third return is false when the
// name is not a cached table or view — callers must return the canonical
// "unknown or non-cached table" error.
func cacheRelationFor(table hook.TableName) (schema, name string, ok bool) {
	switch table {
	case TableArticles:
		return "", "articles", true
	case TableOrderItems:
		return "", "order_items", true
	case TableProducts:
		return "", "products", true
	case TableProfiles:
		return "", "profiles", true
	case TableUsers:
		return "", "users", true
	case TableProductSummaries:
		return "", "product_summary", true
	}
	return "", "", false
}

// cacheSchemaFor resolves the static schema segment for a cached table or view.
// The second return is false when the name is not a cached table or view —
// callers must return the canonical "unknown or non-cached table" error.
func cacheSchemaFor(table hook.TableName) (string, bool) {
	schema, _, ok := cacheRelationFor(table)
	return schema, ok
}

// invalidateKeys centralizes metrics, circuit-breaker, latency timing, and
// backend dispatch for key-based invalidation. Public Invalidate /
// InvalidateMany paths converge here.
func (c *Cache) invalidateKeys(ctx context.Context, table hook.TableName, keys []string) error {
	if len(keys) == 0 {
		return nil
	}
	if c.breaker != nil && !c.breaker.Allow() {
		return nil
	}
	schema, _ := cacheSchemaFor(table)
	start := time.Now()
	err := c.backend.InvalidateMany(ctx, keys)
	if c.metrics != nil {
		c.metrics.InvalidateLatency(schema, table, time.Since(start))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "invalidate_many", schema, table, err)
		return err
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Invalidate(schema, table)
	}
	return nil
}

// invalidatePattern centralizes metrics, circuit-breaker, latency timing, and
// backend dispatch for pattern-based invalidation (InvalidateTable / view
// invalidation / the tenant capture-gap fallback). Mutation invalidation does
// not come through here — every op, *Where included, evicts by key.
func (c *Cache) invalidatePattern(ctx context.Context, table hook.TableName, pattern string) error {
	if c.breaker != nil && !c.breaker.Allow() {
		return nil
	}
	schema, _ := cacheSchemaFor(table)
	start := time.Now()
	err := c.backend.InvalidatePattern(ctx, pattern)
	if c.metrics != nil {
		c.metrics.InvalidateLatency(schema, table, time.Since(start))
	}
	if err != nil {
		cache.RouteError(ctx, c.metrics, c.onError, c.breaker, "invalidate_pattern", schema, table, err)
		return err
	}
	if c.breaker != nil {
		c.breaker.RecordSuccess()
	}
	if c.metrics != nil {
		c.metrics.Invalidate(schema, table)
	}
	return nil
}

// cacheSkipper is implemented by CallOptions to check the SkipCache flag.
type cacheSkipper interface {
	skipCache() bool
}

func (o CallOptions[FO]) skipCache() bool { return o.SkipCache }

// QueryHook returns the cache read-through hook. The hook dispatches to a
// per-table typed helper that knows the concrete entity type; wrong-type PKs
// or non-matching tables fall through to the DB so the cache never breaks the
// caller path.
func (c *Cache) QueryHook() hook.QueryHook {
	return func(next hook.QueryHandler) hook.QueryHandler {
		return func(ctx context.Context, q *hook.QueryContext) (any, error) {
			if q.Op == hook.OpRefresh {
				result, err := next(ctx, q)
				if err != nil {
					return result, err
				}
				c.dispatchRefresh(ctx, q.Table)
				return result, nil
			}
			if q.Op != hook.OpGet {
				return next(ctx, q)
			}
			if skipper, ok := q.CallOptions.(cacheSkipper); ok && skipper.skipCache() {
				return next(ctx, q)
			}
			// Relationship-loaded Gets bypass the cache entirely.
			if hasAnyRelationshipFieldOptions(q.Table, q.CallOptions) {
				return next(ctx, q)
			}
			// Partial fetches with hydration disabled are pure pass-through
			// With hydration enabled, partial fetches still go
			// through read-through so a cached full entity can satisfy the
			// request; the miss path in readThrough{Table} triggers
			// fire-and-forget hydration without caching the partial result.
			if !c.hydrationEnabled && extractFieldOptions(q.CallOptions) != nil {
				return next(ctx, q)
			}
			switch q.Table {
			case TableArticles:
				pk, ok := q.PK.(int64)
				if !ok {
					return next(ctx, q)
				}
				return c.readThroughArticle(ctx, pk, q, next)
			case TableOrderItems:
				pk, ok := q.PK.(OrderItemPK)
				if !ok {
					return next(ctx, q)
				}
				return c.readThroughOrderItem(ctx, pk, q, next)
			case TableProducts:
				pk, ok := q.PK.(int64)
				if !ok {
					return next(ctx, q)
				}
				return c.readThroughProduct(ctx, pk, q, next)
			case TableProfiles:
				pk, ok := q.PK.(int64)
				if !ok {
					return next(ctx, q)
				}
				return c.readThroughProfile(ctx, pk, q, next)
			case TableUsers:
				pk, ok := q.PK.(int64)
				if !ok {
					return next(ctx, q)
				}
				return c.readThroughUser(ctx, pk, q, next)
			}
			return next(ctx, q)
		}
	}
}

// MutationHook returns the cache invalidation hook. Entity + view invalidation
// fires after every mutation; inside a transaction it's deferred via
// tx.OnCommit (FIFO after the event hook).
func (c *Cache) MutationHook() hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, m *hook.MutationContext) (any, error) {
			result, err := next(ctx, m)
			if err != nil {
				return result, err
			}
			if skipper, ok := m.CallOptions.(cacheSkipper); ok && skipper.skipCache() {
				return result, nil
			}
			c.dispatchMutation(ctx, m, result)
			return result, nil
		}
	}
}

// dispatchMutation fans out entity + view invalidation for a mutation. The
// two callbacks are registered in-order on the transaction so the FIFO
// guarantee on tx.OnCommit preserves entity-before-view ordering. The
// mutation's result is forwarded so Create / CreateMany can populate the
// cache with the new entity.
func (c *Cache) dispatchMutation(ctx context.Context, m *hook.MutationContext, result any) {
	table := m.Table
	op := m.Op
	affected := append([]any(nil), m.AffectedPKs...)
	// Partial FieldOptions / relationship-loaded entities must not be cached
	// The simplest safe check: only cache on Create when
	// CallOptions.FieldOptions is unset — matching the "full, no relationships"
	// row of the cache behavior table.
	fieldOptsSet := extractFieldOptions(m.CallOptions) != nil

	entityOp := func(ctx context.Context) error {
		switch op {
		case hook.OpCreate:
			if fieldOptsSet {
				return nil
			}
			switch table {
			case TableArticles:
				if entity, ok := result.(*Article); ok {
					c.setArticle(ctx, entity)
				}
			case TableOrderItems:
				if entity, ok := result.(*OrderItem); ok {
					c.setOrderItem(ctx, entity)
				}
			case TableProducts:
				if entity, ok := result.(*Product); ok {
					c.setProduct(ctx, entity)
				}
			case TableProfiles:
				if entity, ok := result.(*Profile); ok {
					c.setProfile(ctx, entity)
				}
			case TableUsers:
				if entity, ok := result.(*User); ok {
					c.setUser(ctx, entity)
				}
			}
			return nil
		case hook.OpCreateMany:
			if fieldOptsSet {
				return nil
			}
			switch table {
			case TableArticles:
				if entities, ok := result.([]*Article); ok {
					for _, entity := range entities {
						c.setArticle(ctx, entity)
					}
				}
			case TableOrderItems:
				if entities, ok := result.([]*OrderItem); ok {
					for _, entity := range entities {
						c.setOrderItem(ctx, entity)
					}
				}
			case TableProducts:
				if entities, ok := result.([]*Product); ok {
					for _, entity := range entities {
						c.setProduct(ctx, entity)
					}
				}
			case TableProfiles:
				if entities, ok := result.([]*Profile); ok {
					for _, entity := range entities {
						c.setProfile(ctx, entity)
					}
				}
			case TableUsers:
				if entities, ok := result.([]*User); ok {
					for _, entity := range entities {
						c.setUser(ctx, entity)
					}
				}
			}
			return nil
		case hook.OpUpdate, hook.OpUpsert, hook.OpSoftDelete, hook.OpHardDelete,
			hook.OpRestore, hook.OpIncrement,
			hook.OpUpsertMany, hook.OpUpdateMany, hook.OpSoftDeleteMany, hook.OpHardDeleteMany, hook.OpRestoreMany,
			hook.OpUpdateWhere, hook.OpSoftDeleteWhere, hook.OpHardDeleteWhere, hook.OpRestoreWhere:
			// Every op here evicts by key, the *Where ops included: each
			// captures the affected rows' PKs on the MutationContext before
			// it returns, so the predicate's row set is known by the time
			// invalidation runs. Prior-fingerprint orphans are
			// left to TTL and to a deliberate InvalidateTable sweep rather
			// than to a whole-table pattern wipe on every *Where call.
			//
			// OpUpsertMany belongs here and not with OpCreateMany: it
			// invalidates many, evicting by key like the
			// other *Many ops rather than writing the returned entities
			// through. It is a direct write path with its own op, so the
			// switch needs it named explicitly — there is no permissive
			// default that would otherwise cover it.
			if len(affected) == 0 {
				return nil
			}
			// A table the config left uncached still reaches this hook. It
			// has nothing to evict, and the "non-cached table" error would
			// otherwise surface out of a CallbackSync commit for a write
			// that already succeeded.
			if _, ok := cacheSchemaFor(table); !ok {
				return nil
			}
			return c.InvalidateMany(ctx, table, affected)
		}
		return nil
	}

	viewOp := func(ctx context.Context) error {
		patterns := c.patternsForSourceTable(table)
		if len(patterns) == 0 {
			return nil
		}
		for _, pattern := range patterns {
			if err := c.invalidatePattern(ctx, table, pattern); err != nil {
				return err
			}
		}
		return nil
	}

	if tx := database.FromContext(ctx); tx != nil && !tx.IsClosed() {
		tx.OnCommit(entityOp)
		tx.OnCommit(viewOp)
		return
	}
	_ = entityOp(ctx)
	_ = viewOp(ctx)
}

// dispatchRefresh clears every cached entry for a refreshed materialized view:
// a refresh replaces the stored rows, so pre-refresh cached reads would serve
// doubly-stale data. Views that are not
// cached are a pure no-op. Inside a transaction the clear is deferred via
// tx.OnCommit — the refreshed rows are invisible to other connections until
// commit, so an eager clear could be repopulated with pre-commit rows (the
// same race the mutation path defers for). Invalidation
// errors route through the standard cache error path and never fail the
// refresh.
func (c *Cache) dispatchRefresh(ctx context.Context, table hook.TableName) {
	if !c.isCachedView(table) {
		return
	}
	refreshOp := func(ctx context.Context) error {
		return c.InvalidateTable(ctx, table)
	}
	if tx := database.FromContext(ctx); tx != nil && !tx.IsClosed() {
		tx.OnCommit(refreshOp)
		return
	}
	_ = refreshOp(ctx)
}

// isCachedView reports whether table names a cached view.
func (c *Cache) isCachedView(table hook.TableName) bool {
	switch table {
	case TableProductSummaries:
		return true
	}
	return false
}

// hasAnyRelationshipFieldOptions routes the FieldOptions relationship check
// to the per-table hasAnyRelationshipXxx helper. FieldOptions is a
// per-table pointer type — this dispatch resolves the CallOptions generic
// parameter to the right concrete helper.
func hasAnyRelationshipFieldOptions(table hook.TableName, callOpts any) bool {
	fo := extractFieldOptions(callOpts)
	if fo == nil {
		return false
	}
	switch table {
	case TableArticles:
		return hasAnyRelationshipArticle(fo)
	case TableOrderItems:
		return hasAnyRelationshipOrderItem(fo)
	case TableProducts:
		return hasAnyRelationshipProduct(fo)
	case TableProfiles:
		return hasAnyRelationshipProfile(fo)
	case TableUsers:
		return hasAnyRelationshipUser(fo)
	}
	return false
}

// extractFieldOptions pulls the FieldOptions pointer out of a resolved
// CallOptions[FO] via a small interface probe. Returns nil when the
// CallOptions shape does not expose FieldOptions.
type fieldOptionsAccessor interface {
	fieldOptions() any
}

func (o CallOptions[FO]) fieldOptions() any {
	if o.FieldOptions == nil {
		return nil
	}
	return o.FieldOptions
}

func extractFieldOptions(callOpts any) any {
	if callOpts == nil {
		return nil
	}
	if accessor, ok := callOpts.(fieldOptionsAccessor); ok {
		return accessor.fieldOptions()
	}
	return nil
}

// Close stops the invalidation subscription and closes the backend when it
// implements io.Closer. Hydration goroutines are not awaited — they exit on
// their timeout deadline.
func (c *Cache) Close() error {
	if c.invalidationSub != nil {
		_ = c.invalidationSub.Unsubscribe()
	}
	if closer, ok := c.backend.(io.Closer); ok {
		return closer.Close()
	}
	return nil
}
