package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models/graph/model"
)

// CreateBinaryKeyEvent is the resolver for the createBinaryKeyEvent field.
func (r *mutationResolver) CreateBinaryKeyEvent(ctx context.Context, input gqlmodel.CreateBinaryKeyEventInput) (*models.BinaryKeyEvent, error) {
	return r.M.CreateBinaryKeyEvent(ctx, translateCreateBinaryKeyEventInput(input))
}

// CreateBinaryKeyEvents is the resolver for the createBinaryKeyEvents field.
func (r *mutationResolver) CreateBinaryKeyEvents(ctx context.Context, inputs []*gqlmodel.CreateBinaryKeyEventInput) ([]*models.BinaryKeyEvent, error) {
	xs := make([]*models.CreateBinaryKeyEventInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateBinaryKeyEventInput(*in))
	}
	return r.M.CreateBinaryKeyEvents(ctx, xs)
}

// UpdateBinaryKeyEvent is the resolver for the updateBinaryKeyEvent field.
// No numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateBinaryKeyEvent(ctx context.Context, id int, input gqlmodel.UpdateBinaryKeyEventInput) (*models.BinaryKeyEvent, error) {
	setIn := translateUpdateBinaryKeyEventInput(input)
	hasSet := hasUpdateBinaryKeyEventSetFields(input)
	return r.M.UpdateBinaryKeyEvent(ctx, id, setIn, hasSet)
}

// UpdateBinaryKeyEvents is the resolver for the updateBinaryKeyEvents field.
func (r *mutationResolver) UpdateBinaryKeyEvents(ctx context.Context, filter gqlmodel.BinaryKeyEventFilter, input gqlmodel.UpdateBinaryKeyEventInput) ([]*models.BinaryKeyEvent, error) {
	return r.M.UpdateBinaryKeyEvents(ctx, translateBinaryKeyEventFilter(&filter), translateUpdateBinaryKeyEventInput(input))
}

// UpsertBinaryKeyEvent is the resolver for the upsertBinaryKeyEvent field.
func (r *mutationResolver) UpsertBinaryKeyEvent(ctx context.Context, input gqlmodel.CreateBinaryKeyEventInput) (*models.BinaryKeyEvent, error) {
	return r.M.UpsertBinaryKeyEvent(ctx, translateCreateBinaryKeyEventInput(input))
}

// DeleteBinaryKeyEvent is the resolver for the deleteBinaryKeyEvent field.
func (r *mutationResolver) DeleteBinaryKeyEvent(ctx context.Context, id int) (bool, error) {
	return r.M.DeleteBinaryKeyEvent(ctx, id)
}

// BinaryKeyEvent is the resolver for the binaryKeyEvent field.
func (r *queryResolver) BinaryKeyEvent(ctx context.Context, id int) (*models.BinaryKeyEvent, error) {
	return r.Q.BinaryKeyEvent(ctx, id)
}

// BinaryKeyEvents is the resolver for the binaryKeyEvents field.
func (r *queryResolver) BinaryKeyEvents(ctx context.Context, filter *gqlmodel.BinaryKeyEventFilter, first *int, after *string, last *int, before *string) (*models.Connection[models.BinaryKeyEvent], error) {
	return r.Q.BinaryKeyEvents(ctx, translateBinaryKeyEventFilter(filter), first, after, last, before)
}

// BinaryKeyEventList is the resolver for the binaryKeyEventList field.
func (r *queryResolver) BinaryKeyEventList(ctx context.Context, filter *gqlmodel.BinaryKeyEventFilter, sort []*gqlmodel.BinaryKeyEventSort, limit *int, offset *int) (*models.PaginateResult[models.BinaryKeyEvent], error) {
	return r.Q.BinaryKeyEventList(ctx, translateBinaryKeyEventFilter(filter), translateBinaryKeyEventSort(sort), limit, offset)
}
