// Code generated by sqlgen dev. DO NOT EDIT.
package models

import (
	"github.com/teandresmith/sqlgen/sql"
)

// ArticleSorter provides type-safe sort helpers for the Article entity.
// Each method returns a sql.Sort for the corresponding column.
type ArticleSorter struct{}

// NewArticleSorter returns a new ArticleSorter.
func NewArticleSorter() ArticleSorter { return ArticleSorter{} }

// Author returns a sort for the author column in the given direction.
func (s ArticleSorter) Author(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "author", Direction: direction}
}

// Body returns a sort for the body column in the given direction.
func (s ArticleSorter) Body(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "body", Direction: direction}
}

// CreatedAt returns a sort for the created_at column in the given direction.
func (s ArticleSorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// DeletedAt returns a sort for the deleted_at column in the given direction.
func (s ArticleSorter) DeletedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "deleted_at", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s ArticleSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Title returns a sort for the title column in the given direction.
func (s ArticleSorter) Title(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "title", Direction: direction}
}

// AssetSorter provides type-safe sort helpers for the Asset entity.
// Each method returns a sql.Sort for the corresponding column.
type AssetSorter struct{}

// NewAssetSorter returns a new AssetSorter.
func NewAssetSorter() AssetSorter { return AssetSorter{} }

// CreatedAt returns a sort for the created_at column in the given direction.
func (s AssetSorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s AssetSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s AssetSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// AssetDocumentLinkSorter provides type-safe sort helpers for the AssetDocumentLink entity.
// Each method returns a sql.Sort for the corresponding column.
type AssetDocumentLinkSorter struct{}

// NewAssetDocumentLinkSorter returns a new AssetDocumentLinkSorter.
func NewAssetDocumentLinkSorter() AssetDocumentLinkSorter { return AssetDocumentLinkSorter{} }

// AssetID returns a sort for the asset_id column in the given direction.
func (s AssetDocumentLinkSorter) AssetID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "asset_id", Direction: direction}
}

// DocumentID returns a sort for the document_id column in the given direction.
func (s AssetDocumentLinkSorter) DocumentID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "document_id", Direction: direction}
}

// BinaryKeySorter provides type-safe sort helpers for the BinaryKey entity.
// Each method returns a sql.Sort for the corresponding column.
type BinaryKeySorter struct{}

// NewBinaryKeySorter returns a new BinaryKeySorter.
func NewBinaryKeySorter() BinaryKeySorter { return BinaryKeySorter{} }

// CreatedAt returns a sort for the created_at column in the given direction.
func (s BinaryKeySorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s BinaryKeySorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s BinaryKeySorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// BinaryKeyEventSorter provides type-safe sort helpers for the BinaryKeyEvent entity.
// Each method returns a sql.Sort for the corresponding column.
type BinaryKeyEventSorter struct{}

// NewBinaryKeyEventSorter returns a new BinaryKeyEventSorter.
func NewBinaryKeyEventSorter() BinaryKeyEventSorter { return BinaryKeyEventSorter{} }

// BinaryKeyID returns a sort for the binary_key_id column in the given direction.
func (s BinaryKeyEventSorter) BinaryKeyID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "binary_key_id", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s BinaryKeyEventSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Label returns a sort for the label column in the given direction.
func (s BinaryKeyEventSorter) Label(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "label", Direction: direction}
}

// CategorySorter provides type-safe sort helpers for the Category entity.
// Each method returns a sql.Sort for the corresponding column.
type CategorySorter struct{}

// NewCategorySorter returns a new CategorySorter.
func NewCategorySorter() CategorySorter { return CategorySorter{} }

// Description returns a sort for the description column in the given direction.
func (s CategorySorter) Description(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "description", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s CategorySorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s CategorySorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// DigitLeadingColumnSorter provides type-safe sort helpers for the DigitLeadingColumn entity.
// Each method returns a sql.Sort for the corresponding column.
type DigitLeadingColumnSorter struct{}

// NewDigitLeadingColumnSorter returns a new DigitLeadingColumnSorter.
func NewDigitLeadingColumnSorter() DigitLeadingColumnSorter { return DigitLeadingColumnSorter{} }

// Col1stPlace returns a sort for the 1st_place column in the given direction.
func (s DigitLeadingColumnSorter) Col1stPlace(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "1st_place", Direction: direction}
}

// Col2010Revenue returns a sort for the 2010_revenue column in the given direction.
func (s DigitLeadingColumnSorter) Col2010Revenue(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "2010_revenue", Direction: direction}
}

// Col2024Quota returns a sort for the 2024_quota column in the given direction.
func (s DigitLeadingColumnSorter) Col2024Quota(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "2024_quota", Direction: direction}
}

// Col3dModelURL returns a sort for the 3d_model_url column in the given direction.
func (s DigitLeadingColumnSorter) Col3dModelURL(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "3d_model_url", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s DigitLeadingColumnSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// DocumentSorter provides type-safe sort helpers for the Document entity.
// Each method returns a sql.Sort for the corresponding column.
type DocumentSorter struct{}

// NewDocumentSorter returns a new DocumentSorter.
func NewDocumentSorter() DocumentSorter { return DocumentSorter{} }

// CreatedAt returns a sort for the created_at column in the given direction.
func (s DocumentSorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// EntityID returns a sort for the entity_id column in the given direction.
func (s DocumentSorter) EntityID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "entity_id", Direction: direction}
}

// EntityType returns a sort for the entity_type column in the given direction.
func (s DocumentSorter) EntityType(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "entity_type", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s DocumentSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s DocumentSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// KeyOnlyRowSorter provides type-safe sort helpers for the KeyOnlyRow entity.
// Each method returns a sql.Sort for the corresponding column.
type KeyOnlyRowSorter struct{}

// NewKeyOnlyRowSorter returns a new KeyOnlyRowSorter.
func NewKeyOnlyRowSorter() KeyOnlyRowSorter { return KeyOnlyRowSorter{} }

// ID returns a sort for the id column in the given direction.
func (s KeyOnlyRowSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// OrderSorter provides type-safe sort helpers for the Order entity.
// Each method returns a sql.Sort for the corresponding column.
type OrderSorter struct{}

// NewOrderSorter returns a new OrderSorter.
func NewOrderSorter() OrderSorter { return OrderSorter{} }

// ID returns a sort for the id column in the given direction.
func (s OrderSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Notes returns a sort for the notes column in the given direction.
func (s OrderSorter) Notes(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "notes", Direction: direction}
}

// OrderedAt returns a sort for the ordered_at column in the given direction.
func (s OrderSorter) OrderedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "ordered_at", Direction: direction}
}

// Status returns a sort for the status column in the given direction.
func (s OrderSorter) Status(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "status", Direction: direction}
}

// Total returns a sort for the total column in the given direction.
func (s OrderSorter) Total(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "total", Direction: direction}
}

// UserID returns a sort for the user_id column in the given direction.
func (s OrderSorter) UserID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "user_id", Direction: direction}
}

// OrderItemSorter provides type-safe sort helpers for the OrderItem entity.
// Each method returns a sql.Sort for the corresponding column.
type OrderItemSorter struct{}

// NewOrderItemSorter returns a new OrderItemSorter.
func NewOrderItemSorter() OrderItemSorter { return OrderItemSorter{} }

// ID returns a sort for the id column in the given direction.
func (s OrderItemSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// OrderID returns a sort for the order_id column in the given direction.
func (s OrderItemSorter) OrderID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "order_id", Direction: direction}
}

// ProductID returns a sort for the product_id column in the given direction.
func (s OrderItemSorter) ProductID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "product_id", Direction: direction}
}

// Quantity returns a sort for the quantity column in the given direction.
func (s OrderItemSorter) Quantity(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "quantity", Direction: direction}
}

// UnitPrice returns a sort for the unit_price column in the given direction.
func (s OrderItemSorter) UnitPrice(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "unit_price", Direction: direction}
}

// OwnerSorter provides type-safe sort helpers for the Owner entity.
// Each method returns a sql.Sort for the corresponding column.
type OwnerSorter struct{}

// NewOwnerSorter returns a new OwnerSorter.
func NewOwnerSorter() OwnerSorter { return OwnerSorter{} }

// Name returns a sort for the name column in the given direction.
func (s OwnerSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// OwnerKey returns a sort for the owner_key column in the given direction.
func (s OwnerSorter) OwnerKey(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "owner_key", Direction: direction}
}

// OwnerProfileSorter provides type-safe sort helpers for the OwnerProfile entity.
// Each method returns a sql.Sort for the corresponding column.
type OwnerProfileSorter struct{}

// NewOwnerProfileSorter returns a new OwnerProfileSorter.
func NewOwnerProfileSorter() OwnerProfileSorter { return OwnerProfileSorter{} }

// Bio returns a sort for the bio column in the given direction.
func (s OwnerProfileSorter) Bio(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "bio", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s OwnerProfileSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// OwnerID returns a sort for the owner_id column in the given direction.
func (s OwnerProfileSorter) OwnerID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "owner_id", Direction: direction}
}

// ProductSorter provides type-safe sort helpers for the Product entity.
// Each method returns a sql.Sort for the corresponding column.
type ProductSorter struct{}

// NewProductSorter returns a new ProductSorter.
func NewProductSorter() ProductSorter { return ProductSorter{} }

// CategoryID returns a sort for the category_id column in the given direction.
func (s ProductSorter) CategoryID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "category_id", Direction: direction}
}

// CreatedAt returns a sort for the created_at column in the given direction.
func (s ProductSorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s ProductSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// InStock returns a sort for the in_stock column in the given direction.
func (s ProductSorter) InStock(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "in_stock", Direction: direction}
}

// Price returns a sort for the price column in the given direction.
func (s ProductSorter) Price(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "price", Direction: direction}
}

// SKU returns a sort for the sku column in the given direction.
func (s ProductSorter) SKU(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "sku", Direction: direction}
}

// Title returns a sort for the title column in the given direction.
func (s ProductSorter) Title(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "title", Direction: direction}
}

// WeightKg returns a sort for the weight_kg column in the given direction.
func (s ProductSorter) WeightKg(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "weight_kg", Direction: direction}
}

// ProductTagLabelSorter provides type-safe sort helpers for the ProductTagLabel entity.
// Each method returns a sql.Sort for the corresponding column.
type ProductTagLabelSorter struct{}

// NewProductTagLabelSorter returns a new ProductTagLabelSorter.
func NewProductTagLabelSorter() ProductTagLabelSorter { return ProductTagLabelSorter{} }

// Description returns a sort for the description column in the given direction.
func (s ProductTagLabelSorter) Description(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "description", Direction: direction}
}

// Label returns a sort for the label column in the given direction.
func (s ProductTagLabelSorter) Label(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "label", Direction: direction}
}

// ProductID returns a sort for the product_id column in the given direction.
func (s ProductTagLabelSorter) ProductID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "product_id", Direction: direction}
}

// TagName returns a sort for the tag_name column in the given direction.
func (s ProductTagLabelSorter) TagName(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "tag_name", Direction: direction}
}

// ProfileSorter provides type-safe sort helpers for the Profile entity.
// Each method returns a sql.Sort for the corresponding column.
type ProfileSorter struct{}

// NewProfileSorter returns a new ProfileSorter.
func NewProfileSorter() ProfileSorter { return ProfileSorter{} }

// GithubHandle returns a sort for the github_handle column in the given direction.
func (s ProfileSorter) GithubHandle(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "github_handle", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s ProfileSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// UserID returns a sort for the user_id column in the given direction.
func (s ProfileSorter) UserID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "user_id", Direction: direction}
}

// Verified returns a sort for the verified column in the given direction.
func (s ProfileSorter) Verified(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "verified", Direction: direction}
}

// Website returns a sort for the website column in the given direction.
func (s ProfileSorter) Website(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "website", Direction: direction}
}

// ReservedWordColumnSorter provides type-safe sort helpers for the ReservedWordColumn entity.
// Each method returns a sql.Sort for the corresponding column.
type ReservedWordColumnSorter struct{}

// NewReservedWordColumnSorter returns a new ReservedWordColumnSorter.
func NewReservedWordColumnSorter() ReservedWordColumnSorter { return ReservedWordColumnSorter{} }

// Ctx returns a sort for the ctx column in the given direction.
func (s ReservedWordColumnSorter) Ctx(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "ctx", Direction: direction}
}

// Err returns a sort for the err column in the given direction.
func (s ReservedWordColumnSorter) Err(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "err", Direction: direction}
}

// Error returns a sort for the error column in the given direction.
func (s ReservedWordColumnSorter) Error(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "error", Direction: direction}
}

// Func returns a sort for the func column in the given direction.
func (s ReservedWordColumnSorter) Func(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "func", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s ReservedWordColumnSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Interface returns a sort for the interface column in the given direction.
func (s ReservedWordColumnSorter) Interface(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "interface", Direction: direction}
}

// Len returns a sort for the len column in the given direction.
func (s ReservedWordColumnSorter) Len(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "len", Direction: direction}
}

// Make returns a sort for the make column in the given direction.
func (s ReservedWordColumnSorter) Make(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "make", Direction: direction}
}

// Map returns a sort for the map column in the given direction.
func (s ReservedWordColumnSorter) Map(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "map", Direction: direction}
}

// New returns a sort for the new column in the given direction.
func (s ReservedWordColumnSorter) New(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "new", Direction: direction}
}

// Type returns a sort for the type column in the given direction.
func (s ReservedWordColumnSorter) Type(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "type", Direction: direction}
}

// SluggedRowSorter provides type-safe sort helpers for the SluggedRow entity.
// Each method returns a sql.Sort for the corresponding column.
type SluggedRowSorter struct{}

// NewSluggedRowSorter returns a new SluggedRowSorter.
func NewSluggedRowSorter() SluggedRowSorter { return SluggedRowSorter{} }

// ID returns a sort for the id column in the given direction.
func (s SluggedRowSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s SluggedRowSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// Slug returns a sort for the slug column in the given direction.
func (s SluggedRowSorter) Slug(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "slug", Direction: direction}
}

// TagSorter provides type-safe sort helpers for the Tag entity.
// Each method returns a sql.Sort for the corresponding column.
type TagSorter struct{}

// NewTagSorter returns a new TagSorter.
func NewTagSorter() TagSorter { return TagSorter{} }

// ID returns a sort for the id column in the given direction.
func (s TagSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// IsDeleted returns a sort for the is_deleted column in the given direction.
func (s TagSorter) IsDeleted(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "is_deleted", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s TagSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// UserSorter provides type-safe sort helpers for the User entity.
// Each method returns a sql.Sort for the corresponding column.
type UserSorter struct{}

// NewUserSorter returns a new UserSorter.
func NewUserSorter() UserSorter { return UserSorter{} }

// Age returns a sort for the age column in the given direction.
func (s UserSorter) Age(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "age", Direction: direction}
}

// Avatar returns a sort for the avatar column in the given direction.
func (s UserSorter) Avatar(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "avatar", Direction: direction}
}

// Balance returns a sort for the balance column in the given direction.
func (s UserSorter) Balance(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "balance", Direction: direction}
}

// Bio returns a sort for the bio column in the given direction.
func (s UserSorter) Bio(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "bio", Direction: direction}
}

// CreatedAt returns a sort for the created_at column in the given direction.
func (s UserSorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// Email returns a sort for the email column in the given direction.
func (s UserSorter) Email(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "email", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s UserSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// IsActive returns a sort for the is_active column in the given direction.
func (s UserSorter) IsActive(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "is_active", Direction: direction}
}

// LoginCount returns a sort for the login_count column in the given direction.
func (s UserSorter) LoginCount(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "login_count", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s UserSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// Role returns a sort for the role column in the given direction.
func (s UserSorter) Role(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "role", Direction: direction}
}

// Score returns a sort for the score column in the given direction.
func (s UserSorter) Score(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "score", Direction: direction}
}

// UpdatedAt returns a sort for the updated_at column in the given direction.
func (s UserSorter) UpdatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "updated_at", Direction: direction}
}

// UserCategorySorter provides type-safe sort helpers for the UserCategory entity.
// Each method returns a sql.Sort for the corresponding column.
type UserCategorySorter struct{}

// NewUserCategorySorter returns a new UserCategorySorter.
func NewUserCategorySorter() UserCategorySorter { return UserCategorySorter{} }

// CategoryID returns a sort for the category_id column in the given direction.
func (s UserCategorySorter) CategoryID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "category_id", Direction: direction}
}

// UserID returns a sort for the user_id column in the given direction.
func (s UserCategorySorter) UserID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "user_id", Direction: direction}
}

// WarehouseSorter provides type-safe sort helpers for the Warehouse entity.
// Each method returns a sql.Sort for the corresponding column.
type WarehouseSorter struct{}

// NewWarehouseSorter returns a new WarehouseSorter.
func NewWarehouseSorter() WarehouseSorter { return WarehouseSorter{} }

// CreatedAt returns a sort for the created_at column in the given direction.
func (s WarehouseSorter) CreatedAt(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "created_at", Direction: direction}
}

// ExternalID returns a sort for the external_id column in the given direction.
func (s WarehouseSorter) ExternalID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "external_id", Direction: direction}
}

// ID returns a sort for the id column in the given direction.
func (s WarehouseSorter) ID(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "id", Direction: direction}
}

// Name returns a sort for the name column in the given direction.
func (s WarehouseSorter) Name(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "name", Direction: direction}
}

// NullablePrice returns a sort for the nullable_price column in the given direction.
func (s WarehouseSorter) NullablePrice(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "nullable_price", Direction: direction}
}

// Price returns a sort for the price column in the given direction.
func (s WarehouseSorter) Price(direction sql.SortDirection) sql.Sort {
	return sql.Sort{Column: "price", Direction: direction}
}
