// Code generated by sqlgen dev. DO NOT EDIT.
package models

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"iter"
	"slices"

	"github.com/teandresmith/sqlgen/comparator"
	"github.com/teandresmith/sqlgen/database"
	"github.com/teandresmith/sqlgen/hook"
	"github.com/teandresmith/sqlgen/omittable"
	"github.com/teandresmith/sqlgen/sql"
	"github.com/teandresmith/sqlgen/types"
	"golang.org/x/sync/errgroup"
)

type Product struct {
	ID         int64          `db:"id" json:"id"`
	CategoryID int64          `db:"category_id" json:"category_id"`
	Title      string         `db:"title" json:"title"`
	Price      float64        `db:"price" json:"price"`
	WeightKg   *float64       `db:"weight_kg" json:"weight_kg"`
	InStock    bool           `db:"in_stock" json:"in_stock"`
	SKU        string         `db:"sku" json:"sku"`
	CreatedAt  types.DateTime `db:"created_at" json:"created_at"`

	// OrderItems - one-to-many relationship with the order_items table.
	OrderItems []*OrderItem `db:"-" json:"order_items"`
	// ProductTagLabels - one-to-many relationship with the product_tag_labels table.
	ProductTagLabels []*ProductTagLabel `db:"-" json:"product_tag_labels"`
}

// ProductClient provides type-safe operations for the products table.
type ProductClient interface {
	// --- Read Operations ---

	// Get returns a single product by primary key.
	Get(ctx context.Context, id int64, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error)

	// GetMany returns products matching the given filter, field selection, and sort criteria.
	// When FieldOptions includes O2M or M2M relationships, they are loaded via an
	// errgroup fan-out — in parallel over the pool, and serialized by the
	// transaction's connection reservation when ctx carries one.
	GetMany(ctx context.Context, input *GetProductsInput, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error)

	// Exists returns true if a product with the given primary key exists.
	Exists(ctx context.Context, id int64, opts ...func(*CallOptions[ProductFieldOptions])) (bool, error)

	// ExistsWhere returns true if any product matches the given filter.
	ExistsWhere(ctx context.Context, filter *ProductFilter, opts ...func(*CallOptions[ProductFieldOptions])) (bool, error)

	// Count returns the number of products matching the given filter.
	Count(ctx context.Context, filter *ProductFilter, opts ...func(*CallOptions[ProductFieldOptions])) (int64, error)

	// --- Write Operations ---

	// Create inserts a new product and returns the created entity.
	Create(ctx context.Context, input *CreateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error)

	// CreateMany inserts multiple products in batches and returns all created entities.
	// Sub-batches are not automatically rolled back on failure — wrap in a transaction for atomicity.
	CreateMany(ctx context.Context, inputs []*CreateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error)

	// Update partially updates a product by primary key and returns the updated entity.
	// Only fields where IsSet() is true are included in the SET clause.
	// Returns ErrNotFound if the primary key does not exist.
	Update(ctx context.Context, id int64, input *UpdateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error)

	// UpdateMany updates multiple products and returns the updated entities.
	UpdateMany(ctx context.Context, items []UpdateProductItem, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error)

	// UpdateWhere updates all products matching the filter and returns the updated entities.
	// Idempotent — returns empty slice when no rows match.
	UpdateWhere(ctx context.Context, filter *ProductFilter, input *UpdateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error)

	// Upsert inserts a product or updates it on conflict and returns the resulting entity.
	Upsert(ctx context.Context, input *CreateProductInput, target ProductConflictTarget, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error)

	// UpsertMany inserts or updates multiple products in batches and returns all resulting entities.
	// Inputs resolving to the same conflict target are deduped, last occurrence wins.
	UpsertMany(ctx context.Context, inputs []*CreateProductInput, target ProductConflictTarget, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error)

	// Increment atomically increments or decrements a numeric column on a product.
	// Returns ErrNotFound if the primary key does not exist.
	Increment(ctx context.Context, id int64, input IncrementInput[ProductIncrementColumn], opts ...func(*CallOptions[ProductFieldOptions])) error

	// --- Hard Delete Operations ---

	// HardDelete permanently removes a product from the database.
	// Idempotent — returns nil if the primary key does not exist.
	HardDelete(ctx context.Context, id int64, opts ...func(*CallOptions[ProductFieldOptions])) error

	// HardDeleteMany permanently removes multiple products from the database.
	HardDeleteMany(ctx context.Context, ids []int64, opts ...func(*CallOptions[ProductFieldOptions])) error

	// HardDeleteWhere permanently removes all products matching the filter.
	// Idempotent — returns nil when no rows match.
	HardDeleteWhere(ctx context.Context, filter *ProductFilter, opts ...func(*CallOptions[ProductFieldOptions])) error

	// --- Pagination Operations ---

	// Paginate returns a page of products with total count for offset-based pagination.
	Paginate(ctx context.Context, input PaginateInput[ProductFilter], opts ...func(*CallOptions[ProductFieldOptions])) (*PaginateResult[Product], error)

	// Connection returns a Relay-style cursor-paginated connection of products.
	// Sort order is determined by cursor_keys — custom sorts are not supported.
	// Use Paginate for custom sort orders.
	Connection(ctx context.Context, input ConnectionInput[ProductFilter], opts ...func(*CallOptions[ProductFieldOptions])) (*Connection[Product], error)

	// Stream returns an iterator over products matching the filter and sort criteria.
	// Rows are yielded as the driver returns them; cache is bypassed.
	// Stream cannot load relationships.
	//
	// Stream refuses an active transaction unless CallOptions.AllowInTransaction
	// is set, and the opt-in commits the caller to issuing nothing else on that
	// txCtx: the one rule that remains the caller's — drain or close a result set
	// before issuing the next statement on that txCtx — applied to a loop whose
	// body is caller code.
	Stream(ctx context.Context, input *StreamProductsInput, opts ...func(*CallOptions[StreamProductFieldOptions])) iter.Seq2[*Product, error]
}

// productClient implements the ProductClient interface.
type productClient struct {
	querier                     database.Querier
	dialect                     sql.Dialect
	table                       sql.Table
	batchSize                   int
	queryLimit                  int
	pageSize                    int
	cursorKeys                  []string
	strictUpdates               bool
	mutationHooks               []hook.MutationHook
	queryHooks                  []hook.QueryHook
	panicHandler                hook.PanicHandler
	callbackMode                database.CallbackMode
	orderItemsDefaultSort       []sql.Sort
	productTagLabelsDefaultSort []sql.Sort
	orderItemClient             *orderItemClient
	productTagLabelClient       *productTagLabelClient
}

// newProductClient creates a new productClient.
func newProductClient(querier database.Querier, mutationHooks []hook.MutationHook, queryHooks []hook.QueryHook, panicHandler hook.PanicHandler) *productClient {
	return &productClient{
		querier:       querier,
		dialect:       sql.NewSQLiteDialect(),
		table:         sql.Table{Schema: "", Name: "products"},
		batchSize:     200,
		queryLimit:    1000,
		pageSize:      100,
		cursorKeys:    []string{"id"},
		strictUpdates: true,
		mutationHooks: mutationHooks,
		queryHooks:    queryHooks,
		panicHandler:  panicHandler,
	}
}

// executeMutation runs fn through the mutation hook chain.
// When skipHooks is true, only panic recovery wraps the call.
func (c *productClient) executeMutation(ctx context.Context, skipHooks bool, mc *hook.MutationContext, fn hook.MutationHandler) (any, error) {
	var hooks []hook.MutationHook
	if !skipHooks {
		hooks = c.mutationHooks
	}
	return hook.BuildMutationChain(c.panicHandler, hooks, fn)(ctx, mc)
}

// executeQuery runs fn through the query hook chain.
// When skipHooks is true, only panic recovery wraps the call.
func (c *productClient) executeQuery(ctx context.Context, skipHooks bool, qc *hook.QueryContext, fn hook.QueryHandler) (any, error) {
	var hooks []hook.QueryHook
	if !skipHooks {
		hooks = c.queryHooks
	}
	return hook.BuildQueryChain(c.panicHandler, hooks, fn)(ctx, qc)
}

// productAllColumns is the column list for full-entity reads, sorted for determinism.
var productAllColumns = []string{"category_id", "created_at", "id", "in_stock", "price", "sku", "title", "weight_kg"}

// scanProducts scans rows into Product entities using a column-name switch.
// Handles both scan target shapes (direct, wrapped) without reflection.
func scanProducts(rows database.Rows, columns []string) ([]*Product, error) {
	var result []*Product
	for rows.Next() {
		p := &Product{}

		targets := make([]any, len(columns))
		for idx, col := range columns {
			switch col {
			case "id":
				targets[idx] = &p.ID
			case "category_id":
				targets[idx] = &p.CategoryID
			case "title":
				targets[idx] = &p.Title
			case "price":
				targets[idx] = &p.Price
			case "weight_kg":
				targets[idx] = &p.WeightKg
			case "in_stock":
				targets[idx] = &p.InStock
			case "sku":
				targets[idx] = &p.SKU
			case "created_at":
				targets[idx] = &p.CreatedAt
			}
		}

		if err := rows.Scan(targets...); err != nil {
			return nil, fmt.Errorf("scan product: %w", err)
		}

		result = append(result, p)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate product rows: %w", err)
	}
	return result, nil
}

// Get returns a single product by primary key with optional field selection.
// If fieldOptions is provided, only the selected columns are returned and
// relationships with non-nil FieldOptions are loaded.
func (c *productClient) Get(ctx context.Context, id int64, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error) {
	options := resolveCallOptions(opts)

	if options.LockMode != sql.LockNone {
		return nil, fmt.Errorf("get product: LockMode is unsupported on sqlite dialect")
	}
	qctx := &hook.QueryContext{
		Op: hook.OpGet, Table: TableProducts, Schema: "",
		PK: id, CallOptions: options,
	}
	result, err := c.executeQuery(ctx, options.SkipHooks, qctx, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		// Hooks may mutate q.CallOptions (e.g. the cache hook's hydration
		// path overrides FieldOptions for a full-entity refill). Prefer
		// those overrides when present; otherwise fall back to the
		// caller-supplied options captured at Get() time.
		effectiveOpts := options
		if qOpts, ok := q.CallOptions.(CallOptions[ProductFieldOptions]); ok {
			effectiveOpts = qOpts
		}
		// Internal GetMany call with SkipHooks to prevent nested hook invocation
		internalOpts := func(o *CallOptions[ProductFieldOptions]) {
			*o = effectiveOpts
			o.SkipHooks = true
		}
		products, err := c.GetMany(ctx, &GetProductsInput{
			Filter: &ProductFilter{
				ID: &comparator.Number[int64]{Eq: new(id)},
			},
			Limit: new(1),
		}, internalOpts)
		if err != nil {
			return nil, err
		}
		if len(products) == 0 {
			return nil, ErrNotFound
		}
		return products[0], nil
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*Product), nil
}

// GetMany returns products matching the given filter, field selection, and sort criteria.
// When FieldOptions includes O2M or M2M relationships, they are loaded via an
// errgroup fan-out — in parallel over the pool, and serialized by the
// transaction's connection reservation when ctx carries one.
func (c *productClient) GetMany(ctx context.Context, input *GetProductsInput, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error) {
	// A nil input is the zero-value input — no filter, no sorts, no
	// limit. Normalized before the hook context is built, so a hook never sees
	// a nil Input either.
	if input == nil {
		input = &GetProductsInput{}
	}
	options := resolveCallOptions(opts)

	if options.LockMode != sql.LockNone {
		return nil, fmt.Errorf("get products: LockMode is unsupported on sqlite dialect")
	}
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpGetMany, Table: TableProducts, Schema: "",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		// FieldOptions from CallOptions — nil means all columns
		fieldOptions := options.FieldOptions

		// Nothing selected — return early
		if fieldOptions != nil && !fieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		// Determine columns from FieldOptions. A narrowed projection still
		// carries the columns this call structurally requires — the cursor keys
		// an internal caller declares, and the key relationship
		// mapping reads off each row. An all-false FieldOptions is
		// untouched: it short-circuits above.
		columns := productAllColumns
		if fieldOptions != nil {
			if selected := fieldOptions.Columns(); len(selected) > 0 {
				columns = unionColumns(selected, input.requiredColumns...)
				if fieldOptions.loadsRelationships() {
					columns = unionColumns(columns, "id")
				}
			}
		}

		// Build conditions from filter
		var conds []sql.Condition
		if input.Filter != nil {
			conds = input.Filter.ToConditions(c.dialect)
		}

		// Append internal conditions (e.g., keyset conditions from Connection)
		conds = append(conds, input.conditions...)

		// Resolve limit/offset to pointers for the builder.
		// nil → no clause, *0 (via new(0)) → no clause, *N → LIMIT/OFFSET N.
		var limitPtr *int
		if input.Limit != nil {
			if v := *input.Limit; v > 0 {
				limitPtr = new(v)
			}
		} else if c.queryLimit > 0 {
			limitPtr = new(c.queryLimit)
		}
		var offsetPtr *int
		if input.Offset != nil {
			if v := *input.Offset; v > 0 {
				offsetPtr = new(v)
			}
		}

		var products []*Product
		query, args := sql.BuildSelect(c.dialect, c.table, sql.SelectOptions{
			Columns:    columns,
			Conditions: conds,
			OrderBy:    input.Sorts,
			Limit:      limitPtr,
			Offset:     offsetPtr,
			LockMode:   options.LockMode,
		})

		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("get products: %w", err)
		}
		defer rows.Close()

		products, err = scanProducts(rows, columns)
		if err != nil {
			return nil, err
		}

		// Load O2M/M2M relationships via errgroup — in parallel over the pool,
		// serialized by the transaction's connection reservation inside one
		if fieldOptions != nil {
			if err := c.loadRelationships(ctx, conn, products, options.FieldOptions); err != nil {
				return nil, err
			}
		}

		return products, nil
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*Product), nil
}

// loadsRelationships reports whether any O2M or M2M relationship is selected.
// GetMany unions the id column into a narrowed projection when one is:
// loadRelationships maps every child back through p.ID, which
// an unselected column would leave at its zero value.
func (fo *ProductFieldOptions) loadsRelationships() bool {
	if fo.OrderItems != nil {
		return true
	}
	if fo.ProductTagLabels != nil {
		return true
	}
	return false
}

// loadRelationships fetches every selected O2M / M2M member through the
// target's own client, so each child read carries that table's own filters,
// soft-delete default and access rules rather than this one's.
//
// The fan-out is unbounded, inside a transaction and out. Outside one each
// edge draws its own pooled connection and the parallelism is real. Inside one
// they share the transaction's single connection — database.Conn hands every
// nested read the same *database.Tx — and the Tx's connection reservation
// serializes them, so the statement count is identical either way and only the
// concurrency differs. The loader needs no transaction-aware bound of its own.
func (c *productClient) loadRelationships(ctx context.Context, conn database.Querier, products []*Product, fo *ProductFieldOptions) error {
	g, ctx := errgroup.WithContext(ctx)

	if fo.OrderItems != nil {
		g.Go(func() error {
			// Collect parent FK values
			productIDs := make([]int64, len(products))
			for idx, p := range products {
				productIDs[idx] = p.ID
			}

			// Build FK-based filter, merged with consumer filter
			filter := &OrderItemFilter{
				ProductID: &comparator.Number[int64]{In: productIDs},
			}
			if fo.OrderItems.Filter != nil {
				filter.And = append(filter.And, fo.OrderItems.Filter)
			}

			// Load via related entity client
			sorts := fo.OrderItems.Sorts
			if len(sorts) == 0 {
				sorts = c.orderItemsDefaultSort
			}

			// Self-referential relationships share the parent's entity type, so
			// the loaded children must use a name distinct from the parent slice
			// (products) to avoid shadowing it and mis-mapping the results
			// onto the children instead of the parents.
			relatedOrderItems, err := c.orderItemClient.GetMany(ctx, &GetOrderItemsInput{
				Filter: filter,
				Sorts:  sorts,
				Limit:  new(0),
				// The mapping below keys every child on its FK, so the fetch
				// declares that column rather than mutating the caller's
				// FieldOptions — a narrowed selection that omits it would
				// otherwise map every child onto the zero value.
				requiredColumns: []string{"product_id"},
			}, func(co *CallOptions[OrderItemFieldOptions]) {
				co.FieldOptions = fo.OrderItems.FieldOptions
			})
			if err != nil {
				return fmt.Errorf("load product order_items: %w", err)
			}

			// Map results back to parent entities by FK. The FK column on the
			// child table may be nullable and resolved to a Null-wrapper struct
			// (e.g., uuid.NullUUID) — fkLoadGuard skips invalid rows and
			// fkLoadKey unwraps the underlying scalar before stringifying.
			byFK := make(map[string][]*OrderItem)
			for _, r := range relatedOrderItems {
				key := fmt.Sprint(r.ProductID)
				byFK[key] = append(byFK[key], r)
			}
			for i := range products {
				products[i].OrderItems = byFK[fmt.Sprint(products[i].ID)]
			}
			return nil
		})
	}

	if fo.ProductTagLabels != nil {
		g.Go(func() error {
			// Collect parent FK values
			productIDs := make([]int64, len(products))
			for idx, p := range products {
				productIDs[idx] = p.ID
			}

			// Build FK-based filter, merged with consumer filter
			filter := &ProductTagLabelFilter{
				ProductID: &comparator.Number[int64]{In: productIDs},
			}
			if fo.ProductTagLabels.Filter != nil {
				filter.And = append(filter.And, fo.ProductTagLabels.Filter)
			}

			// Load via related entity client
			sorts := fo.ProductTagLabels.Sorts
			if len(sorts) == 0 {
				sorts = c.productTagLabelsDefaultSort
			}

			// Self-referential relationships share the parent's entity type, so
			// the loaded children must use a name distinct from the parent slice
			// (products) to avoid shadowing it and mis-mapping the results
			// onto the children instead of the parents.
			relatedProductTagLabels, err := c.productTagLabelClient.GetMany(ctx, &GetProductTagLabelsInput{
				Filter: filter,
				Sorts:  sorts,
				Limit:  new(0),
				// The mapping below keys every child on its FK, so the fetch
				// declares that column rather than mutating the caller's
				// FieldOptions — a narrowed selection that omits it would
				// otherwise map every child onto the zero value.
				requiredColumns: []string{"product_id"},
			}, func(co *CallOptions[ProductTagLabelFieldOptions]) {
				co.FieldOptions = fo.ProductTagLabels.FieldOptions
			})
			if err != nil {
				return fmt.Errorf("load product product_tag_labels: %w", err)
			}

			// Map results back to parent entities by FK. The FK column on the
			// child table may be nullable and resolved to a Null-wrapper struct
			// (e.g., uuid.NullUUID) — fkLoadGuard skips invalid rows and
			// fkLoadKey unwraps the underlying scalar before stringifying.
			byFK := make(map[string][]*ProductTagLabel)
			for _, r := range relatedProductTagLabels {
				key := fmt.Sprint(r.ProductID)
				byFK[key] = append(byFK[key], r)
			}
			for i := range products {
				products[i].ProductTagLabels = byFK[fmt.Sprint(products[i].ID)]
			}
			return nil
		})
	}

	return g.Wait()
}

// Create inserts a new product and returns the created entity.
func (c *productClient) Create(ctx context.Context, input *CreateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error) {
	// A write cannot normalize nil to the zero value the way a read
	// does — a zero CreateProductInput legally writes a row (each required
	// field's zero value, or with no required field, every column's default), so
	// that would turn a caller's mistake into a silently written one. Guarded
	// before the executor, so nil fires no hook and publishes no event.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpCreate, Table: TableProducts, Schema: "",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		columns := []string{"category_id", "title", "price", "sku"}
		args := []any{input.CategoryID, input.Title, input.Price, input.SKU}

		if v, ok := input.WeightKg.Get(); ok {
			columns = append(columns, "weight_kg")
			args = append(args, v)
		}

		if v, ok := input.InStock.Get(); ok {
			columns = append(columns, "in_stock")
			args = append(args, v)
		}

		if v, ok := input.CreatedAt.Get(); ok {
			columns = append(columns, "created_at")
			args = append(args, v)
		}

		id, err := c.insertAndResolveID(ctx, conn, columns, args)
		if err != nil {
			return nil, fmt.Errorf("create product: %w", err)
		}
		m.AffectedPKs = []any{id}

		// Empty FieldOptions — caller doesn't need the result
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.Get(ctx, id, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*Product), nil
}

// CreateMany inserts multiple products in batches and returns all created entities.
// Sub-batches are not automatically rolled back on failure — wrap in a transaction for atomicity.
func (c *productClient) CreateMany(ctx context.Context, inputs []*CreateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error) {
	// A nil *slice* is simply no rows, but a nil *element* is the
	// same caller error a nil Create argument is — and skipping it silently
	// would drop a row the caller asked for. Rejected before the executor.
	for _, in := range inputs {
		if in == nil {
			return nil, ErrNilInput
		}
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpCreateMany, Table: TableProducts, Schema: "",
		Input: inputs, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		// An empty batch writes nothing and must read nothing. The trailing
		// re-fetch below filters on the keys this call touched, and every
		// generated key filter treats an empty set as *no condition* — so
		// without this guard the re-fetch degrades to an unfiltered SELECT and
		// returns the whole table as if this call had produced it.
		if len(inputs) == 0 {
			return []*Product{}, nil
		}
		var allIDs []int64
		for start := 0; start < len(inputs); start += c.batchSize {
			end := min(start+c.batchSize, len(inputs))
			batch := inputs[start:end]

			columns := []string{"category_id", "title", "price", "weight_kg", "in_stock", "sku", "created_at"}
			var valueRows [][]any
			for _, input := range batch {
				var weightKg any = sql.NewDefaultExpr("NULL")
				if v, ok := input.WeightKg.Get(); ok {
					weightKg = v
				}
				var inStock any = sql.NewDefaultExpr("1")
				if v, ok := input.InStock.Get(); ok {
					inStock = v
				}
				var createdAt any = sql.NewDefaultExpr("datetime('now')")
				if v, ok := input.CreatedAt.Get(); ok {
					createdAt = v
				}

				valueRows = append(valueRows, []any{
					input.CategoryID,
					input.Title,
					input.Price,
					weightKg,
					inStock,
					input.SKU,
					createdAt,
				})
			}

			ids, err := c.multiInsertAndResolveIDs(ctx, conn, columns, valueRows)
			if err != nil {
				return nil, fmt.Errorf("create products batch: %w", err)
			}
			allIDs = append(allIDs, ids...)
		}

		m.AffectedPKs = toAnySlice(allIDs)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}
		return c.GetMany(ctx, &GetProductsInput{
			Filter: &ProductFilter{
				ID: &comparator.Number[int64]{In: allIDs},
			},
			Limit: new(0),
		}, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*Product), nil
}

// insertAndResolveID performs the INSERT and resolves the generated primary key.
func (c *productClient) insertAndResolveID(ctx context.Context, conn database.Querier, columns []string, args []any) (int64, error) {
	query, queryArgs := sql.BuildInsert(c.dialect, c.table, sql.InsertOptions{
		Columns:          columns,
		Values:           args,
		ReturningColumns: []string{"id"},
	})
	var id int64
	if err := conn.QueryRow(ctx, query, queryArgs...).Scan(&id); err != nil {
		return 0, err
	}
	return id, nil
}

// multiInsertAndResolveIDs performs a multi-row INSERT and resolves all generated primary keys.
func (c *productClient) multiInsertAndResolveIDs(ctx context.Context, conn database.Querier, columns []string, valueRows [][]any) ([]int64, error) {
	query, args := sql.BuildMultiInsert(c.dialect, c.table, sql.MultiInsertOptions{
		Columns:          columns,
		ValueRows:        valueRows,
		ReturningColumns: []string{"id"},
	})

	rows, err := conn.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, fmt.Errorf("scan product id: %w", err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return ids, nil
}

// Update partially updates a product by primary key and returns the updated entity.
// Only fields where IsSet() is true are included in the SET clause. If no fields are
// set, no UPDATE is executed and the current entity is returned unchanged.
// Returns ErrNotFound if the primary key does not exist (strict_updates is enabled).
func (c *productClient) Update(ctx context.Context, id int64, input *UpdateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error) {
	// Nil is a caller error, distinct from an empty-but-non-nil
	// input — that one is the documented no-op returning the entity unchanged.
	// Guarded before the executor, so nil fires no hook and publishes no event.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpdate, Table: TableProducts, Schema: "",
		PK: id, Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		// Build SET clause from omittable fields — explicit per-field checks, no reflection
		setClauses := make(map[string]any)
		if v, ok := input.CategoryID.Get(); ok {
			setClauses["category_id"] = v
		}
		if v, ok := input.Title.Get(); ok {
			setClauses["title"] = v
		}
		if v, ok := input.Price.Get(); ok {
			setClauses["price"] = v
		}
		if v, ok := input.WeightKg.Get(); ok {
			setClauses["weight_kg"] = v
		}
		if v, ok := input.InStock.Get(); ok {
			setClauses["in_stock"] = v
		}
		if v, ok := input.SKU.Get(); ok {
			setClauses["sku"] = v
		}
		if v, ok := input.CreatedAt.Get(); ok {
			setClauses["created_at"] = v
		}

		// Empty update — no fields set, return current entity unchanged
		if len(setClauses) == 0 {
			// Empty FieldOptions — caller doesn't need the result
			if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
				return nil, nil
			}

			return c.Get(ctx, id, func(o *CallOptions[ProductFieldOptions]) {
				*o = options
				o.SkipHooks = true
				o.LockMode = sql.LockNone
			})
		}

		query, args := sql.BuildUpdate(c.dialect, c.table, sql.UpdateOptions{
			SetClauses: setClauses,
			Conditions: []sql.Condition{sql.Where(c.dialect.QuoteIdentifier("id")).Eq(id)},
		})

		execResult, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("update product: %w", err)
		}
		count, err := execResult.RowsAffected()
		if err != nil {
			return nil, fmt.Errorf("update product rows affected: %w", err)
		}
		if count == 0 {
			return nil, ErrNotFound
		}
		m.AffectedPKs = []any{id}

		// Empty FieldOptions — caller doesn't need the result
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.Get(ctx, id, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*Product), nil
}

// UpdateProductItem pairs a primary key with an update input for batch updates.
type UpdateProductItem struct {
	ID    int64               `json:"id"`
	Input *UpdateProductInput `json:"input"`
}

// UpdateMany partially updates multiple products and returns the updated entities.
// Each item is a (PK, UpdateInput) pair. Splits into batches of batchSize.
// On stdlib, each UPDATE executes sequentially.
func (c *productClient) UpdateMany(ctx context.Context, items []UpdateProductItem, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error) {
	// UpdateProductItem.Input is a pointer, so a zero-valued item
	// carries a nil one — a shape that compiles naturally. Rejected before the
	// executor, like every other nil write input.
	for _, item := range items {
		if item.Input == nil {
			return nil, ErrNilInput
		}
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpdateMany, Table: TableProducts, Schema: "",
		Input: items, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		// An empty batch writes nothing and must read nothing. The trailing
		// re-fetch below filters on the keys this call touched, and every
		// generated key filter treats an empty set as *no condition* — so
		// without this guard the re-fetch degrades to an unfiltered SELECT and
		// returns the whole table as if this call had produced it.
		if len(items) == 0 {
			return []*Product{}, nil
		}
		var allIDs []int64
		for start := 0; start < len(items); start += c.batchSize {
			end := min(start+c.batchSize, len(items))
			batch := items[start:end]

			for _, item := range batch {
				setClauses := make(map[string]any)
				if v, ok := item.Input.CategoryID.Get(); ok {
					setClauses["category_id"] = v
				}
				if v, ok := item.Input.Title.Get(); ok {
					setClauses["title"] = v
				}
				if v, ok := item.Input.Price.Get(); ok {
					setClauses["price"] = v
				}
				if v, ok := item.Input.WeightKg.Get(); ok {
					setClauses["weight_kg"] = v
				}
				if v, ok := item.Input.InStock.Get(); ok {
					setClauses["in_stock"] = v
				}
				if v, ok := item.Input.SKU.Get(); ok {
					setClauses["sku"] = v
				}
				if v, ok := item.Input.CreatedAt.Get(); ok {
					setClauses["created_at"] = v
				}

				// Skip no-op updates
				if len(setClauses) == 0 {
					allIDs = append(allIDs, item.ID)
					continue
				}

				query, args := sql.BuildUpdate(c.dialect, c.table, sql.UpdateOptions{
					SetClauses: setClauses,
					Conditions: []sql.Condition{sql.Where(c.dialect.QuoteIdentifier("id")).Eq(item.ID)},
				})

				_, err := conn.Exec(ctx, query, args...)
				if err != nil {
					return nil, fmt.Errorf("update product %v: %w", item.ID, err)
				}
				allIDs = append(allIDs, item.ID)
			}
		}

		m.AffectedPKs = toAnySlice(allIDs)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}
		return c.GetMany(ctx, &GetProductsInput{
			Filter: &ProductFilter{
				ID: &comparator.Number[int64]{In: allIDs},
			},
			Limit: new(0),
		}, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*Product), nil
}

// UpdateWhere updates all products matching the filter and returns the updated entities.
// Idempotent — returns empty slice when no rows match.
// Returns ErrNilInput when input is nil, checked before the filter.
// Returns ErrEmptyFilter when the filter is nil or produces no conditions.
func (c *productClient) UpdateWhere(ctx context.Context, filter *ProductFilter, input *UpdateProductInput, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error) {
	// Argument validity is checked before the filter's bulk-op
	// safety guard, and before the executor, so a nil input fires no hook and
	// publishes no event. ErrEmptyFilter still covers a non-nil input with an
	// empty filter.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpdateWhere, Table: TableProducts, Schema: "",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		conds := filter.ToConditions(c.dialect)
		if len(conds) == 0 {
			return nil, ErrEmptyFilter
		}

		// Build SET clause (same per-field checks as Update)
		setClauses := make(map[string]any)
		if v, ok := input.CategoryID.Get(); ok {
			setClauses["category_id"] = v
		}
		if v, ok := input.Title.Get(); ok {
			setClauses["title"] = v
		}
		if v, ok := input.Price.Get(); ok {
			setClauses["price"] = v
		}
		if v, ok := input.WeightKg.Get(); ok {
			setClauses["weight_kg"] = v
		}
		if v, ok := input.InStock.Get(); ok {
			setClauses["in_stock"] = v
		}
		if v, ok := input.SKU.Get(); ok {
			setClauses["sku"] = v
		}
		if v, ok := input.CreatedAt.Get(); ok {
			setClauses["created_at"] = v
		}

		// No fields set — return matching entities unchanged
		if len(setClauses) == 0 {
			if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
				return nil, nil
			}
			return c.GetMany(ctx, &GetProductsInput{
				Filter: filter,
				Limit:  new(0),
			}, func(o *CallOptions[ProductFieldOptions]) {
				*o = options
				o.SkipHooks = true
				o.LockMode = sql.LockNone
			})
		}

		// UPDATE with RETURNING "id" — get affected IDs in one round-trip
		query, args := sql.BuildUpdate(c.dialect, c.table, sql.UpdateOptions{
			SetClauses:       setClauses,
			Conditions:       conds,
			ReturningColumns: []string{"id"},
		})

		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("update products where: %w", err)
		}
		defer rows.Close()
		var ids []int64
		for rows.Next() {
			var id int64
			if err := rows.Scan(&id); err != nil {
				return nil, fmt.Errorf("scan updated product id: %w", err)
			}
			ids = append(ids, id)
		}
		if err := rows.Err(); err != nil {
			return nil, err
		}
		if len(ids) == 0 {
			return nil, nil
		}
		m.AffectedPKs = toAnySlice(ids)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		// Fetch affected entities with FieldOptions
		return c.GetMany(ctx, &GetProductsInput{
			Filter: &ProductFilter{
				ID: &comparator.Number[int64]{In: ids},
			},
			Limit: new(0),
		}, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*Product), nil
}

// HardDelete permanently removes a product from the database.
// Idempotent — returns nil if the primary key does not exist.
func (c *productClient) HardDelete(ctx context.Context, id int64, opts ...func(*CallOptions[ProductFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpHardDelete, Table: TableProducts, Schema: "",
		PK: id, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		query, args := sql.BuildHardDelete(c.dialect, c.table, sql.HardDeleteOptions{
			Conditions: []sql.Condition{sql.Where(c.dialect.QuoteIdentifier("id")).Eq(id)},
		})

		_, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("hard delete product: %w", err)
		}
		m.AffectedPKs = []any{id}
		return nil, nil
	})
	return err
}

// HardDeleteMany permanently removes multiple products from the database.
func (c *productClient) HardDeleteMany(ctx context.Context, ids []int64, opts ...func(*CallOptions[ProductFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpHardDeleteMany, Table: TableProducts, Schema: "",
		Input: ids, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		query, args := sql.BuildHardDelete(c.dialect, c.table, sql.HardDeleteOptions{
			Conditions: []sql.Condition{
				sql.Where(c.dialect.QuoteIdentifier("id")).In(toAnySlice(ids)...),
			},
		})

		_, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("hard delete products: %w", err)
		}
		m.AffectedPKs = toAnySlice(ids)
		return nil, nil
	})
	return err
}

// HardDeleteWhere permanently removes all products matching the filter.
// Idempotent — returns nil when no rows match.
// Returns ErrEmptyFilter when the filter is nil or produces no conditions.
func (c *productClient) HardDeleteWhere(ctx context.Context, filter *ProductFilter, opts ...func(*CallOptions[ProductFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpHardDeleteWhere, Table: TableProducts, Schema: "",
		Input: filter, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		conds := filter.ToConditions(c.dialect)
		if len(conds) == 0 {
			return nil, ErrEmptyFilter
		}

		// DELETE with RETURNING "id" — get affected IDs in one round-trip
		query, args := sql.BuildHardDelete(c.dialect, c.table, sql.HardDeleteOptions{
			Conditions:       conds,
			ReturningColumns: []string{"id"},
		})

		rows, err := conn.Query(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("hard delete products where: %w", err)
		}
		defer rows.Close()
		var ids []int64
		for rows.Next() {
			var id int64
			if err := rows.Scan(&id); err != nil {
				return nil, fmt.Errorf("scan deleted product id: %w", err)
			}
			ids = append(ids, id)
		}
		if err := rows.Err(); err != nil {
			return nil, err
		}
		m.AffectedPKs = toAnySlice(ids)
		return nil, nil
	})
	return err
}

// ProductConflictTarget identifies a unique constraint for upsert conflict detection.
type ProductConflictTarget int

const (
	ProductConflictPK  ProductConflictTarget = iota // PRIMARY KEY (id)
	ProductConflictSKU                              // UNIQUE (sku)
)

// productConflictColumns maps each conflict target to its column set.
var productConflictColumns = map[ProductConflictTarget][]string{
	ProductConflictPK:  {"id"},
	ProductConflictSKU: {"sku"},
}

// Upsert inserts a product or updates it if a row matching the conflict target already
// exists. Returns the resulting entity with optional field selection and relationship loading.
// The conflict target determines which unique constraint triggers an update
// instead of an insert. Non-PK, non-conflict columns are included in the SET clause.
func (c *productClient) Upsert(ctx context.Context, input *CreateProductInput, target ProductConflictTarget, opts ...func(*CallOptions[ProductFieldOptions])) (*Product, error) {
	// A write cannot normalize nil to the zero value the way a read
	// does — a zero CreateProductInput legally writes a row (each required
	// field's zero value, or with no required field, every column's default).
	// Guarded before the executor, so nil fires no hook and publishes no event.
	// An input that supplies no column gets no conflict clause on any dialect:
	// it is a plain insert, so a conflict on a UNIQUE column with a
	// DEFAULT is a unique violation, including on MySQL, where ON DUPLICATE KEY
	// UPDATE would have returned the existing row.
	if input == nil {
		return nil, ErrNilInput
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpsert, Table: TableProducts, Schema: "",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		columns := []string{"category_id", "title", "price", "sku"}
		args := []any{input.CategoryID, input.Title, input.Price, input.SKU}

		if v, ok := input.WeightKg.Get(); ok {
			columns = append(columns, "weight_kg")
			args = append(args, v)
		}

		if v, ok := input.InStock.Get(); ok {
			columns = append(columns, "in_stock")
			args = append(args, v)
		}

		if v, ok := input.CreatedAt.Get(); ok {
			columns = append(columns, "created_at")
			args = append(args, v)
		}

		// Resolve conflict target and update columns. Tenant column is excluded
		// from the UPDATE-set half of the conflict clause — a
		// row's tenant is not a mutable attribute under normal operation.
		conflictColumns := productConflictColumns[target]
		updateColumns := excludeColumns(columns, append(conflictColumns, "id"))

		id, err := c.insertUpsertAndResolveID(ctx, conn, columns, args, conflictColumns, updateColumns)
		if err != nil {
			return nil, fmt.Errorf("upsert product: %w", err)
		}
		m.AffectedPKs = []any{id}

		// Empty FieldOptions — caller doesn't need the result
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.Get(ctx, id, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.(*Product), nil
}

// insertUpsertAndResolveID performs the INSERT with upsert clause and resolves the generated primary key.
func (c *productClient) insertUpsertAndResolveID(ctx context.Context, conn database.Querier, columns []string, args []any, conflictColumns, updateColumns []string) (int64, error) {
	query, queryArgs := sql.BuildInsert(c.dialect, c.table, sql.InsertOptions{
		Columns:               columns,
		Values:                args,
		UpsertConflictKeys:    conflictColumns,
		UpsertUpdateColumns:   updateColumns,
		UpsertResolvePKColumn: "id",
		ReturningColumns:      []string{"id"},
	})
	rows, err := conn.Query(ctx, query, queryArgs...)
	if err != nil {
		return 0, err
	}
	var id int64
	found := rows.Next()
	if found {
		err = rows.Scan(&id)
	}
	if err == nil {
		err = rows.Err()
	}
	// Closed before the fallback below issues its own statement: conn may be a
	// transaction, where an open result set blocks the next statement on the
	// same connection.
	if cerr := rows.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return 0, err
	}
	if found {
		return id, nil
	}
	return c.resolveUpsertConflictRow(ctx, conn, columns, args, conflictColumns)
}

// resolveUpsertConflictRow resolves the row an upsert conflicted with, for the
// case where the statement returned nothing.
//
// A conflict target that covers every inserted column leaves no column to
// assign, so the dialect emits DO NOTHING — and DO NOTHING returns
// no row, which leaves the RETURNING branch above with no PK for a write that
// did resolve to a row. The conflicting row is looked up by the same conflict
// columns the statement targeted; unlike MySQL's ON DUPLICATE KEY UPDATE, an
// explicit ON CONFLICT target can only have fired on those columns, so the
// lookup identifies the same row the statement did.
//
// The lookup does not exclude soft-deleted rows: the unique index matched
// regardless of the soft-delete column, so a soft-deleted row is still the row
// that conflicted and still the row whose PK this resolves. (The terminal Get
// then applies the read path's own soft-delete filter, exactly as it does on
// the DO UPDATE SET branch.)
//
// This is a second statement, so a concurrent delete between the insert and
// this lookup surfaces as ErrNotFound. Run the upsert inside a transaction
// where the pair has to be atomic.
func (c *productClient) resolveUpsertConflictRow(ctx context.Context, conn database.Querier, columns []string, args []any, conflictColumns []string) (int64, error) {
	conds := make([]sql.Condition, 0, len(conflictColumns))
	for _, col := range conflictColumns {
		i := slices.Index(columns, col)
		if i < 0 {
			// A conflict column the statement never supplied cannot have
			// produced the conflict, so there is no row to look up.
			return 0, ErrNotFound
		}
		conds = append(conds, sql.Where(c.dialect.QuoteIdentifier(col)).Eq(args[i]))
	}

	query, queryArgs := sql.BuildSelect(c.dialect, c.table, sql.SelectOptions{
		Columns:    []string{"id"},
		Conditions: conds,
		Limit:      new(1),
	})
	rows, err := conn.Query(ctx, query, queryArgs...)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	var id int64
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return 0, err
		}
		// The conflicting row is gone — deleted between the two statements.
		return 0, ErrNotFound
	}
	if err := rows.Scan(&id); err != nil {
		return 0, err
	}
	return id, rows.Err()
}

// UpsertMany inserts or updates multiple products in batches and returns all
// resulting entities. One conflict target applies to the whole batch, drawn from
// the same enum Upsert takes. Sub-batches are not automatically rolled back on
// failure — wrap in a transaction for atomicity.
//
// Inputs resolving to the same conflict target are deduped before the statement
// is built, last occurrence wins. PostgreSQL rejects an
// ON CONFLICT ... DO UPDATE that would affect one row twice; MySQL and SQLite
// accept it and keep the last row. The dedupe is what makes one spelling behave
// identically on all three. A row carrying no definite, non-NULL value for every
// conflict column is exempt: a NULL never matches under a unique index on any of
// the three dialects, so two such rows are two rows, not a duplicate.
//
// The returned slice carries one entity per deduped input on every dialect,
// including the DO NOTHING branch a conflict target covering every inserted
// column produces. The entities come from a re-fetch by primary key, never from
// RETURNING — RETURNING yields only the rows actually inserted, so a batch that
// conflicted would come back short. Row order is GetMany's, as with
// CreateMany.
//
// products.id is database-generated, so the rows written by each
// sub-batch are read back by the conflict target they targeted — two statements
// per sub-batch rather than one. No dialect can report them from the
// statement itself: MySQL's LAST_INSERT_ID() after a mixed batch names the first
// *newly inserted* row, not the batch's first row, so fabricating ids from it is
// unsound, and RETURNING drops every row that took the DO NOTHING branch. The
// conflict target must therefore name columns the input carries; one that does
// not is an error before anything is written.
func (c *productClient) UpsertMany(ctx context.Context, inputs []*CreateProductInput, target ProductConflictTarget, opts ...func(*CallOptions[ProductFieldOptions])) ([]*Product, error) {
	// A nil *slice* is simply no rows, but a nil *element* is the
	// same caller error a nil Upsert argument is — and skipping it silently
	// would drop a row the caller asked for. Rejected before the executor.
	for _, in := range inputs {
		if in == nil {
			return nil, ErrNilInput
		}
	}
	options := resolveCallOptions(opts)
	result, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpUpsertMany, Table: TableProducts, Schema: "",
		Input: inputs, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		// No rows means no statement and nothing affected. Guarded here because
		// the terminal GetMany filters on the written keys, and a key filter
		// built from an empty set contributes no condition — an unguarded empty
		// call would read the whole table back.
		if len(inputs) == 0 {
			return []*Product{}, nil
		}
		conn := database.Conn(ctx, c.querier)

		// Resolve conflict target and update columns. Tenant column is excluded
		// from the UPDATE-set half of the conflict clause — a
		// row's tenant is not a mutable attribute under normal operation.
		//
		// UpsertResolvePKColumn is deliberately not set: it exists so a
		// single-row MySQL upsert can republish the conflicting row's id into
		// the OK packet, and after a batch that packet names at most one row.
		// Nothing here reads LastInsertId, so requesting it would
		// only add a misleading assignment to the SET list.
		columns := []string{"category_id", "title", "price", "weight_kg", "in_stock", "sku", "created_at"}
		conflictColumns := productConflictColumns[target]
		updateColumns := excludeColumns(columns, append(conflictColumns, "id"))
		conflictPositions, haveConflictKey := upsertConflictPositions(columns, conflictColumns)
		if !haveConflictKey {
			return nil, fmt.Errorf("upsert products: conflict target names a column the input does not supply, so the written rows cannot be identified")
		}

		// One value row per input, built before any statement runs: the dedupe
		// spans the whole call, not a sub-batch (ceil(M/batch_size)
		// statements for M inputs, *after* the dedupe).
		valueRows := make([][]any, 0, len(inputs))
		rowInputs := make([]*CreateProductInput, 0, len(inputs))
		var rowIDs []int64
		for _, input := range inputs {
			var weightKg any = sql.NewDefaultExpr("NULL")
			if v, ok := input.WeightKg.Get(); ok {
				weightKg = v
			}
			var inStock any = sql.NewDefaultExpr("1")
			if v, ok := input.InStock.Get(); ok {
				inStock = v
			}
			var createdAt any = sql.NewDefaultExpr("datetime('now')")
			if v, ok := input.CreatedAt.Get(); ok {
				createdAt = v
			}

			valueRows = append(valueRows, []any{
				input.CategoryID,
				input.Title,
				input.Price,
				weightKg,
				inStock,
				input.SKU,
				createdAt,
			})
			rowInputs = append(rowInputs, input)
		}

		// Dedupe by conflict target, last occurrence wins, first-appearance
		// order preserved.
		if haveConflictKey {
			seen := make(map[string]int, len(valueRows))
			dedupedRows := make([][]any, 0, len(valueRows))
			dedupedInputs := make([]*CreateProductInput, 0, len(rowInputs))
			for i, row := range valueRows {
				key, keyed := upsertDedupeKey(row, conflictPositions)
				if !keyed {
					// The row cannot be read back by the conflict target, so
					// its database-generated primary key would be unknowable.
					// Refused before anything is written rather than returned
					// short.
					return nil, fmt.Errorf("upsert products: input %d supplies no definite value for every conflict column, so its generated id cannot be resolved", i)
				}
				if keyed {
					if j, ok := seen[key]; ok {
						dedupedRows[j] = row
						dedupedInputs[j] = rowInputs[i]
						continue
					}
					seen[key] = len(dedupedRows)
				}
				dedupedRows = append(dedupedRows, row)
				dedupedInputs = append(dedupedInputs, rowInputs[i])
			}
			valueRows = dedupedRows
			rowInputs = dedupedInputs
		}
		// The published input is the deduped slice, so it stays index-aligned
		// with m.AffectedPKs: an event fanned out per affected row carries the
		// input that actually wrote that row.
		m.Input = rowInputs

		for start := 0; start < len(valueRows); start += c.batchSize {
			end := min(start+c.batchSize, len(valueRows))
			batch := valueRows[start:end]

			query, queryArgs := sql.BuildMultiInsert(c.dialect, c.table, sql.MultiInsertOptions{
				Columns:             columns,
				ValueRows:           batch,
				UpsertConflictKeys:  conflictColumns,
				UpsertUpdateColumns: updateColumns,
			})
			if _, err := conn.Exec(ctx, query, queryArgs...); err != nil {
				return nil, fmt.Errorf("upsert products batch: %w", err)
			}

			batchIDs, err := c.resolveUpsertManyRows(ctx, conn, conflictColumns, conflictPositions, batch)
			if err != nil {
				return nil, fmt.Errorf("upsert products batch: %w", err)
			}
			rowIDs = append(rowIDs, batchIDs...)
		}

		m.AffectedPKs = toAnySlice(rowIDs)

		// Empty FieldOptions — skip fetch
		if options.FieldOptions != nil && !options.FieldOptions.HasSelectedColumns() {
			return nil, nil
		}

		return c.GetMany(ctx, &GetProductsInput{
			Filter: &ProductFilter{
				ID: &comparator.Number[int64]{In: rowIDs},
			},
			Limit: new(0),
		}, func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
			o.LockMode = sql.LockNone
		})
	})
	if err != nil {
		return nil, err
	}
	if result == nil {
		return nil, nil
	}
	return result.([]*Product), nil
}

// resolveUpsertManyRows reads back the rows one UpsertMany sub-batch wrote,
// keyed on the conflict target the statement used, and returns each row's
// primary key in the batch's own order.
//
// It exists because no dialect reports a batch's keys: MySQL's LAST_INSERT_ID()
// names the first *newly inserted* row after a mixed batch — not the batch's
// first row, so fabricating ids as firstID+i is unsound — and RETURNING omits
// every row that took the DO NOTHING branch. Reading back by
// the conflict columns is unambiguous for the same reason
// resolveUpsertConflictRow's lookup is: an explicit conflict target can only
// have fired on those columns.
//
// products.id is database-generated, so every call takes this path.
//
// The lookup applies neither the soft-delete filter nor a tenant predicate. The
// unique index matched regardless of either, so a soft-deleted or other-tenant
// row is still the row that conflicted and still the row whose key this
// resolves; the terminal GetMany then applies the read path's own filters,
// exactly as on the DO UPDATE SET branch.
//
// It is a second statement, so a concurrent delete between the two leaves a row
// unmatched. That is reported rather than silently returned short.
func (c *productClient) resolveUpsertManyRows(ctx context.Context, conn database.Querier, conflictColumns []string, positions []int, rows [][]any) ([]int64, error) {
	if len(rows) == 0 {
		return nil, nil
	}
	keySets := make([][]any, len(rows))
	for i, row := range rows {
		vals := make([]any, len(positions))
		for j, pos := range positions {
			vals[j] = row[pos]
		}
		keySets[i] = vals
	}

	// Copied rather than sorted in place: conflictColumns aliases the
	// package-level productConflictColumns entry, and BuildSelect
	// emits its column list sorted, so scanProducts
	// must be handed the same sorted list to bind targets against.
	lookupColumns := make([]string, 0, len(conflictColumns)+2)
	lookupColumns = append(lookupColumns, conflictColumns...)
	for _, required := range []string{"id"} {
		if !slices.Contains(lookupColumns, required) {
			lookupColumns = append(lookupColumns, required)
		}
	}
	slices.Sort(lookupColumns)

	query, args := sql.BuildSelect(c.dialect, c.table, sql.SelectOptions{
		Columns:    lookupColumns,
		Conditions: []sql.Condition{sql.BuildCompositePKBatchCondition(c.dialect, conflictColumns, keySets)},
	})
	queried, err := conn.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	found, err := scanProducts(queried, lookupColumns)
	if cerr := queried.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return nil, err
	}

	// The read-back row is keyed by the same function the value rows are, over
	// the conflict columns in their own order — so keyPositions is the identity.
	keyPositions := make([]int, len(conflictColumns))
	for i := range keyPositions {
		keyPositions[i] = i
	}
	type resolvedRow struct {
		pk int64
	}
	byKey := make(map[string]resolvedRow, len(found))
	for _, entity := range found {
		keyRow := make([]any, len(conflictColumns))
		for i, col := range conflictColumns {
			keyRow[i] = productColumnValue(entity, col)
		}
		key, ok := upsertDedupeKey(keyRow, keyPositions)
		if !ok {
			continue
		}
		byKey[key] = resolvedRow{pk: entity.ID}
	}

	pks := make([]int64, len(rows))
	for i, row := range rows {
		key, ok := upsertDedupeKey(row, positions)
		if !ok {
			return nil, fmt.Errorf("row %d carries no definite conflict-target value", i)
		}
		resolved, ok := byKey[key]
		if !ok {
			return nil, fmt.Errorf("row %d was written but could not be read back by conflict target %v: the stored value differs from the one supplied (a case-insensitive collation, CHAR padding or a timestamp precision the column truncates), or the row was deleted concurrently", i, conflictColumns)
		}
		pks[i] = resolved.pk
	}
	return pks, nil
}

// productColumnValue returns one column's value off a scanned
// Product, so a row read back by resolveUpsertManyRows can be keyed
// against the value row that wrote it. The conflict target is a runtime
// argument, so the column cannot be selected at generation time — but its Go
// type can, which is what keeps this switch free of reflection, like
// scanProducts.
func productColumnValue(p *Product, column string) any {
	switch column {
	case "id":
		return p.ID
	case "category_id":
		return p.CategoryID
	case "title":
		return p.Title
	case "price":
		return p.Price
	case "weight_kg":
		return p.WeightKg
	case "in_stock":
		return p.InStock
	case "sku":
		return p.SKU
	case "created_at":
		return p.CreatedAt
	}
	return nil
}

// ProductIncrementColumn identifies a numeric column eligible for atomic increment/decrement.
type ProductIncrementColumn string

const (
	ProductIncrementPrice    ProductIncrementColumn = "price"
	ProductIncrementWeightKg ProductIncrementColumn = "weight_kg"
)

// Increment atomically increments or decrements a numeric column on a product.
// A negative amount performs a decrement.
// Returns ErrNotFound if the primary key does not exist.
func (c *productClient) Increment(ctx context.Context, id int64, input IncrementInput[ProductIncrementColumn], opts ...func(*CallOptions[ProductFieldOptions])) error {
	options := resolveCallOptions(opts)
	_, err := c.executeMutation(ctx, options.SkipHooks, &hook.MutationContext{
		Op: hook.OpIncrement, Table: TableProducts, Schema: "",
		PK: id, Input: input, CallOptions: options,
	}, func(ctx context.Context, m *hook.MutationContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		query, args := sql.BuildIncrement(c.dialect, c.table, string(input.Column), input.Amount, []sql.Condition{
			sql.Where(c.dialect.QuoteIdentifier("id")).Eq(id),
		})

		execResult, err := conn.Exec(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("increment product %s: %w", input.Column, err)
		}

		count, err := execResult.RowsAffected()
		if err != nil {
			return nil, fmt.Errorf("increment product rows affected: %w", err)
		}
		if count == 0 {
			return nil, ErrNotFound
		}
		m.AffectedPKs = []any{id}
		return nil, nil
	})
	return err
}

// Exists returns true if a product with the given primary key exists.
func (c *productClient) Exists(ctx context.Context, id int64, opts ...func(*CallOptions[ProductFieldOptions])) (bool, error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpExists, Table: TableProducts, Schema: "",
		PK: id, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)
		conds := []sql.Condition{sql.Where(c.dialect.QuoteIdentifier("id")).Eq(id)}

		query, args := sql.BuildExists(c.dialect, c.table, conds)

		var exists bool
		if err := conn.QueryRow(ctx, query, args...).Scan(&exists); err != nil {
			return false, fmt.Errorf("exists product: %w", err)
		}
		return exists, nil
	})
	if err != nil {
		return false, err
	}
	return result.(bool), nil
}

// ExistsWhere returns true if any product matches the given filter.
func (c *productClient) ExistsWhere(ctx context.Context, filter *ProductFilter, opts ...func(*CallOptions[ProductFieldOptions])) (bool, error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpExists, Table: TableProducts, Schema: "",
		Input: filter, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		var conds []sql.Condition
		if filter != nil {
			conds = filter.ToConditions(c.dialect)
		}

		query, args := sql.BuildExists(c.dialect, c.table, conds)

		var exists bool
		if err := conn.QueryRow(ctx, query, args...).Scan(&exists); err != nil {
			return false, fmt.Errorf("exists product where: %w", err)
		}
		return exists, nil
	})
	if err != nil {
		return false, err
	}
	return result.(bool), nil
}

// Count returns the number of products matching the given filter.
// A nil filter counts all products.
func (c *productClient) Count(ctx context.Context, filter *ProductFilter, opts ...func(*CallOptions[ProductFieldOptions])) (int64, error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpCount, Table: TableProducts, Schema: "",
		Input: filter, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		conn := database.Conn(ctx, c.querier)

		var conds []sql.Condition
		if filter != nil {
			conds = filter.ToConditions(c.dialect)
		}

		query, args := sql.BuildCount(c.dialect, c.table, conds)

		var count int64
		if err := conn.QueryRow(ctx, query, args...).Scan(&count); err != nil {
			return int64(0), fmt.Errorf("count products: %w", err)
		}
		return count, nil
	})
	if err != nil {
		return 0, err
	}
	return result.(int64), nil
}

// Paginate returns a page of products with total count for offset-based pagination.
// A nil filter paginates all products.
func (c *productClient) Paginate(ctx context.Context, input PaginateInput[ProductFilter], opts ...func(*CallOptions[ProductFieldOptions])) (*PaginateResult[Product], error) {
	options := resolveCallOptions(opts)
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpPaginate, Table: TableProducts, Schema: "",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		// Internal calls with SkipHooks to prevent nested hook invocation
		internalOpts := func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
		}

		// Total count (delegates to Count — both are always generated)
		totalCount, err := c.Count(ctx, input.Filter, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("paginate products count: %w", err)
		}

		// Page data via GetMany (handles FieldOptions and relationships)
		products, err := c.GetMany(ctx, &GetProductsInput{
			Filter: input.Filter,
			Sorts:  input.Sort,
			Limit:  &input.Limit,
			Offset: &input.Offset,
		}, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("paginate products: %w", err)
		}

		return &PaginateResult[Product]{
			Items:      products,
			TotalCount: totalCount,
			Offset:     input.Offset,
			Limit:      input.Limit,
			HasMore:    int64(input.Offset+input.Limit) < totalCount,
		}, nil
	})
	if err != nil {
		return nil, err
	}
	return result.(*PaginateResult[Product]), nil
}

// Connection returns a Relay-style cursor-paginated connection of products.
// Sort order is determined by cursor_keys — custom sorts are not supported.
// Use Paginate for custom sort orders.
func (c *productClient) Connection(ctx context.Context, input ConnectionInput[ProductFilter], opts ...func(*CallOptions[ProductFieldOptions])) (*Connection[Product], error) {
	options := resolveCallOptions(opts)

	if options.LockMode != sql.LockNone {
		return nil, fmt.Errorf("connection products: LockMode is unsupported on sqlite dialect")
	}
	result, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
		Op: hook.OpConnection, Table: TableProducts, Schema: "",
		Input: input, CallOptions: options,
	}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
		// Internal calls with SkipHooks to prevent nested hook invocation
		internalOpts := func(o *CallOptions[ProductFieldOptions]) {
			*o = options
			o.SkipHooks = true
		}

		// Validate: first and last are mutually exclusive
		if input.First != nil && input.Last != nil {
			return nil, ErrInvalidCursor
		}

		// Total count (separate COUNT query — no cursor conditions)
		totalCount, err := c.Count(ctx, input.Filter, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("connection products count: %w", err)
		}

		// Decode cursors and build keyset conditions
		var keysetConds []sql.Condition
		if input.After != nil {
			cursor, err := decodeCursor(*input.After)
			if err != nil {
				return nil, ErrInvalidCursor
			}
			keysetConds = append(keysetConds, cursorKeyset(c.dialect, c.cursorKeys, cursor, ">"))
		}
		if input.Before != nil {
			cursor, err := decodeCursor(*input.Before)
			if err != nil {
				return nil, ErrInvalidCursor
			}
			keysetConds = append(keysetConds, cursorKeyset(c.dialect, c.cursorKeys, cursor, "<"))
		}

		// Direction and limit
		limit := c.pageSize
		ascending := true
		if input.First != nil {
			limit = *input.First
		} else if input.Last != nil {
			limit = *input.Last
			ascending = false
		}

		// Fetch limit+1 rows via GetMany (handles FieldOptions, O2O joins, relationships, soft delete)
		connLimit := limit + 1
		products, err := c.GetMany(ctx, &GetProductsInput{
			Filter:     input.Filter,
			Sorts:      cursorSorts(c.cursorKeys, ascending),
			Limit:      &connLimit,
			conditions: keysetConds,
			// Each edge's cursor is encoded from the row it wraps, so the cursor
			// keys have to survive a narrowed FieldOptions — otherwise the
			// encoder reads fields the SELECT never filled and every cursor
			// carries zero values.
			requiredColumns: c.cursorKeys,
		}, internalOpts)
		if err != nil {
			return nil, fmt.Errorf("connection products: %w", err)
		}

		// Trim extra row and determine page boundaries
		hasMore := len(products) > limit
		if hasMore {
			products = products[:limit]
		}

		// Backward pagination: reverse for ascending cursor order
		if !ascending {
			slices.Reverse(products)
		}

		// Build edges with encoded cursors
		edges := make([]Edge[Product], len(products))
		for i, row := range products {
			cursor, err := encodeProductCursor(c.cursorKeys, row)
			if err != nil {
				return nil, err
			}
			edges[i] = Edge[Product]{
				Node:   row,
				Cursor: cursor,
			}
		}

		pageInfo := PageInfo{
			HasNextPage:     (ascending && hasMore) || (!ascending && input.Before != nil),
			HasPreviousPage: (!ascending && hasMore) || (ascending && input.After != nil),
		}
		if len(edges) > 0 {
			pageInfo.StartCursor = &edges[0].Cursor
			pageInfo.EndCursor = &edges[len(edges)-1].Cursor
		}

		return &Connection[Product]{Edges: edges, PageInfo: pageInfo, TotalCount: totalCount}, nil
	})
	if err != nil {
		return nil, err
	}
	return result.(*Connection[Product]), nil
}

// encodeProductCursor encodes cursor key values as a base64 JSON string.
func encodeProductCursor(keys []string, p *Product) (string, error) {
	out := make(map[string]any, len(keys))
	for _, key := range keys {
		switch key {
		case "id":
			out["id"] = p.ID
		case "category_id":
			out["category_id"] = p.CategoryID
		case "title":
			out["title"] = p.Title
		case "price":
			out["price"] = p.Price
		case "weight_kg":
			out["weight_kg"] = p.WeightKg
		case "in_stock":
			out["in_stock"] = p.InStock
		case "sku":
			out["sku"] = p.SKU
		case "created_at":
			out["created_at"] = p.CreatedAt
		}
	}
	data, err := json.Marshal(out)
	if err != nil {
		return "", fmt.Errorf("encode product cursor: %w", err)
	}
	return base64.StdEncoding.EncodeToString(data), nil
}

// StreamProductsInput holds query parameters for streaming products records.
// Stream is iterator-style and intentionally has no Limit/Offset.
// Field selection is controlled via CallOptions.FieldOptions, not this struct.
type StreamProductsInput struct {
	Filter *ProductFilter `json:"filter"`
	Sorts  []sql.Sort     `json:"sorts"`
}

// StreamProductFieldOptions controls scalar column selection for products streams.
// Stream cannot load relationships — only scalar columns are selectable.
type StreamProductFieldOptions struct {
	ID         bool `json:"id"`
	CategoryID bool `json:"category_id"`
	Title      bool `json:"title"`
	Price      bool `json:"price"`
	WeightKg   bool `json:"weight_kg"`
	InStock    bool `json:"in_stock"`
	SKU        bool `json:"sku"`
	CreatedAt  bool `json:"created_at"`
}

// Columns returns the SQL column names for all selected columns, sorted alphabetically
// to match the SQL builder's deterministic column ordering.
func (fo *StreamProductFieldOptions) Columns() []string {
	var cols []string
	if fo.ID {
		cols = append(cols, "id")
	}
	if fo.CategoryID {
		cols = append(cols, "category_id")
	}
	if fo.Title {
		cols = append(cols, "title")
	}
	if fo.Price {
		cols = append(cols, "price")
	}
	if fo.WeightKg {
		cols = append(cols, "weight_kg")
	}
	if fo.InStock {
		cols = append(cols, "in_stock")
	}
	if fo.SKU {
		cols = append(cols, "sku")
	}
	if fo.CreatedAt {
		cols = append(cols, "created_at")
	}
	slices.Sort(cols)
	return cols
}

// HasSelectedColumns reports whether any column is selected.
func (fo *StreamProductFieldOptions) HasSelectedColumns() bool {
	if fo.ID {
		return true
	}
	if fo.CategoryID {
		return true
	}
	if fo.Title {
		return true
	}
	if fo.Price {
		return true
	}
	if fo.WeightKg {
		return true
	}
	if fo.InStock {
		return true
	}
	if fo.SKU {
		return true
	}
	if fo.CreatedAt {
		return true
	}
	return false
}

// scanProductRow scans a single row into a Product entity.
// Used by Stream to yield rows one at a time without materializing the result set.
func scanProductRow(rows database.Rows, columns []string) (*Product, error) {
	p := &Product{}

	targets := make([]any, len(columns))
	for idx, col := range columns {
		switch col {
		case "id":
			targets[idx] = &p.ID
		case "category_id":
			targets[idx] = &p.CategoryID
		case "title":
			targets[idx] = &p.Title
		case "price":
			targets[idx] = &p.Price
		case "weight_kg":
			targets[idx] = &p.WeightKg
		case "in_stock":
			targets[idx] = &p.InStock
		case "sku":
			targets[idx] = &p.SKU
		case "created_at":
			targets[idx] = &p.CreatedAt
		}
	}

	if err := rows.Scan(targets...); err != nil {
		return nil, fmt.Errorf("scan product: %w", err)
	}

	return p, nil
}

// Stream returns an iterator over products matching the given filter and sort criteria.
// Rows are yielded as the driver returns them, without materializing the full
// result set. Cache is bypassed regardless of caller setting.
// Stream cannot load relationships — use Connection in a loop when relationships
// are required.
//
// Stream refuses an active transaction. It runs consumer code inside an open
// result set, which inside a transaction is the transaction's only connection,
// held for the whole iteration — so a statement issued from the loop body on the
// same txCtx waits on a reservation the loop itself holds. Set
// CallOptions.AllowInTransaction for a snapshot-consistent stream that issues
// nothing else on that txCtx. That obligation is the one rule that remains the
// caller's — drain or close a result set before issuing the next statement on
// that txCtx — applied to a loop whose body is caller code.
func (c *productClient) Stream(ctx context.Context, input *StreamProductsInput, opts ...func(*CallOptions[StreamProductFieldOptions])) iter.Seq2[*Product, error] {
	return func(yield func(*Product, error) bool) {
		// A nil input is the zero-value input. Without it, an
		// unguarded nil dereference in the handler would be recovered by the
		// panic wrapper and reported as an error instead of streaming the table.
		if input == nil {
			input = &StreamProductsInput{}
		}
		options := resolveCallOptions(opts)
		options.SkipCache = true

		// Stream's contract is that the connection stays open across
		// caller code; a transaction's is one connection, one statement at a
		// time. The two cannot both hold, so Stream refuses a transaction unless
		// the caller opts in. Refused before any SQL is issued and before the
		// hook chain is built, mirroring the LockMode precondition, and
		// surfaced through yield because Stream returns an iterator and has no
		// error return.
		if database.InTransaction(ctx) && !options.AllowInTransaction {
			yield(nil, fmt.Errorf("stream products: unsupported inside a transaction — use Connection in a loop, "+
				"or set AllowInTransaction for a snapshot-consistent stream that issues nothing else on this txCtx"))
			return
		}

		// stopped is true while the consumer's loop body runs, and stays true
		// once the body breaks (yield returned false) or panics out of yield.
		// Calling yield again after either makes the Go runtime panic, so the
		// chain's error below is yielded only while stopped is false.
		var stopped bool
		emit := func(row *Product, err error) bool {
			stopped = true
			if !yield(row, err) {
				return false
			}
			stopped = false
			return true
		}

		// A recovered panic and a hook's abort error are the
		// chain's return value. Stream has no error return, so it yields that
		// error once, after anything the handler yielded.
		_, err := c.executeQuery(ctx, options.SkipHooks, &hook.QueryContext{
			Op: hook.OpStream, Table: TableProducts, Schema: "",
			Input: input, CallOptions: options,
		}, func(ctx context.Context, q *hook.QueryContext) (any, error) {
			conn := database.Conn(ctx, c.querier)

			fieldOptions := options.FieldOptions
			columns := productAllColumns
			if fieldOptions != nil {
				if selected := fieldOptions.Columns(); len(selected) > 0 {
					columns = selected
				}
			}

			var conds []sql.Condition
			if input.Filter != nil {
				conds = input.Filter.ToConditions(c.dialect)
			}

			query, args := sql.BuildSelect(c.dialect, c.table, sql.SelectOptions{
				Columns:    columns,
				Conditions: conds,
				OrderBy:    input.Sorts,
			})

			rows, err := conn.Query(ctx, query, args...)
			if err != nil {
				emit(nil, fmt.Errorf("stream products: %w", err))
				return nil, nil
			}
			defer rows.Close()

			for rows.Next() {
				p, err := scanProductRow(rows, columns)
				if err != nil {
					if !emit(nil, err) {
						return nil, nil
					}
					continue
				}
				if !emit(p, nil) {
					return nil, nil
				}
			}
			if err := rows.Err(); err != nil {
				emit(nil, fmt.Errorf("iterate product rows: %w", err))
			}
			return nil, nil
		})
		if err != nil && !stopped {
			yield(nil, err)
		}
	}
}

// ProductFilter provides type-safe filtering for the products table.
type ProductFilter struct {
	CategoryID       *comparator.Number[int64]           `json:"category_id"`
	CreatedAt        *comparator.Time                    `json:"created_at"`
	ID               *comparator.Number[int64]           `json:"id"`
	InStock          *comparator.Bool                    `json:"in_stock"`
	Price            *comparator.Number[float64]         `json:"price"`
	SKU              *comparator.String                  `json:"sku"`
	Title            *comparator.String                  `json:"title"`
	WeightKg         *comparator.NullableNumber[float64] `json:"weight_kg"`
	OrderItems       *OrderItemFilter                    `json:"order_items"`
	ProductTagLabels *ProductTagLabelFilter              `json:"product_tag_labels"`
	And              []*ProductFilter                    `json:"and"`
	Or               []*ProductFilter                    `json:"or"`
}

// ToConditions converts the filter to a slice of SQL conditions.
//
// A nil receiver contributes no conditions. Two callers depend on that. The
// *Where methods dereference their filter only here and document a nil one as
// the empty-filter case, so this is what makes ErrEmptyFilter reachable instead
// of a nil dereference. And a nil entry inside and / or is skipped rather than
// fatal, matching the "an unset member contributes no SQL" rule the
// relationship members already follow.
func (f *ProductFilter) ToConditions(dialect sql.Dialect, opts ...FilterOption) []sql.Condition {
	if f == nil {
		return nil
	}

	var conds []sql.Condition

	if f.CategoryID != nil {
		conds = append(conds, f.CategoryID.Parse(dialect.QuoteIdentifier("category_id"), dialect)...)
	}

	if f.CreatedAt != nil {
		conds = append(conds, f.CreatedAt.Parse(dialect.QuoteIdentifier("created_at"), dialect)...)
	}

	if f.ID != nil {
		conds = append(conds, f.ID.Parse(dialect.QuoteIdentifier("id"), dialect)...)
	}

	if f.InStock != nil {
		conds = append(conds, f.InStock.Parse(dialect.QuoteIdentifier("in_stock"), dialect)...)
	}

	if f.Price != nil {
		conds = append(conds, f.Price.Parse(dialect.QuoteIdentifier("price"), dialect)...)
	}

	if f.SKU != nil {
		conds = append(conds, f.SKU.Parse(dialect.QuoteIdentifier("sku"), dialect)...)
	}

	if f.Title != nil {
		conds = append(conds, f.Title.Parse(dialect.QuoteIdentifier("title"), dialect)...)
	}

	if f.WeightKg != nil {
		conds = append(conds, f.WeightKg.Parse(dialect.QuoteIdentifier("weight_kg"), dialect)...)
	}

	if f.OrderItems != nil {
		conds = append(conds, productOrderItemsFilterExists(f.OrderItems, dialect, opts))
	}

	if f.ProductTagLabels != nil {
		conds = append(conds, productProductTagLabelsFilterExists(f.ProductTagLabels, dialect, opts))
	}

	for _, sub := range f.And {
		subConds := sub.ToConditions(dialect, opts...)
		if len(subConds) > 0 {
			conds = append(conds, sql.And(subConds...))
		}
	}

	// A filter object's own fields are always conjunctive, so each or member
	// contributes sql.And of its own conditions and the members are OR-ed
	// together as ONE group condition. Appending a per-member
	// sql.Or instead hands the caller N conditions, and buildWhere joins those
	// with AND — turning or: [A, B] into A AND B, while simultaneously OR-ing a
	// single member's own fields against each other.
	//
	// The group is appended only when some member compiled to something:
	// sql.Or of nothing expands to a literal "()", which buildWhere keeps
	// because it is not the empty string, yielding invalid SQL.
	var orGroup []sql.Condition
	for _, sub := range f.Or {
		subConds := sub.ToConditions(dialect, opts...)
		if len(subConds) > 0 {
			orGroup = append(orGroup, sql.And(subConds...))
		}
	}
	if len(orGroup) > 0 {
		conds = append(conds, sql.Or(orGroup...))
	}

	return conds
}

// productOrderItemsFilterExists compiles a OrderItemFilter set on the
// OrderItems relationship into a correlated EXISTS over order_items.
//
// The parent-side reference carries no qualifier: sql.CorrelationToken is
// resolved by the builder against whichever FROM clause encloses the predicate,
// so one emitted value is correct on both the plain read path and the aliased
// O2O-join path.
//
// The subquery alias is keyed on nesting depth. A relationship filter nested
// inside itself — legal for a self-referential relationship — would
// otherwise reuse the alias and let the inner subquery shadow the reference its
// own correlation resolves against.
//
// MySQL rejects an EXISTS naming the table an UPDATE or DELETE is mutating
// (error 1093). A relationship filter whose target is the mutated table is
// therefore a read-path predicate on MySQL, not one to pass to UpdateWhere /
// SoftDeleteWhere / HardDeleteWhere / Increment.
func productOrderItemsFilterExists(f *OrderItemFilter, dialect sql.Dialect, opts []FilterOption) sql.Condition {
	scope := resolveFilterScope(opts)
	tgt := filterSubqueryAlias("tgt", scope.depth)
	subSQL := "SELECT 1 FROM " + dialect.FormatTable(sql.Table{Schema: "", Name: "order_items"}) + " " + tgt +
		" WHERE " + tgt + "." + dialect.QuoteIdentifier("product_id") + " = " + sql.CorrelationToken
	var subArgs []any

	// The target's own ToConditions supplies the inner WHERE, so nesting and
	// and/or compose recursively. Every reference is qualified with the target
	// alias: unqualified names inside a correlated subquery bind to the
	// enclosing statement whenever the target lacks the column.
	if where, whereArgs := sql.SubqueryWhere(dialect, tgt, f.ToConditions(dialect, nestFilterScope(opts, scope.depth+1)...)); where != "" {
		subSQL += " AND " + where
		subArgs = append(subArgs, whereArgs...)
	}

	return sql.Exists("id", sql.Subquery{SQL: subSQL, Args: subArgs})
}

// productProductTagLabelsFilterExists compiles a ProductTagLabelFilter set on the
// ProductTagLabels relationship into a correlated EXISTS over product_tag_labels.
//
// The parent-side reference carries no qualifier: sql.CorrelationToken is
// resolved by the builder against whichever FROM clause encloses the predicate,
// so one emitted value is correct on both the plain read path and the aliased
// O2O-join path.
//
// The subquery alias is keyed on nesting depth. A relationship filter nested
// inside itself — legal for a self-referential relationship — would
// otherwise reuse the alias and let the inner subquery shadow the reference its
// own correlation resolves against.
//
// MySQL rejects an EXISTS naming the table an UPDATE or DELETE is mutating
// (error 1093). A relationship filter whose target is the mutated table is
// therefore a read-path predicate on MySQL, not one to pass to UpdateWhere /
// SoftDeleteWhere / HardDeleteWhere / Increment.
func productProductTagLabelsFilterExists(f *ProductTagLabelFilter, dialect sql.Dialect, opts []FilterOption) sql.Condition {
	scope := resolveFilterScope(opts)
	tgt := filterSubqueryAlias("tgt", scope.depth)
	subSQL := "SELECT 1 FROM " + dialect.FormatTable(sql.Table{Schema: "", Name: "product_tag_labels"}) + " " + tgt +
		" WHERE " + tgt + "." + dialect.QuoteIdentifier("product_id") + " = " + sql.CorrelationToken
	var subArgs []any

	// The target's own ToConditions supplies the inner WHERE, so nesting and
	// and/or compose recursively. Every reference is qualified with the target
	// alias: unqualified names inside a correlated subquery bind to the
	// enclosing statement whenever the target lacks the column.
	if where, whereArgs := sql.SubqueryWhere(dialect, tgt, f.ToConditions(dialect, nestFilterScope(opts, scope.depth+1)...)); where != "" {
		subSQL += " AND " + where
		subArgs = append(subArgs, whereArgs...)
	}

	return sql.Exists("id", sql.Subquery{SQL: subSQL, Args: subArgs})
}

// ProductFieldOptions controls column selection and relationship loading for products queries.
type ProductFieldOptions struct {
	ID               bool                                `json:"id"`
	CategoryID       bool                                `json:"category_id"`
	Title            bool                                `json:"title"`
	Price            bool                                `json:"price"`
	WeightKg         bool                                `json:"weight_kg"`
	InStock          bool                                `json:"in_stock"`
	SKU              bool                                `json:"sku"`
	CreatedAt        bool                                `json:"created_at"`
	OrderItems       *OrderItemRelationshipOptions       `json:"order_items"`
	ProductTagLabels *ProductTagLabelRelationshipOptions `json:"product_tag_labels"`
}

// Columns returns the SQL column names for all selected columns, sorted alphabetically
// to match the SQL builder's deterministic column ordering.
func (fo *ProductFieldOptions) Columns() []string {
	var cols []string
	if fo.ID {
		cols = append(cols, "id")
	}
	if fo.CategoryID {
		cols = append(cols, "category_id")
	}
	if fo.Title {
		cols = append(cols, "title")
	}
	if fo.Price {
		cols = append(cols, "price")
	}
	if fo.WeightKg {
		cols = append(cols, "weight_kg")
	}
	if fo.InStock {
		cols = append(cols, "in_stock")
	}
	if fo.SKU {
		cols = append(cols, "sku")
	}
	if fo.CreatedAt {
		cols = append(cols, "created_at")
	}
	slices.Sort(cols)
	return cols
}

// ColumnMap returns a mapping of Go field name to SQL column name for all columns.
func (fo *ProductFieldOptions) ColumnMap() map[string]string {
	return map[string]string{
		"ID":         "id",
		"CategoryID": "category_id",
		"Title":      "title",
		"Price":      "price",
		"WeightKg":   "weight_kg",
		"InStock":    "in_stock",
		"SKU":        "sku",
		"CreatedAt":  "created_at",
	}
}

// HasSelectedColumns reports whether any column or relationship is selected.
func (fo *ProductFieldOptions) HasSelectedColumns() bool {
	if fo.ID {
		return true
	}
	if fo.CategoryID {
		return true
	}
	if fo.Title {
		return true
	}
	if fo.Price {
		return true
	}
	if fo.WeightKg {
		return true
	}
	if fo.InStock {
		return true
	}
	if fo.SKU {
		return true
	}
	if fo.CreatedAt {
		return true
	}
	if fo.OrderItems != nil {
		return true
	}
	if fo.ProductTagLabels != nil {
		return true
	}
	return false
}

// ProductTagLabelRelationshipOptions controls loading options for ProductTagLabel relationships.
type ProductTagLabelRelationshipOptions struct {
	FieldOptions *ProductTagLabelFieldOptions `json:"field_options"`
	Filter       *ProductTagLabelFilter       `json:"filter"`
	Sorts        []sql.Sort                   `json:"sorts"`
}

// CreateProductInput holds the fields for creating a products record.
type CreateProductInput struct {
	CategoryID int64                           `json:"category_id"`
	Title      string                          `json:"title"`
	Price      float64                         `json:"price"`
	WeightKg   omittable.Value[*float64]       `json:"weight_kg,omitzero"`
	InStock    omittable.Value[bool]           `json:"in_stock,omitzero"`
	SKU        string                          `json:"sku"`
	CreatedAt  omittable.Value[types.DateTime] `json:"created_at,omitzero"`
}

// UpdateProductInput holds the fields for updating a products record.
// All fields use omittable.Value to distinguish "not set" from "set to zero".
type UpdateProductInput struct {
	CategoryID omittable.Value[int64]          `json:"category_id,omitzero"`
	Title      omittable.Value[string]         `json:"title,omitzero"`
	Price      omittable.Value[float64]        `json:"price,omitzero"`
	WeightKg   omittable.Value[*float64]       `json:"weight_kg,omitzero"`
	InStock    omittable.Value[bool]           `json:"in_stock,omitzero"`
	SKU        omittable.Value[string]         `json:"sku,omitzero"`
	CreatedAt  omittable.Value[types.DateTime] `json:"created_at,omitzero"`
}

// GetProductsInput holds query parameters for retrieving products records.
// Field selection is controlled via CallOptions.FieldOptions, not this struct.
type GetProductsInput struct {
	Filter *ProductFilter `json:"filter"`
	Limit  *int           `json:"limit"`
	Offset *int           `json:"offset"`
	Sorts  []sql.Sort     `json:"sorts"`
	// conditions holds additional SQL conditions injected by internal callers
	// (e.g., Connection keyset conditions). Not part of the public API.
	conditions []sql.Condition
	// requiredColumns holds columns an internal caller needs read back even
	// when FieldOptions narrows the projection (e.g., Connection cursor keys).
	// Not part of the public API.
	requiredColumns []string
}
