// Code generated by sqlgen dev. DO NOT EDIT.
package models

import (
	"context"
	"maps"
	"time"
	"uuid"

	"github.com/teandresmith/sqlgen/database"
	"github.com/teandresmith/sqlgen/event"
	"github.com/teandresmith/sqlgen/hook"
)

// eventSkipper is implemented by CallOptions to check the SkipEvents flag.
type eventSkipper interface {
	skipEvents() bool
}

func (o CallOptions[FO]) skipEvents() bool { return o.SkipEvents }

// mapOpToAction maps a mutation operation to an event action.
func mapOpToAction(op hook.MutationOp) event.Action {
	switch op {
	case hook.OpCreate, hook.OpCreateMany:
		return event.Create
	case hook.OpUpdate, hook.OpUpdateMany, hook.OpUpdateWhere,
		hook.OpRestore, hook.OpRestoreMany, hook.OpRestoreWhere,
		hook.OpIncrement:
		return event.Update
	case hook.OpSoftDelete, hook.OpSoftDeleteMany, hook.OpSoftDeleteWhere,
		hook.OpHardDelete, hook.OpHardDeleteMany, hook.OpHardDeleteWhere:
		return event.Delete
	case hook.OpUpsert, hook.OpUpsertMany:
		// Batched upserts reuse the single-row action: a
		// subscriber filtering event.Upsert receives them without changing
		// its filter, and no new wire action is introduced.
		return event.Upsert
	default:
		return event.Action(string(op))
	}
}

// mergeEventMetadata builds one event's Metadata from the per-hook
// MetadataFunc result (base) and the system-owned keys (system —
// currently only the tenant stamp). base is shallow-cloned per event so
// a shared map never bleeds across the fanned-out batch, and the system keys
// are applied last so consumer metadata cannot override them. Returns nil when
// neither source contributes a key, keeping the no-metadata path
// byte-identical to prior output (a nil MetadataFunc on a non-tenanted table
// yields a nil Metadata, exactly as before).
func mergeEventMetadata(base, system map[string]string) map[string]string {
	if len(base) == 0 && len(system) == 0 {
		return nil
	}
	merged := make(map[string]string, len(base)+len(system))
	maps.Copy(merged, base)
	maps.Copy(merged, system)
	return merged
}

// newArticleEventHook creates a mutation hook that publishes events for Article mutations.
func newArticleEventHook(publisher event.Publisher, onError func(ctx context.Context, events []event.Event, err error), metaFunc func(ctx context.Context) map[string]string) hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, mc *hook.MutationContext) (any, error) {
			result, err := next(ctx, mc)
			if err != nil {
				return result, err
			}

			// Check SkipEvents via CallOptions
			if skipper, ok := mc.CallOptions.(eventSkipper); ok && skipper.skipEvents() {
				return result, nil
			}

			if len(mc.AffectedPKs) == 0 {
				return result, nil
			}

			// MetadataFunc: resolve consumer metadata
			// once here at hook entry, where the request ctx is still live —
			// never from the deferred OnCommit callback, which runs on
			// context.Background(). The result is merged into
			// each fanned-out event below; the system tenant stamp is applied
			// last so a consumer cannot override it.
			var baseMeta map[string]string
			if metaFunc != nil {
				baseMeta = metaFunc(ctx)
			}

			events := make([]event.Event, len(mc.AffectedPKs))

			// Per-entity Input fanout. For batch ops the i-th
			// fanned-out event carries the i-th element of the published
			// input slice — keeps wire cost O(N) on serialization and lets
			// subscribers run one type-switch across single-op and batch
			// shapes uniformly. UpsertMany publishes the *deduped* slice
			// rather than the caller's, which is the one index-aligned with
			// AffectedPKs. *Many delete/restore ops carry nil since
			// the PK already travels via Event.PK; *Where ops and single-op
			// mutations keep mc.Input unchanged.
			var (
				batchCreateInputs []*CreateArticleInput
				batchUpdateItems  []UpdateArticleItem
			)
			switch mc.Op {
			case hook.OpCreateMany, hook.OpUpsertMany:
				batchCreateInputs, _ = mc.Input.([]*CreateArticleInput)
			case hook.OpUpdateMany:
				batchUpdateItems, _ = mc.Input.([]UpdateArticleItem)
			}
			for i, pk := range mc.AffectedPKs {
				var inputVal any
				switch mc.Op {
				case hook.OpCreateMany, hook.OpUpsertMany:
					if i < len(batchCreateInputs) {
						inputVal = batchCreateInputs[i]
					}
				case hook.OpUpdateMany:
					if i < len(batchUpdateItems) {
						inputVal = batchUpdateItems[i]
					}
				case hook.OpHardDeleteMany, hook.OpSoftDeleteMany, hook.OpRestoreMany:
					// Per-entity input is nil — the PK already travels via Event.PK.
				default:
					inputVal = mc.Input
				}
				events[i] = event.Event{
					ID:        uuid.NewV4().String(),
					Table:     "articles",
					Schema:    mc.Schema,
					Action:    mapOpToAction(mc.Op),
					PK:        pk,
					Input:     inputVal,
					Timestamp: time.Now(),
					Metadata:  mergeEventMetadata(baseMeta, nil),
				}
			}

			publish := func(ctx context.Context) error {
				if err := publisher.PublishBatch(ctx, events); err != nil {
					onError(ctx, events, err)
				}
				return nil
			}

			if tx := database.FromContext(ctx); tx != nil {
				tx.OnCommit(publish)
			} else {
				publish(ctx)
			}

			return result, nil
		}
	}
}

// newAuditLogEventHook creates a mutation hook that publishes events for AuditLog mutations.
func newAuditLogEventHook(publisher event.Publisher, onError func(ctx context.Context, events []event.Event, err error), metaFunc func(ctx context.Context) map[string]string) hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, mc *hook.MutationContext) (any, error) {
			result, err := next(ctx, mc)
			if err != nil {
				return result, err
			}

			// Check SkipEvents via CallOptions
			if skipper, ok := mc.CallOptions.(eventSkipper); ok && skipper.skipEvents() {
				return result, nil
			}

			if len(mc.AffectedPKs) == 0 {
				return result, nil
			}

			// MetadataFunc: resolve consumer metadata
			// once here at hook entry, where the request ctx is still live —
			// never from the deferred OnCommit callback, which runs on
			// context.Background(). The result is merged into
			// each fanned-out event below; the system tenant stamp is applied
			// last so a consumer cannot override it.
			var baseMeta map[string]string
			if metaFunc != nil {
				baseMeta = metaFunc(ctx)
			}

			events := make([]event.Event, len(mc.AffectedPKs))

			// Per-entity Input fanout. For batch ops the i-th
			// fanned-out event carries the i-th element of the published
			// input slice — keeps wire cost O(N) on serialization and lets
			// subscribers run one type-switch across single-op and batch
			// shapes uniformly. UpsertMany publishes the *deduped* slice
			// rather than the caller's, which is the one index-aligned with
			// AffectedPKs. *Many delete/restore ops carry nil since
			// the PK already travels via Event.PK; *Where ops and single-op
			// mutations keep mc.Input unchanged.
			var (
				batchCreateInputs []*CreateAuditLogInput
				batchUpdateItems  []UpdateAuditLogItem
			)
			switch mc.Op {
			case hook.OpCreateMany, hook.OpUpsertMany:
				batchCreateInputs, _ = mc.Input.([]*CreateAuditLogInput)
			case hook.OpUpdateMany:
				batchUpdateItems, _ = mc.Input.([]UpdateAuditLogItem)
			}
			for i, pk := range mc.AffectedPKs {
				var inputVal any
				switch mc.Op {
				case hook.OpCreateMany, hook.OpUpsertMany:
					if i < len(batchCreateInputs) {
						inputVal = batchCreateInputs[i]
					}
				case hook.OpUpdateMany:
					if i < len(batchUpdateItems) {
						inputVal = batchUpdateItems[i]
					}
				case hook.OpHardDeleteMany, hook.OpSoftDeleteMany, hook.OpRestoreMany:
					// Per-entity input is nil — the PK already travels via Event.PK.
				default:
					inputVal = mc.Input
				}
				events[i] = event.Event{
					ID:        uuid.NewV4().String(),
					Table:     "audit_logs",
					Schema:    mc.Schema,
					Action:    mapOpToAction(mc.Op),
					PK:        pk,
					Input:     inputVal,
					Timestamp: time.Now(),
					Metadata:  mergeEventMetadata(baseMeta, nil),
				}
			}

			publish := func(ctx context.Context) error {
				if err := publisher.PublishBatch(ctx, events); err != nil {
					onError(ctx, events, err)
				}
				return nil
			}

			if tx := database.FromContext(ctx); tx != nil {
				tx.OnCommit(publish)
			} else {
				publish(ctx)
			}

			return result, nil
		}
	}
}

// newOrderItemEventHook creates a mutation hook that publishes events for OrderItem mutations.
func newOrderItemEventHook(publisher event.Publisher, onError func(ctx context.Context, events []event.Event, err error), metaFunc func(ctx context.Context) map[string]string) hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, mc *hook.MutationContext) (any, error) {
			result, err := next(ctx, mc)
			if err != nil {
				return result, err
			}

			// Check SkipEvents via CallOptions
			if skipper, ok := mc.CallOptions.(eventSkipper); ok && skipper.skipEvents() {
				return result, nil
			}

			if len(mc.AffectedPKs) == 0 {
				return result, nil
			}

			// MetadataFunc: resolve consumer metadata
			// once here at hook entry, where the request ctx is still live —
			// never from the deferred OnCommit callback, which runs on
			// context.Background(). The result is merged into
			// each fanned-out event below; the system tenant stamp is applied
			// last so a consumer cannot override it.
			var baseMeta map[string]string
			if metaFunc != nil {
				baseMeta = metaFunc(ctx)
			}

			events := make([]event.Event, len(mc.AffectedPKs))

			// Per-entity Input fanout. For batch ops the i-th
			// fanned-out event carries the i-th element of the published
			// input slice — keeps wire cost O(N) on serialization and lets
			// subscribers run one type-switch across single-op and batch
			// shapes uniformly. UpsertMany publishes the *deduped* slice
			// rather than the caller's, which is the one index-aligned with
			// AffectedPKs. *Many delete/restore ops carry nil since
			// the PK already travels via Event.PK; *Where ops and single-op
			// mutations keep mc.Input unchanged.
			var (
				batchCreateInputs []*CreateOrderItemInput
				batchUpdateItems  []UpdateOrderItemItem
			)
			switch mc.Op {
			case hook.OpCreateMany, hook.OpUpsertMany:
				batchCreateInputs, _ = mc.Input.([]*CreateOrderItemInput)
			case hook.OpUpdateMany:
				batchUpdateItems, _ = mc.Input.([]UpdateOrderItemItem)
			}
			for i, pk := range mc.AffectedPKs {
				var inputVal any
				switch mc.Op {
				case hook.OpCreateMany, hook.OpUpsertMany:
					if i < len(batchCreateInputs) {
						inputVal = batchCreateInputs[i]
					}
				case hook.OpUpdateMany:
					if i < len(batchUpdateItems) {
						inputVal = batchUpdateItems[i]
					}
				case hook.OpHardDeleteMany, hook.OpSoftDeleteMany, hook.OpRestoreMany:
					// Per-entity input is nil — the PK already travels via Event.PK.
				default:
					inputVal = mc.Input
				}
				events[i] = event.Event{
					ID:        uuid.NewV4().String(),
					Table:     "order_items",
					Schema:    mc.Schema,
					Action:    mapOpToAction(mc.Op),
					PK:        pk,
					Input:     inputVal,
					Timestamp: time.Now(),
					Metadata:  mergeEventMetadata(baseMeta, nil),
				}
			}

			publish := func(ctx context.Context) error {
				if err := publisher.PublishBatch(ctx, events); err != nil {
					onError(ctx, events, err)
				}
				return nil
			}

			if tx := database.FromContext(ctx); tx != nil {
				tx.OnCommit(publish)
			} else {
				publish(ctx)
			}

			return result, nil
		}
	}
}

// newProductEventHook creates a mutation hook that publishes events for Product mutations.
func newProductEventHook(publisher event.Publisher, onError func(ctx context.Context, events []event.Event, err error), metaFunc func(ctx context.Context) map[string]string) hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, mc *hook.MutationContext) (any, error) {
			result, err := next(ctx, mc)
			if err != nil {
				return result, err
			}

			// Check SkipEvents via CallOptions
			if skipper, ok := mc.CallOptions.(eventSkipper); ok && skipper.skipEvents() {
				return result, nil
			}

			if len(mc.AffectedPKs) == 0 {
				return result, nil
			}

			// MetadataFunc: resolve consumer metadata
			// once here at hook entry, where the request ctx is still live —
			// never from the deferred OnCommit callback, which runs on
			// context.Background(). The result is merged into
			// each fanned-out event below; the system tenant stamp is applied
			// last so a consumer cannot override it.
			var baseMeta map[string]string
			if metaFunc != nil {
				baseMeta = metaFunc(ctx)
			}

			events := make([]event.Event, len(mc.AffectedPKs))

			// Per-entity Input fanout. For batch ops the i-th
			// fanned-out event carries the i-th element of the published
			// input slice — keeps wire cost O(N) on serialization and lets
			// subscribers run one type-switch across single-op and batch
			// shapes uniformly. UpsertMany publishes the *deduped* slice
			// rather than the caller's, which is the one index-aligned with
			// AffectedPKs. *Many delete/restore ops carry nil since
			// the PK already travels via Event.PK; *Where ops and single-op
			// mutations keep mc.Input unchanged.
			var (
				batchCreateInputs []*CreateProductInput
				batchUpdateItems  []UpdateProductItem
			)
			switch mc.Op {
			case hook.OpCreateMany, hook.OpUpsertMany:
				batchCreateInputs, _ = mc.Input.([]*CreateProductInput)
			case hook.OpUpdateMany:
				batchUpdateItems, _ = mc.Input.([]UpdateProductItem)
			}
			for i, pk := range mc.AffectedPKs {
				var inputVal any
				switch mc.Op {
				case hook.OpCreateMany, hook.OpUpsertMany:
					if i < len(batchCreateInputs) {
						inputVal = batchCreateInputs[i]
					}
				case hook.OpUpdateMany:
					if i < len(batchUpdateItems) {
						inputVal = batchUpdateItems[i]
					}
				case hook.OpHardDeleteMany, hook.OpSoftDeleteMany, hook.OpRestoreMany:
					// Per-entity input is nil — the PK already travels via Event.PK.
				default:
					inputVal = mc.Input
				}
				events[i] = event.Event{
					ID:        uuid.NewV4().String(),
					Table:     "products",
					Schema:    mc.Schema,
					Action:    mapOpToAction(mc.Op),
					PK:        pk,
					Input:     inputVal,
					Timestamp: time.Now(),
					Metadata:  mergeEventMetadata(baseMeta, nil),
				}
			}

			publish := func(ctx context.Context) error {
				if err := publisher.PublishBatch(ctx, events); err != nil {
					onError(ctx, events, err)
				}
				return nil
			}

			if tx := database.FromContext(ctx); tx != nil {
				tx.OnCommit(publish)
			} else {
				publish(ctx)
			}

			return result, nil
		}
	}
}

// newProfileEventHook creates a mutation hook that publishes events for Profile mutations.
func newProfileEventHook(publisher event.Publisher, onError func(ctx context.Context, events []event.Event, err error), metaFunc func(ctx context.Context) map[string]string) hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, mc *hook.MutationContext) (any, error) {
			result, err := next(ctx, mc)
			if err != nil {
				return result, err
			}

			// Check SkipEvents via CallOptions
			if skipper, ok := mc.CallOptions.(eventSkipper); ok && skipper.skipEvents() {
				return result, nil
			}

			if len(mc.AffectedPKs) == 0 {
				return result, nil
			}

			// MetadataFunc: resolve consumer metadata
			// once here at hook entry, where the request ctx is still live —
			// never from the deferred OnCommit callback, which runs on
			// context.Background(). The result is merged into
			// each fanned-out event below; the system tenant stamp is applied
			// last so a consumer cannot override it.
			var baseMeta map[string]string
			if metaFunc != nil {
				baseMeta = metaFunc(ctx)
			}

			events := make([]event.Event, len(mc.AffectedPKs))

			// Per-entity Input fanout. For batch ops the i-th
			// fanned-out event carries the i-th element of the published
			// input slice — keeps wire cost O(N) on serialization and lets
			// subscribers run one type-switch across single-op and batch
			// shapes uniformly. UpsertMany publishes the *deduped* slice
			// rather than the caller's, which is the one index-aligned with
			// AffectedPKs. *Many delete/restore ops carry nil since
			// the PK already travels via Event.PK; *Where ops and single-op
			// mutations keep mc.Input unchanged.
			var (
				batchCreateInputs []*CreateProfileInput
				batchUpdateItems  []UpdateProfileItem
			)
			switch mc.Op {
			case hook.OpCreateMany, hook.OpUpsertMany:
				batchCreateInputs, _ = mc.Input.([]*CreateProfileInput)
			case hook.OpUpdateMany:
				batchUpdateItems, _ = mc.Input.([]UpdateProfileItem)
			}
			for i, pk := range mc.AffectedPKs {
				var inputVal any
				switch mc.Op {
				case hook.OpCreateMany, hook.OpUpsertMany:
					if i < len(batchCreateInputs) {
						inputVal = batchCreateInputs[i]
					}
				case hook.OpUpdateMany:
					if i < len(batchUpdateItems) {
						inputVal = batchUpdateItems[i]
					}
				case hook.OpHardDeleteMany, hook.OpSoftDeleteMany, hook.OpRestoreMany:
					// Per-entity input is nil — the PK already travels via Event.PK.
				default:
					inputVal = mc.Input
				}
				events[i] = event.Event{
					ID:        uuid.NewV4().String(),
					Table:     "profiles",
					Schema:    mc.Schema,
					Action:    mapOpToAction(mc.Op),
					PK:        pk,
					Input:     inputVal,
					Timestamp: time.Now(),
					Metadata:  mergeEventMetadata(baseMeta, nil),
				}
			}

			publish := func(ctx context.Context) error {
				if err := publisher.PublishBatch(ctx, events); err != nil {
					onError(ctx, events, err)
				}
				return nil
			}

			if tx := database.FromContext(ctx); tx != nil {
				tx.OnCommit(publish)
			} else {
				publish(ctx)
			}

			return result, nil
		}
	}
}

// newUserEventHook creates a mutation hook that publishes events for User mutations.
func newUserEventHook(publisher event.Publisher, onError func(ctx context.Context, events []event.Event, err error), metaFunc func(ctx context.Context) map[string]string) hook.MutationHook {
	return func(next hook.MutationHandler) hook.MutationHandler {
		return func(ctx context.Context, mc *hook.MutationContext) (any, error) {
			result, err := next(ctx, mc)
			if err != nil {
				return result, err
			}

			// Check SkipEvents via CallOptions
			if skipper, ok := mc.CallOptions.(eventSkipper); ok && skipper.skipEvents() {
				return result, nil
			}

			if len(mc.AffectedPKs) == 0 {
				return result, nil
			}

			// MetadataFunc: resolve consumer metadata
			// once here at hook entry, where the request ctx is still live —
			// never from the deferred OnCommit callback, which runs on
			// context.Background(). The result is merged into
			// each fanned-out event below; the system tenant stamp is applied
			// last so a consumer cannot override it.
			var baseMeta map[string]string
			if metaFunc != nil {
				baseMeta = metaFunc(ctx)
			}

			events := make([]event.Event, len(mc.AffectedPKs))

			// Per-entity Input fanout. For batch ops the i-th
			// fanned-out event carries the i-th element of the published
			// input slice — keeps wire cost O(N) on serialization and lets
			// subscribers run one type-switch across single-op and batch
			// shapes uniformly. UpsertMany publishes the *deduped* slice
			// rather than the caller's, which is the one index-aligned with
			// AffectedPKs. *Many delete/restore ops carry nil since
			// the PK already travels via Event.PK; *Where ops and single-op
			// mutations keep mc.Input unchanged.
			var (
				batchCreateInputs []*CreateUserInput
				batchUpdateItems  []UpdateUserItem
			)
			switch mc.Op {
			case hook.OpCreateMany, hook.OpUpsertMany:
				batchCreateInputs, _ = mc.Input.([]*CreateUserInput)
			case hook.OpUpdateMany:
				batchUpdateItems, _ = mc.Input.([]UpdateUserItem)
			}
			for i, pk := range mc.AffectedPKs {
				var inputVal any
				switch mc.Op {
				case hook.OpCreateMany, hook.OpUpsertMany:
					if i < len(batchCreateInputs) {
						inputVal = batchCreateInputs[i]
					}
				case hook.OpUpdateMany:
					if i < len(batchUpdateItems) {
						inputVal = batchUpdateItems[i]
					}
				case hook.OpHardDeleteMany, hook.OpSoftDeleteMany, hook.OpRestoreMany:
					// Per-entity input is nil — the PK already travels via Event.PK.
				default:
					inputVal = mc.Input
				}
				events[i] = event.Event{
					ID:        uuid.NewV4().String(),
					Table:     "users",
					Schema:    mc.Schema,
					Action:    mapOpToAction(mc.Op),
					PK:        pk,
					Input:     inputVal,
					Timestamp: time.Now(),
					Metadata:  mergeEventMetadata(baseMeta, nil),
				}
			}

			publish := func(ctx context.Context) error {
				if err := publisher.PublishBatch(ctx, events); err != nil {
					onError(ctx, events, err)
				}
				return nil
			}

			if tx := database.FromContext(ctx); tx != nil {
				tx.OnCommit(publish)
			} else {
				publish(ctx)
			}

			return result, nil
		}
	}
}

// buildEventHooks creates per-entity event hooks scoped via hook.ForTable.
func buildEventHooks(publisher event.Publisher, cfg event.Config) []hook.MutationHook {
	onError := cfg.ResolveOnError()
	metaFunc := cfg.MetadataFunc
	return []hook.MutationHook{
		hook.ForTable(newArticleEventHook(publisher, onError, metaFunc), TableArticles),
		hook.ForTable(newAuditLogEventHook(publisher, onError, metaFunc), TableAuditLogs),
		hook.ForTable(newOrderItemEventHook(publisher, onError, metaFunc), TableOrderItems),
		hook.ForTable(newProductEventHook(publisher, onError, metaFunc), TableProducts),
		hook.ForTable(newProfileEventHook(publisher, onError, metaFunc), TableProfiles),
		hook.ForTable(newUserEventHook(publisher, onError, metaFunc), TableUsers),
	}
}

// WithEventPublisher configures event publishing for all mutations.
// Event hooks are prepended to the mutation hook chain as the outermost hooks
// (after panic recovery). Events are deferred via Tx.OnCommit inside transactions
// and fire immediately outside transactions. Publish failures invoke OnError but
// never fail the mutation.
func WithEventPublisher(publisher event.Publisher, opts ...func(*event.Config)) ClientOption {
	return func(o *clientOptions) {
		o.eventPublisher = publisher
		for _, opt := range opts {
			opt(&o.eventConfig)
		}
	}
}
