package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models/graph/model"
)

// CategoryPriceTotal is the resolver for the categoryPriceTotal field.
func (r *queryResolver) CategoryPriceTotal(ctx context.Context, categoryID int) (*models.CategoryPriceTotal, error) {
	return r.Q.CategoryPriceTotal(ctx, categoryID)
}

// CategoryPriceTotals is the resolver for the categoryPriceTotals field.
func (r *queryResolver) CategoryPriceTotals(ctx context.Context, filter *gqlmodel.CategoryPriceTotalFilter, first *int, after *string, last *int, before *string) (*models.Connection[models.CategoryPriceTotal], error) {
	return r.Q.CategoryPriceTotals(ctx, translateCategoryPriceTotalFilter(filter), first, after, last, before)
}

// CategoryPriceTotalList is the resolver for the categoryPriceTotalList field.
func (r *queryResolver) CategoryPriceTotalList(ctx context.Context, filter *gqlmodel.CategoryPriceTotalFilter, sort []*gqlmodel.CategoryPriceTotalSort, limit *int, offset *int) (*models.PaginateResult[models.CategoryPriceTotal], error) {
	return r.Q.CategoryPriceTotalList(ctx, translateCategoryPriceTotalFilter(filter), translateCategoryPriceTotalSort(sort), limit, offset)
}
