package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	uuid1 "uuid"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models/graph/model"
	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models/graph/sqlgenresolver"
)

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input gqlmodel.CreateEventInput) (*models.Event, error) {
	return r.M.CreateEvent(ctx, translateCreateEventInput(input))
}

// CreateEvents is the resolver for the createEvents field.
func (r *mutationResolver) CreateEvents(ctx context.Context, inputs []*gqlmodel.CreateEventInput) ([]*models.Event, error) {
	xs := make([]*models.CreateEventInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateEventInput(*in))
	}
	return r.M.CreateEvents(ctx, xs)
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id uuid1.UUID, input gqlmodel.UpdateEventInput) (*models.Event, error) {
	if input.Adjustment != nil && input.AdjustmentInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update events: column \"adjustment\" cannot be both set and incremented in one mutation")
	}
	if input.AdjustmentInc != nil && input.AdjustmentDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update events: column \"adjustment\" cannot be both incremented and decremented in one mutation")
	}
	setIn := translateUpdateEventInput(input)
	hasSet := hasUpdateEventSetFields(input)
	var incOps []sqlgenresolver.IncrementOp[models.EventIncrementColumn]
	if input.AdjustmentInc != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[models.EventIncrementColumn]{
			Column: models.EventIncrementAdjustment,
			Amount: int(*input.AdjustmentInc),
		})
	}
	if input.AdjustmentDec != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[models.EventIncrementColumn]{
			Column: models.EventIncrementAdjustment,
			Amount: -int(*input.AdjustmentDec),
		})
	}
	return r.M.UpdateEvent(ctx, id, setIn, hasSet, incOps)
}

// UpdateEvents is the resolver for the updateEvents field.
func (r *mutationResolver) UpdateEvents(ctx context.Context, filter gqlmodel.EventFilter, input gqlmodel.UpdateEventInput) ([]*models.Event, error) {
	if input.Adjustment != nil && input.AdjustmentInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update events: column \"adjustment\" cannot be both set and incremented in one mutation")
	}
	if input.AdjustmentInc != nil && input.AdjustmentDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update events: column \"adjustment\" cannot be both incremented and decremented in one mutation")
	}
	return r.M.UpdateEvents(ctx, translateEventFilter(&filter), translateUpdateEventInput(input))
}

// UpsertEvent is the resolver for the upsertEvent field.
func (r *mutationResolver) UpsertEvent(ctx context.Context, input gqlmodel.CreateEventInput) (*models.Event, error) {
	return r.M.UpsertEvent(ctx, translateCreateEventInput(input))
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id uuid1.UUID) (bool, error) {
	return r.M.DeleteEvent(ctx, id)
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id uuid1.UUID) (*models.Event, error) {
	return r.Q.Event(ctx, id)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *gqlmodel.EventFilter, first *int, after *string, last *int, before *string) (*models.Connection[models.Event], error) {
	return r.Q.Events(ctx, translateEventFilter(filter), first, after, last, before)
}

// EventList is the resolver for the eventList field.
func (r *queryResolver) EventList(ctx context.Context, filter *gqlmodel.EventFilter, sort []*gqlmodel.EventSort, limit *int, offset *int) (*models.PaginateResult[models.Event], error) {
	return r.Q.EventList(ctx, translateEventFilter(filter), translateEventSort(sort), limit, offset)
}
