// Code generated by sqlgen dev. DO NOT EDIT.
package graph

import (
	"net"
	"time"

	"github.com/teandresmith/sqlgen/comparator"

	models "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql/models/graph/model"
)

// Per-family comparator translators. These are shared across
// the whole project (one impl per family variant, regardless of how many
// tables reference it) and are dispatched into by the per-table filter
// translators in filter_translate_gen.go.
//
// Numeric variants are emitted per Go T parameter (e.g.
// translateNumericComparatorInt32, translateNumericComparatorFloat64). The
// gqlgen-generated NumericComparator carries float64-typed fields (the
// GraphQL `Float` scalar binds to Go `float64`); each variant casts to its
// underlying T so the resulting *comparator.Number[T] matches the model
// filter's column type exactly.
//
// Nullable variants take their own Nullable<X>Comparator input, not the base
// one — GraphQL input types are global, so `isNull` cannot be a conditional
// field on a shared input and nullability has to be a separate type.
// They therefore copy the operands themselves rather than
// delegating to the base translator: the two functions no longer accept the
// same Go type. The operand block is identical text either way because
// comparator.Nullable<X> embeds <X>, so Go promotes the field assignments.
// `isNull` lands in the wrapper's `Null *bool`, giving IS NULL / IS NOT NULL
// a reachable path from the API surface.
//
// The `Custom []sql.Condition` field every family carries is deliberately
// never populated here — it is a raw-SQL escape hatch, and exposing it over
// HTTP would be an injection surface.

// translateBooleanComparator translates a GraphQL BooleanComparator into a
// *comparator.Bool for the model layer's filter struct.
func translateBooleanComparator(in *gqlmodel.BooleanComparator) *comparator.Bool {
	if in == nil {
		return nil
	}
	out := &comparator.Bool{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	return out
}

// translateBooleanSliceComparator translates a GraphQL BooleanSliceComparator into a
// *comparator.Slice[bool] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// No conversion is needed: gqlgen's element type for
// `[Boolean!]` is already bool.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateBooleanSliceComparator(in *gqlmodel.BooleanSliceComparator) *comparator.Slice[bool] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[bool]{}
	if len(in.ContainsAny) > 0 {
		out.ContainsAny = append([]bool(nil), in.ContainsAny...)
	}
	if len(in.ContainsAll) > 0 {
		out.ContainsAll = append([]bool(nil), in.ContainsAll...)
	}
	if len(in.ContainedBy) > 0 {
		out.ContainedBy = append([]bool(nil), in.ContainedBy...)
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateBytesComparator translates a GraphQL BytesComparator into a
// *comparator.Opaque[[]byte] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us []byte, which is already nilable
// and so arrives unwrapped. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateBytesComparator(in *gqlmodel.BytesComparator) *comparator.Opaque[[]byte] {
	if in == nil {
		return nil
	}
	out := &comparator.Opaque[[]byte]{}
	if in.Eq != nil {
		v := in.Eq
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte
		out.Lte = &v
	}
	if len(in.In) > 0 {
		out.In = append([][]byte(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([][]byte(nil), in.Nin...)
	}
	return out
}

// translateCIDRComparator translates a GraphQL CIDRComparator into a
// *comparator.Opaque[net.IPNet] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us *net.IPNet, which assigns straight onto
// the comparator's own pointer field. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateCIDRComparator(in *gqlmodel.CIDRComparator) *comparator.Opaque[net.IPNet] {
	if in == nil {
		return nil
	}
	out := &comparator.Opaque[net.IPNet]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]net.IPNet, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]net.IPNet, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	return out
}

// translateDecimalComparator translates a GraphQL DecimalComparator into a
// *comparator.String for the model layer's filter struct.
//
// Decimal columns filter through comparator.String on the canonical string
// form — decimal.Decimal does not satisfy comparator.Numeric — so
// each Decimal-typed operand is rendered with String(). The ordered
// operators stay numerically correct because the parameter is compared
// against a numeric column: the database coerces it, rather than collating
// it as text.
func translateDecimalComparator(in *gqlmodel.DecimalComparator) *comparator.String {
	if in == nil {
		return nil
	}
	out := &comparator.String{}
	if in.Eq != nil {
		v := in.Eq.String()
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq.String()
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt.String()
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte.String()
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt.String()
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte.String()
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]string, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]string, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.Nin = xs
	}
	return out
}

// translateDocumentEntityTypeEnumComparator translates a GraphQL DocumentEntityTypeEnumComparator into a
// *comparator.Enum[models.DocumentEntityTypeEnum] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to models.DocumentEntityTypeEnum itself, so the values arrive as
// the model comparator's own type parameter.
func translateDocumentEntityTypeEnumComparator(in *gqlmodel.DocumentEntityTypeEnumComparator) *comparator.Enum[models.DocumentEntityTypeEnum] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[models.DocumentEntityTypeEnum]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]models.DocumentEntityTypeEnum(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]models.DocumentEntityTypeEnum(nil), in.Nin...)
	}
	return out
}

// translateDocumentEntityTypeEnumSliceComparator translates a GraphQL DocumentEntityTypeEnumSliceComparator into a
// *comparator.Slice[models.DocumentEntityTypeEnum] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// No conversion is needed: gqlgen's element type for
// `[DocumentEntityTypeEnum!]` is already models.DocumentEntityTypeEnum.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateDocumentEntityTypeEnumSliceComparator(in *gqlmodel.DocumentEntityTypeEnumSliceComparator) *comparator.Slice[models.DocumentEntityTypeEnum] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[models.DocumentEntityTypeEnum]{}
	if len(in.ContainsAny) > 0 {
		out.ContainsAny = append([]models.DocumentEntityTypeEnum(nil), in.ContainsAny...)
	}
	if len(in.ContainsAll) > 0 {
		out.ContainsAll = append([]models.DocumentEntityTypeEnum(nil), in.ContainsAll...)
	}
	if len(in.ContainedBy) > 0 {
		out.ContainedBy = append([]models.DocumentEntityTypeEnum(nil), in.ContainedBy...)
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateDurationComparator translates a GraphQL DurationComparator into a
// *comparator.Number[time.Duration] for the model layer's filter struct.
//
// A duration column's model comparator IS comparator.Number[time.Duration] —
// time.Duration is ~int64, so it satisfies comparator.Numeric — but its
// operands bind to the Duration scalar rather than to Float, which is what
// gives it an input type of its own instead of collapsing into
// NumericComparator. gqlgen therefore hands us
// time.Duration directly and the conversions below are identities. The value
// reaches the driver as a duration, so the ordered and between operators
// compare intervals rather than nanosecond counts.
func translateDurationComparator(in *gqlmodel.DurationComparator) *comparator.Number[time.Duration] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[time.Duration]{}
	if in.Eq != nil {
		v := time.Duration(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := time.Duration(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := time.Duration(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := time.Duration(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := time.Duration(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := time.Duration(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]time.Duration, len(in.In))
		for i, v := range in.In {
			xs[i] = time.Duration(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Duration, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = time.Duration(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Duration]{
			Start: time.Duration(in.Between.From),
			End:   time.Duration(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Duration]{
			Start: time.Duration(in.Nbetween.From),
			End:   time.Duration(in.Nbetween.To),
		}
	}
	return out
}

// translateFloatSliceComparator translates a GraphQL FloatSliceComparator into a
// *comparator.Slice[float64] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// No conversion is needed: gqlgen's element type for
// `[Float!]` is already float64.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateFloatSliceComparator(in *gqlmodel.FloatSliceComparator) *comparator.Slice[float64] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[float64]{}
	if len(in.ContainsAny) > 0 {
		out.ContainsAny = append([]float64(nil), in.ContainsAny...)
	}
	if len(in.ContainsAll) > 0 {
		out.ContainsAll = append([]float64(nil), in.ContainsAll...)
	}
	if len(in.ContainedBy) > 0 {
		out.ContainedBy = append([]float64(nil), in.ContainedBy...)
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateFloatSliceComparatorFloat32 translates a GraphQL FloatSliceComparator into a
// *comparator.Slice[float32] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// The input is keyed on the ELEMENT's GraphQL type and this function on its Go
// type, so every width binding to `Float` shares one
// FloatSliceComparator and each element converts into
// float32 — the same split NumericComparator carries, for the same
// reason.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateFloatSliceComparatorFloat32(in *gqlmodel.FloatSliceComparator) *comparator.Slice[float32] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[float32]{}
	if len(in.ContainsAny) > 0 {
		xs := make([]float32, len(in.ContainsAny))
		for i, v := range in.ContainsAny {
			xs[i] = float32(v)
		}
		out.ContainsAny = xs
	}
	if len(in.ContainsAll) > 0 {
		xs := make([]float32, len(in.ContainsAll))
		for i, v := range in.ContainsAll {
			xs[i] = float32(v)
		}
		out.ContainsAll = xs
	}
	if len(in.ContainedBy) > 0 {
		xs := make([]float32, len(in.ContainedBy))
		for i, v := range in.ContainedBy {
			xs[i] = float32(v)
		}
		out.ContainedBy = xs
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateIDComparator translates a GraphQL IDComparator into a
// *comparator.ID for the model layer's filter struct.
func translateIDComparator(in *gqlmodel.IDComparator) *comparator.ID {
	if in == nil {
		return nil
	}
	out := &comparator.ID{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	return out
}

// translateIPComparator translates a GraphQL IPComparator into a
// *comparator.Opaque[net.IP] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us net.IP, which is already nilable
// and so arrives unwrapped. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateIPComparator(in *gqlmodel.IPComparator) *comparator.Opaque[net.IP] {
	if in == nil {
		return nil
	}
	out := &comparator.Opaque[net.IP]{}
	if in.Eq != nil {
		v := in.Eq
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte
		out.Lte = &v
	}
	if len(in.In) > 0 {
		out.In = append([]net.IP(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]net.IP(nil), in.Nin...)
	}
	return out
}

// translateIntSliceComparatorInt16 translates a GraphQL IntSliceComparator into a
// *comparator.Slice[int16] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// The input is keyed on the ELEMENT's GraphQL type and this function on its Go
// type, so every width binding to `Int` shares one
// IntSliceComparator and each element converts into
// int16 — the same split NumericComparator carries, for the same
// reason.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateIntSliceComparatorInt16(in *gqlmodel.IntSliceComparator) *comparator.Slice[int16] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[int16]{}
	if len(in.ContainsAny) > 0 {
		xs := make([]int16, len(in.ContainsAny))
		for i, v := range in.ContainsAny {
			xs[i] = int16(v)
		}
		out.ContainsAny = xs
	}
	if len(in.ContainsAll) > 0 {
		xs := make([]int16, len(in.ContainsAll))
		for i, v := range in.ContainsAll {
			xs[i] = int16(v)
		}
		out.ContainsAll = xs
	}
	if len(in.ContainedBy) > 0 {
		xs := make([]int16, len(in.ContainedBy))
		for i, v := range in.ContainedBy {
			xs[i] = int16(v)
		}
		out.ContainedBy = xs
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateIntSliceComparatorInt32 translates a GraphQL IntSliceComparator into a
// *comparator.Slice[int32] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// The input is keyed on the ELEMENT's GraphQL type and this function on its Go
// type, so every width binding to `Int` shares one
// IntSliceComparator and each element converts into
// int32 — the same split NumericComparator carries, for the same
// reason.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateIntSliceComparatorInt32(in *gqlmodel.IntSliceComparator) *comparator.Slice[int32] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[int32]{}
	if len(in.ContainsAny) > 0 {
		xs := make([]int32, len(in.ContainsAny))
		for i, v := range in.ContainsAny {
			xs[i] = int32(v)
		}
		out.ContainsAny = xs
	}
	if len(in.ContainsAll) > 0 {
		xs := make([]int32, len(in.ContainsAll))
		for i, v := range in.ContainsAll {
			xs[i] = int32(v)
		}
		out.ContainsAll = xs
	}
	if len(in.ContainedBy) > 0 {
		xs := make([]int32, len(in.ContainedBy))
		for i, v := range in.ContainedBy {
			xs[i] = int32(v)
		}
		out.ContainedBy = xs
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateIntSliceComparatorInt64 translates a GraphQL IntSliceComparator into a
// *comparator.Slice[int64] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// The input is keyed on the ELEMENT's GraphQL type and this function on its Go
// type, so every width binding to `Int` shares one
// IntSliceComparator and each element converts into
// int64 — the same split NumericComparator carries, for the same
// reason.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateIntSliceComparatorInt64(in *gqlmodel.IntSliceComparator) *comparator.Slice[int64] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[int64]{}
	if len(in.ContainsAny) > 0 {
		xs := make([]int64, len(in.ContainsAny))
		for i, v := range in.ContainsAny {
			xs[i] = int64(v)
		}
		out.ContainsAny = xs
	}
	if len(in.ContainsAll) > 0 {
		xs := make([]int64, len(in.ContainsAll))
		for i, v := range in.ContainsAll {
			xs[i] = int64(v)
		}
		out.ContainsAll = xs
	}
	if len(in.ContainedBy) > 0 {
		xs := make([]int64, len(in.ContainedBy))
		for i, v := range in.ContainedBy {
			xs[i] = int64(v)
		}
		out.ContainedBy = xs
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateJSONBComparator translates a GraphQL JSONBComparator into a
// *comparator.JSONB for the model layer's filter struct.
//
// PostgreSQL-only, which needs no switch here:
// resolveSimpleComparator resolves a column to comparator.JSONB only under the
// postgres dialect, so nothing off it can reach this translator. The document
// operands are typed with the `JSON` scalar, as the JSON family's are.
func translateJSONBComparator(in *gqlmodel.JSONBComparator) *comparator.JSONB {
	if in == nil {
		return nil
	}
	out := &comparator.JSONB{}
	if in.HasKey != nil {
		out.HasKey = in.HasKey
	}
	if len(in.HasAnyKey) > 0 {
		out.HasAnyKey = append([]string(nil), in.HasAnyKey...)
	}
	if len(in.HasAllKeys) > 0 {
		out.HasAllKeys = append([]string(nil), in.HasAllKeys...)
	}
	if in.Contains != nil {
		v := any(string(in.Contains))
		out.Contains = &v
	}
	if in.ContainedBy != nil {
		v := any(string(in.ContainedBy))
		out.ContainedBy = &v
	}
	if in.PathExists != nil {
		out.PathExists = in.PathExists
	}
	return out
}

// translateMacAddrComparator translates a GraphQL MacAddrComparator into a
// *comparator.Opaque[net.HardwareAddr] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us net.HardwareAddr, which is already nilable
// and so arrives unwrapped. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateMacAddrComparator(in *gqlmodel.MacAddrComparator) *comparator.Opaque[net.HardwareAddr] {
	if in == nil {
		return nil
	}
	out := &comparator.Opaque[net.HardwareAddr]{}
	if in.Eq != nil {
		v := in.Eq
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte
		out.Lte = &v
	}
	if len(in.In) > 0 {
		out.In = append([]net.HardwareAddr(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]net.HardwareAddr(nil), in.Nin...)
	}
	return out
}

// translateNullableBooleanComparator translates a GraphQL NullableBooleanComparator into a
// *comparator.NullableBool for the model layer's filter struct.
func translateNullableBooleanComparator(in *gqlmodel.NullableBooleanComparator) *comparator.NullableBool {
	if in == nil {
		return nil
	}
	out := &comparator.NullableBool{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableBytesComparator translates a GraphQL NullableBytesComparator into a
// *comparator.NullableOpaque[[]byte] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us []byte, which is already nilable
// and so arrives unwrapped. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateNullableBytesComparator(in *gqlmodel.NullableBytesComparator) *comparator.NullableOpaque[[]byte] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableOpaque[[]byte]{}
	if in.Eq != nil {
		v := in.Eq
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte
		out.Lte = &v
	}
	if len(in.In) > 0 {
		out.In = append([][]byte(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([][]byte(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableCIDRComparator translates a GraphQL NullableCIDRComparator into a
// *comparator.NullableOpaque[net.IPNet] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us *net.IPNet, which assigns straight onto
// the comparator's own pointer field. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateNullableCIDRComparator(in *gqlmodel.NullableCIDRComparator) *comparator.NullableOpaque[net.IPNet] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableOpaque[net.IPNet]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]net.IPNet, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]net.IPNet, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableDecimalComparator translates a GraphQL NullableDecimalComparator into a
// *comparator.NullableString for the model layer's filter struct.
//
// Decimal columns filter through comparator.String on the canonical string
// form — decimal.Decimal does not satisfy comparator.Numeric — so
// each Decimal-typed operand is rendered with String(). The ordered
// operators stay numerically correct because the parameter is compared
// against a numeric column: the database coerces it, rather than collating
// it as text.
func translateNullableDecimalComparator(in *gqlmodel.NullableDecimalComparator) *comparator.NullableString {
	if in == nil {
		return nil
	}
	out := &comparator.NullableString{}
	if in.Eq != nil {
		v := in.Eq.String()
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq.String()
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt.String()
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte.String()
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt.String()
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte.String()
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]string, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]string, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.Nin = xs
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableDocumentEntityTypeEnumComparator translates a GraphQL NullableDocumentEntityTypeEnumComparator into a
// *comparator.NullableEnum[models.DocumentEntityTypeEnum] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to models.DocumentEntityTypeEnum itself, so the values arrive as
// the model comparator's own type parameter.
func translateNullableDocumentEntityTypeEnumComparator(in *gqlmodel.NullableDocumentEntityTypeEnumComparator) *comparator.NullableEnum[models.DocumentEntityTypeEnum] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableEnum[models.DocumentEntityTypeEnum]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]models.DocumentEntityTypeEnum(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]models.DocumentEntityTypeEnum(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableDurationComparator translates a GraphQL NullableDurationComparator into a
// *comparator.NullableNumber[time.Duration] for the model layer's filter struct.
//
// A duration column's model comparator IS comparator.Number[time.Duration] —
// time.Duration is ~int64, so it satisfies comparator.Numeric — but its
// operands bind to the Duration scalar rather than to Float, which is what
// gives it an input type of its own instead of collapsing into
// NumericComparator. gqlgen therefore hands us
// time.Duration directly and the conversions below are identities. The value
// reaches the driver as a duration, so the ordered and between operators
// compare intervals rather than nanosecond counts.
func translateNullableDurationComparator(in *gqlmodel.NullableDurationComparator) *comparator.NullableNumber[time.Duration] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[time.Duration]{}
	if in.Eq != nil {
		v := time.Duration(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := time.Duration(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := time.Duration(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := time.Duration(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := time.Duration(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := time.Duration(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]time.Duration, len(in.In))
		for i, v := range in.In {
			xs[i] = time.Duration(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Duration, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = time.Duration(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Duration]{
			Start: time.Duration(in.Between.From),
			End:   time.Duration(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Duration]{
			Start: time.Duration(in.Nbetween.From),
			End:   time.Duration(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableIDComparator translates a GraphQL NullableIDComparator into a
// *comparator.NullableID for the model layer's filter struct.
func translateNullableIDComparator(in *gqlmodel.NullableIDComparator) *comparator.NullableID {
	if in == nil {
		return nil
	}
	out := &comparator.NullableID{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableIPComparator translates a GraphQL NullableIPComparator into a
// *comparator.NullableOpaque[net.IP] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us net.IP, which is already nilable
// and so arrives unwrapped. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateNullableIPComparator(in *gqlmodel.NullableIPComparator) *comparator.NullableOpaque[net.IP] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableOpaque[net.IP]{}
	if in.Eq != nil {
		v := in.Eq
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte
		out.Lte = &v
	}
	if len(in.In) > 0 {
		out.In = append([]net.IP(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]net.IP(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableIntSliceComparatorInt32 translates a GraphQL NullableIntSliceComparator into a
// *comparator.NullableSlice[int32] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// The input is keyed on the ELEMENT's GraphQL type and this function on its Go
// type, so every width binding to `Int` shares one
// IntSliceComparator and each element converts into
// int32 — the same split NumericComparator carries, for the same
// reason.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateNullableIntSliceComparatorInt32(in *gqlmodel.NullableIntSliceComparator) *comparator.NullableSlice[int32] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableSlice[int32]{}
	if len(in.ContainsAny) > 0 {
		xs := make([]int32, len(in.ContainsAny))
		for i, v := range in.ContainsAny {
			xs[i] = int32(v)
		}
		out.ContainsAny = xs
	}
	if len(in.ContainsAll) > 0 {
		xs := make([]int32, len(in.ContainsAll))
		for i, v := range in.ContainsAll {
			xs[i] = int32(v)
		}
		out.ContainsAll = xs
	}
	if len(in.ContainedBy) > 0 {
		xs := make([]int32, len(in.ContainedBy))
		for i, v := range in.ContainedBy {
			xs[i] = int32(v)
		}
		out.ContainedBy = xs
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableJSONBComparator translates a GraphQL NullableJSONBComparator into a
// *comparator.NullableJSONB for the model layer's filter struct.
//
// PostgreSQL-only, which needs no switch here:
// resolveSimpleComparator resolves a column to comparator.JSONB only under the
// postgres dialect, so nothing off it can reach this translator. The document
// operands are typed with the `JSON` scalar, as the JSON family's are.
func translateNullableJSONBComparator(in *gqlmodel.NullableJSONBComparator) *comparator.NullableJSONB {
	if in == nil {
		return nil
	}
	out := &comparator.NullableJSONB{}
	if in.HasKey != nil {
		out.HasKey = in.HasKey
	}
	if len(in.HasAnyKey) > 0 {
		out.HasAnyKey = append([]string(nil), in.HasAnyKey...)
	}
	if len(in.HasAllKeys) > 0 {
		out.HasAllKeys = append([]string(nil), in.HasAllKeys...)
	}
	if in.Contains != nil {
		v := any(string(in.Contains))
		out.Contains = &v
	}
	if in.ContainedBy != nil {
		v := any(string(in.ContainedBy))
		out.ContainedBy = &v
	}
	if in.PathExists != nil {
		out.PathExists = in.PathExists
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableJSONComparator translates a GraphQL NullableJSONComparator into a
// *comparator.NullableJSON for the model layer's filter struct.
//
// The document operands are typed with the `JSON` scalar the column's own
// field already declares, so a malformed document is rejected while
// unmarshaling instead of reaching the database as a cast error. The comparator
// holds them as `*any`; comparator.JSON.Parse switches on the dialect, so one
// input serves PostgreSQL's `col::jsonb @>` / `col::jsonb ?` and MySQL's
// JSON_CONTAINS / JSON_CONTAINS_PATH. `hasKey`'s operand is the
// exception the shared input does not normalize: a bare key on PostgreSQL, a
// JSON path on MySQL.
func translateNullableJSONComparator(in *gqlmodel.NullableJSONComparator) *comparator.NullableJSON {
	if in == nil {
		return nil
	}
	out := &comparator.NullableJSON{}
	if in.Contains != nil {
		v := any(string(in.Contains))
		out.Contains = &v
	}
	if in.HasKey != nil {
		out.HasKey = in.HasKey
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableMacAddrComparator translates a GraphQL NullableMacAddrComparator into a
// *comparator.NullableOpaque[net.HardwareAddr] for the model layer's filter struct.
//
// Operands are typed with the same scalar the column's own field declares, so
// no conversion is needed — gqlgen hands us net.HardwareAddr, which is already nilable
// and so arrives unwrapped. The value reaches the driver as the column's
// own Go type rather than as a text rendering of it, which is what makes the
// filter compare against a binary or network column correctly.
func translateNullableMacAddrComparator(in *gqlmodel.NullableMacAddrComparator) *comparator.NullableOpaque[net.HardwareAddr] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableOpaque[net.HardwareAddr]{}
	if in.Eq != nil {
		v := in.Eq
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte
		out.Lte = &v
	}
	if len(in.In) > 0 {
		out.In = append([]net.HardwareAddr(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]net.HardwareAddr(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorFloat32 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[float32] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into float32 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorFloat32(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[float32] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[float32]{}
	if in.Eq != nil {
		v := float32(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := float32(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := float32(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := float32(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := float32(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := float32(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]float32, len(in.In))
		for i, v := range in.In {
			xs[i] = float32(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]float32, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = float32(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[float32]{
			Start: float32(in.Between.From),
			End:   float32(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[float32]{
			Start: float32(in.Nbetween.From),
			End:   float32(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorFloat64 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[float64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into float64 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorFloat64(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[float64] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[float64]{}
	if in.Eq != nil {
		v := float64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := float64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := float64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := float64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := float64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := float64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]float64, len(in.In))
		for i, v := range in.In {
			xs[i] = float64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]float64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = float64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[float64]{
			Start: float64(in.Between.From),
			End:   float64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[float64]{
			Start: float64(in.Nbetween.From),
			End:   float64(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorInt16 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[int16] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int16 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorInt16(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[int16] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[int16]{}
	if in.Eq != nil {
		v := int16(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int16(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int16(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int16(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int16(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int16(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int16, len(in.In))
		for i, v := range in.In {
			xs[i] = int16(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int16, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int16(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int16]{
			Start: int16(in.Between.From),
			End:   int16(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int16]{
			Start: int16(in.Nbetween.From),
			End:   int16(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorInt32 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[int32] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int32 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorInt32(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[int32] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[int32]{}
	if in.Eq != nil {
		v := int32(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int32(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int32(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int32(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int32(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int32(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int32, len(in.In))
		for i, v := range in.In {
			xs[i] = int32(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int32, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int32(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int32]{
			Start: int32(in.Between.From),
			End:   int32(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int32]{
			Start: int32(in.Nbetween.From),
			End:   int32(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorInt64 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[int64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int64 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorInt64(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[int64] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[int64]{}
	if in.Eq != nil {
		v := int64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int64, len(in.In))
		for i, v := range in.In {
			xs[i] = int64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int64]{
			Start: int64(in.Between.From),
			End:   int64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int64]{
			Start: int64(in.Nbetween.From),
			End:   int64(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableStringComparator translates a GraphQL NullableStringComparator into a
// *comparator.NullableString for the model layer's filter struct.
func translateNullableStringComparator(in *gqlmodel.NullableStringComparator) *comparator.NullableString {
	if in == nil {
		return nil
	}
	out := &comparator.NullableString{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if in.Contains != nil {
		out.Contains = in.Contains
	}
	if in.StartsWith != nil {
		out.StartsWith = in.StartsWith
	}
	if in.EndsWith != nil {
		out.EndsWith = in.EndsWith
	}
	if in.Like != nil {
		out.Like = in.Like
	}
	if in.Nlike != nil {
		out.NLike = in.Nlike
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableStringSliceComparator translates a GraphQL NullableStringSliceComparator into a
// *comparator.NullableSlice[string] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// No conversion is needed: gqlgen's element type for
// `[String!]` is already string.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateNullableStringSliceComparator(in *gqlmodel.NullableStringSliceComparator) *comparator.NullableSlice[string] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableSlice[string]{}
	if len(in.ContainsAny) > 0 {
		out.ContainsAny = append([]string(nil), in.ContainsAny...)
	}
	if len(in.ContainsAll) > 0 {
		out.ContainsAll = append([]string(nil), in.ContainsAll...)
	}
	if len(in.ContainedBy) > 0 {
		out.ContainedBy = append([]string(nil), in.ContainedBy...)
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableTimeComparator translates a GraphQL NullableTimeComparator into a
// *comparator.NullableTime for the model layer's filter struct.
func translateNullableTimeComparator(in *gqlmodel.NullableTimeComparator) *comparator.NullableTime {
	if in == nil {
		return nil
	}
	out := &comparator.NullableTime{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]time.Time, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Time, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Time]{Start: in.Between.From, End: in.Between.To}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Time]{Start: in.Nbetween.From, End: in.Nbetween.To}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNumericComparatorFloat32 translates a GraphQL NumericComparator into a
// *comparator.Number[float32] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into float32 so the
// result matches the model filter's column type exactly.
func translateNumericComparatorFloat32(in *gqlmodel.NumericComparator) *comparator.Number[float32] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[float32]{}
	if in.Eq != nil {
		v := float32(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := float32(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := float32(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := float32(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := float32(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := float32(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]float32, len(in.In))
		for i, v := range in.In {
			xs[i] = float32(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]float32, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = float32(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[float32]{
			Start: float32(in.Between.From),
			End:   float32(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[float32]{
			Start: float32(in.Nbetween.From),
			End:   float32(in.Nbetween.To),
		}
	}
	return out
}

// translateNumericComparatorInt16 translates a GraphQL NumericComparator into a
// *comparator.Number[int16] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int16 so the
// result matches the model filter's column type exactly.
func translateNumericComparatorInt16(in *gqlmodel.NumericComparator) *comparator.Number[int16] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[int16]{}
	if in.Eq != nil {
		v := int16(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int16(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int16(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int16(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int16(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int16(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int16, len(in.In))
		for i, v := range in.In {
			xs[i] = int16(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int16, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int16(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int16]{
			Start: int16(in.Between.From),
			End:   int16(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int16]{
			Start: int16(in.Nbetween.From),
			End:   int16(in.Nbetween.To),
		}
	}
	return out
}

// translateNumericComparatorInt32 translates a GraphQL NumericComparator into a
// *comparator.Number[int32] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int32 so the
// result matches the model filter's column type exactly.
func translateNumericComparatorInt32(in *gqlmodel.NumericComparator) *comparator.Number[int32] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[int32]{}
	if in.Eq != nil {
		v := int32(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int32(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int32(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int32(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int32(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int32(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int32, len(in.In))
		for i, v := range in.In {
			xs[i] = int32(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int32, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int32(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int32]{
			Start: int32(in.Between.From),
			End:   int32(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int32]{
			Start: int32(in.Nbetween.From),
			End:   int32(in.Nbetween.To),
		}
	}
	return out
}

// translateNumericComparatorInt64 translates a GraphQL NumericComparator into a
// *comparator.Number[int64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int64 so the
// result matches the model filter's column type exactly.
func translateNumericComparatorInt64(in *gqlmodel.NumericComparator) *comparator.Number[int64] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[int64]{}
	if in.Eq != nil {
		v := int64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int64, len(in.In))
		for i, v := range in.In {
			xs[i] = int64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int64]{
			Start: int64(in.Between.From),
			End:   int64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int64]{
			Start: int64(in.Nbetween.From),
			End:   int64(in.Nbetween.To),
		}
	}
	return out
}

// translateStringComparator translates a GraphQL StringComparator into a
// *comparator.String for the model layer's filter struct.
func translateStringComparator(in *gqlmodel.StringComparator) *comparator.String {
	if in == nil {
		return nil
	}
	out := &comparator.String{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if in.Contains != nil {
		out.Contains = in.Contains
	}
	if in.StartsWith != nil {
		out.StartsWith = in.StartsWith
	}
	if in.EndsWith != nil {
		out.EndsWith = in.EndsWith
	}
	if in.Like != nil {
		out.Like = in.Like
	}
	if in.Nlike != nil {
		out.NLike = in.Nlike
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	return out
}

// translateStringSliceComparator translates a GraphQL StringSliceComparator into a
// *comparator.Slice[string] for the model layer's filter struct.
//
// PostgreSQL-only for the same structural reason the JSONB family is: only the
// gotype resolver's PostgreSQL array branch sets IsSlice, so no column on
// another dialect resolves to comparator.Slice at all.
//
// No conversion is needed: gqlgen's element type for
// `[String!]` is already string.
//
// `isEmpty` is a Boolean predicate on the array itself rather than an element
// operand, so it copies straight across whatever the element type is.
func translateStringSliceComparator(in *gqlmodel.StringSliceComparator) *comparator.Slice[string] {
	if in == nil {
		return nil
	}
	out := &comparator.Slice[string]{}
	if len(in.ContainsAny) > 0 {
		out.ContainsAny = append([]string(nil), in.ContainsAny...)
	}
	if len(in.ContainsAll) > 0 {
		out.ContainsAll = append([]string(nil), in.ContainsAll...)
	}
	if len(in.ContainedBy) > 0 {
		out.ContainedBy = append([]string(nil), in.ContainedBy...)
	}
	if in.IsEmpty != nil {
		out.IsEmpty = in.IsEmpty
	}
	return out
}

// translateTimeComparator translates a GraphQL TimeComparator into a
// *comparator.Time for the model layer's filter struct.
func translateTimeComparator(in *gqlmodel.TimeComparator) *comparator.Time {
	if in == nil {
		return nil
	}
	out := &comparator.Time{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]time.Time, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Time, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Time]{Start: in.Between.From, End: in.Between.To}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Time]{Start: in.Nbetween.From, End: in.Nbetween.To}
	}
	return out
}

// translateWorkspaceNoteKindEnumComparator translates a GraphQL WorkspaceNoteKindEnumComparator into a
// *comparator.Enum[models.WorkspaceNoteKindEnum] for the model layer's filter struct.
//
// Operands are typed with the bound GraphQL enum rather than with String, so
// an unknown member is rejected by the GraphQL parser before any resolver
// runs. No conversion is needed: the gqlgen `models:`
// merge binds that enum to models.WorkspaceNoteKindEnum itself, so the values arrive as
// the model comparator's own type parameter.
func translateWorkspaceNoteKindEnumComparator(in *gqlmodel.WorkspaceNoteKindEnumComparator) *comparator.Enum[models.WorkspaceNoteKindEnum] {
	if in == nil {
		return nil
	}
	out := &comparator.Enum[models.WorkspaceNoteKindEnum]{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if len(in.In) > 0 {
		out.In = append([]models.WorkspaceNoteKindEnum(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]models.WorkspaceNoteKindEnum(nil), in.Nin...)
	}
	return out
}
