package manifest_test

import (
	"encoding/json"
	"go/ast"
	goparser "go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/google/go-cmp/cmp"
)

// exampleManifestGlob matches every checked-in example tree that emits a
// manifest. Both halves this test compares are pipeline output regenerated by
// `make update-golden-e2e`, so a change to either the shared-types template or
// the conventions builder shows up here.
const exampleManifestGlob = "../testdata/examples/*/models/manifest/manifest_gen.json"

// TestCallOptionsFieldsMatchGeneratedStruct is the drift guard for
// conventions.call_options.fields — the sibling of the error_sentinels guard,
// and for the same reason: an agent reads the list to learn which knobs a call
// carries, so a name that resolves to nothing is worse than a missing one. The
// list it replaced advertised a `Tx` field the generated struct has never had,
// while omitting FieldOptions, SkipTenancy and Tenant — drift that survived
// precisely because nothing compared the two.
//
// Every manifest-emitting example tree is checked, which covers both states of
// the tenancy gate: a tenanted tree carries SkipTenancy and Tenant, an
// untenanted one carries neither. Declaration order is compared too, not just
// membership — the list is the struct's shape, and a reader expects the fields
// in the order they are declared.
func TestCallOptionsFieldsMatchGeneratedStruct(t *testing.T) {
	manifests, err := filepath.Glob(exampleManifestGlob)
	if err != nil {
		t.Fatalf("glob %s: %v", exampleManifestGlob, err)
	}
	if len(manifests) == 0 {
		t.Fatalf("no example manifests matched %s — the example trees moved", exampleManifestGlob)
	}

	sawTenanted, sawUntenanted := false, false
	for _, manifestPath := range manifests {
		// .../<tree>/models/manifest/manifest_gen.json → .../<tree>/models
		modelsDir := filepath.Dir(filepath.Dir(manifestPath))
		tree := filepath.Base(filepath.Dir(modelsDir))

		t.Run(tree, func(t *testing.T) {
			declared := callOptionsFieldsDeclaredIn(t, filepath.Join(modelsDir, "shared_types_gen.go"))
			if len(declared) == 0 {
				t.Fatalf("parsed no CallOptions fields out of %s/shared_types_gen.go — the template changed shape", modelsDir)
			}
			advertised := callOptionsFieldsAdvertisedIn(t, manifestPath)
			if diff := cmp.Diff(declared, advertised); diff != "" {
				t.Errorf("conventions.call_options.fields does not match the generated struct (-declared +advertised):\n%s", diff)
			}
		})

		switch {
		case slices.Contains(callOptionsFieldsAdvertisedIn(t, manifestPath), "Tenant"):
			sawTenanted = true
		default:
			sawUntenanted = true
		}
	}

	// Both arms of the gate must actually be exercised, or the guard silently
	// stops covering the conditional fields when an example tree is retired.
	if !sawTenanted {
		t.Error("no manifest-emitting example tree is tenanted; the SkipTenancy/Tenant arm of the gate is uncovered")
	}
	if !sawUntenanted {
		t.Error("every manifest-emitting example tree is tenanted; the tenancy-off arm of the gate is uncovered")
	}
}

// callOptionsFieldsDeclaredIn extracts the field names of the generated
// CallOptions[FO] struct, in declaration order.
func callOptionsFieldsDeclaredIn(t *testing.T, path string) []string {
	t.Helper()
	file, err := goparser.ParseFile(token.NewFileSet(), path, nil, goparser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	var out []string
	for _, decl := range file.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "CallOptions" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, f := range st.Fields.List {
				for _, name := range f.Names {
					out = append(out, name.Name)
				}
			}
		}
	}
	return out
}

// callOptionsFieldsAdvertisedIn reads conventions.call_options.fields out of an
// emitted manifest — the JSON as a consumer sees it, rather than the in-memory
// Document, so a change to the JSON tags shows up here too.
func callOptionsFieldsAdvertisedIn(t *testing.T, path string) []string {
	t.Helper()
	raw, err := os.ReadFile(path) //nolint:gosec // test helper, path comes from a constant glob over the checked-in testdata tree
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var doc struct {
		Conventions struct {
			CallOptions struct {
				Type   string   `json:"type"`
				Fields []string `json:"fields"`
			} `json:"call_options"`
		} `json:"conventions"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	if doc.Conventions.CallOptions.Type != "CallOptions" {
		t.Errorf("%s: conventions.call_options.type = %q, want %q", path, doc.Conventions.CallOptions.Type, "CallOptions")
	}
	return doc.Conventions.CallOptions.Fields
}
