package manifest_test

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/config"
	"github.com/teandresmith/sqlgen/cmd/sqlgen/manifest"
)

// Manifest-directory ownership regression suite. `sqlgen generate` used to
// RemoveAll <output.dir>/manifest/ on every run where the manifest is disabled
// — the default — guarding only that the path was contained in the output dir,
// never that sqlgen wrote it. Since output.dir itself defaults to "." (PRD
// §4.2), a consumer whose module root holds a manifest/ directory of their own
// lost it and its whole subtree on first run, silently. These tests pin the
// ownership gate PRD §30.3 calls for: the directory goes only "after a prior
// true".

// markdownOnlyManifest / jsonOnlyManifest produce single-anchor configs, so the
// removal path is exercised against each half of the ownership proof on its
// own rather than only against the both-formats default.
func markdownOnlyManifest() *config.ManifestConfig {
	m := fullManifestConfig(config.JSONLayoutSingle)
	m.Formats = []string{config.ManifestFormatMarkdown}
	m.EmbedInClient = new(false) // embed_in_client requires the json format
	return m
}

func jsonOnlyManifest() *config.ManifestConfig {
	m := fullManifestConfig(config.JSONLayoutSingle)
	m.Formats = []string{config.ManifestFormatJSON}
	return m
}

// seedDir writes files (relative paths → contents) under dir.
func seedDir(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, body := range files {
		target := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(target), 0o750); err != nil {
			t.Fatalf("seeding %s: %v", target, err)
		}
		if err := os.WriteFile(target, []byte(body), 0o600); err != nil {
			t.Fatalf("seeding %s: %v", target, err)
		}
	}
}

// TestCleanStale_UnownedManifestDirSurvives is the incident itself: a
// manifest/ directory sqlgen never wrote must survive a disabled-manifest
// generate, whatever it happens to contain.
func TestCleanStale_UnownedManifestDirSurvives(t *testing.T) {
	tests := []struct {
		name     string
		manifest *config.ManifestConfig
		seed     map[string]string
	}{
		{
			// The observed case: no manifest block at all — the default —
			// against this repository's own runtime manifest/ package.
			name:     "no manifest block, Go package named manifest",
			manifest: nil,
			seed: map[string]string{
				"load.go":            "package manifest\n",
				"types.go":           "package manifest\n",
				"internal/errors.go": "package internal\n",
			},
		},
		{
			name:     "explicitly disabled, user docs directory",
			manifest: &config.ManifestConfig{Enabled: new(false)},
			seed: map[string]string{
				"adr-001.md": "# Decision record\n",
				"README.md":  "# Manifest notes\n",
			},
		},
		{
			// A prior sqlgen manifest the consumer adopted by deleting the
			// Generator line, mirroring the breadcrumb disown rule.
			name:     "index disowned by dropping the generator line",
			manifest: &config.ManifestConfig{Enabled: new(false)},
			seed: map[string]string{
				"_index.md": "# models manifest\n\n- **Dialect:** postgres\n",
				"user.md":   "# hand-maintained\n",
			},
		},
		{
			name:     "json written by some other generator",
			manifest: &config.ManifestConfig{Enabled: new(false)},
			seed: map[string]string{
				"manifest_gen.json": `{"generator":{"name":"othergen","version":"1.0.0"}}`,
			},
		},
		{
			name:     "json that is not even json",
			manifest: &config.ManifestConfig{Enabled: new(false)},
			seed:     map[string]string{"manifest_gen.json": "not json at all"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			manifestDir := filepath.Join(dir, "manifest")
			seedDir(t, manifestDir, tt.seed)

			cfg := baseConfig()
			cfg.Output.Dir = dir
			cfg.Generation.Manifest = tt.manifest

			res := runStageResult(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

			for name := range tt.seed {
				assertExists(t, filepath.Join(manifestDir, filepath.FromSlash(name)))
			}
			if len(res.Deleted) != 0 {
				t.Errorf("RunStage reported deletions for an unowned manifest dir: %v", res.Deleted)
			}
		})
	}
}

// TestCleanStale_OwnedManifestDirRemoved is the behavior the ownership gate
// must not cost: a directory a prior `enabled: true` run wrote is still swept
// whole on the flip to false (PRD §23.8 / §30.3), including per-entity files
// whose prefixes the disabled path cannot know. Each case drives real emission
// so the proof is read back off genuinely generated bytes — a template edit
// that drops the anchor fails here rather than silently disowning every
// manifest directory in the wild.
func TestCleanStale_OwnedManifestDirRemoved(t *testing.T) {
	tests := []struct {
		name     string
		manifest *config.ManifestConfig
		anchor   string
	}{
		{
			name:     "both formats",
			manifest: fullManifestConfig(config.JSONLayoutSingle),
			anchor:   "_index.md",
		},
		{
			name:     "markdown only, index is the sole anchor",
			manifest: markdownOnlyManifest(),
			anchor:   "_index.md",
		},
		{
			name:     "json only, manifest_gen.json is the sole anchor",
			manifest: jsonOnlyManifest(),
			anchor:   "manifest_gen.json",
		},
		{
			name: "json only under a custom json_filename",
			manifest: func() *config.ManifestConfig {
				m := jsonOnlyManifest()
				m.JSONFilename = "surface.json"
				return m
			}(),
			anchor: "surface.json",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			manifestDir := filepath.Join(dir, "manifest")

			cfg := baseConfig()
			cfg.Output.Dir = dir
			cfg.Generation.Manifest = tt.manifest
			runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))
			assertExists(t, filepath.Join(manifestDir, tt.anchor))

			// A per-entity file for a table dropped before the flip: the
			// disabled path has no Document and cannot name it, so only
			// whole-directory removal reaches it.
			stale := filepath.Join(manifestDir, "removed_table.md")
			seedDir(t, manifestDir, map[string]string{"removed_table.md": "# gone\n"})

			cfg.Generation.Manifest.Enabled = new(false)
			res := runStageResult(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

			assertAbsent(t, manifestDir)
			assertAbsent(t, stale)

			want := filepath.ToSlash(manifestDir) + "/"
			if !slices.Contains(res.Deleted, want) {
				t.Errorf("RunStage deleted set = %v, want it to contain %q", res.Deleted, want)
			}
		})
	}
}

// TestCleanStale_CustomDirNamesFailClosed pins the documented limitation of
// reading ownership off the emitted content: deleting the whole manifest block
// leaves the disabled path resolving default names, so a manifest emitted under
// custom ones is not recognized and is left in place. Stale artifacts the
// consumer can delete by hand is the correct side to err on — the alternative
// is removing directories sqlgen cannot prove it wrote.
func TestCleanStale_CustomDirNamesFailClosed(t *testing.T) {
	dir := t.TempDir()

	cfg := baseConfig()
	cfg.Output.Dir = dir
	m := jsonOnlyManifest()
	m.JSONFilename = "surface.json"
	cfg.Generation.Manifest = m
	runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))
	assertExists(t, filepath.Join(dir, "manifest", "surface.json"))

	// The whole block goes, not just `enabled: false` — the custom filename
	// goes with it.
	cfg.Generation.Manifest = nil
	runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

	assertExists(t, filepath.Join(dir, "manifest", "surface.json"))
}

// TestCleanStale_AnchorCannotBeRelocated pins that the ownership proof must
// come from inside the directory being removed. json_filename is unvalidated
// config, so a value carrying path separators would otherwise read the anchor
// out of some other directory and re-authorize RemoveAll on the strength of a
// manifest that has nothing to do with the target.
func TestCleanStale_AnchorCannotBeRelocated(t *testing.T) {
	dir := t.TempDir()

	// A real sqlgen manifest at <dir>/real/, emitted normally.
	realCfg := baseConfig()
	realCfg.Output.Dir = dir
	realCfg.Generation.Manifest = jsonOnlyManifest()
	realCfg.Generation.Manifest.MarkdownDir = "real"
	runStage(t, makeStageInput(t, stageSchema(), realCfg, "2026-07-09T00:00:00Z"))
	assertExists(t, filepath.Join(dir, "real", "manifest_gen.json"))

	// A consumer directory that sqlgen never wrote, with a config pointing
	// json_filename up and across at the real manifest's anchor.
	victim := filepath.Join(dir, "manifest")
	seedDir(t, victim, map[string]string{"load.go": "package manifest\n"})

	cfg := baseConfig()
	cfg.Output.Dir = dir
	cfg.Generation.Manifest = &config.ManifestConfig{
		Enabled:      new(false),
		JSONFilename: filepath.Join("..", "real", "manifest_gen.json"),
	}
	runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

	assertExists(t, filepath.Join(victim, "load.go"))
}

// TestCleanStale_UnreadableAnchorDoesNotFailGeneration pins that an ownership
// probe cannot abort the run. The probed path may belong to someone else
// entirely, so the only thing a failed read can justify is declining to delete
// — never failing the whole generation over a file sqlgen has no claim to.
func TestCleanStale_UnreadableAnchorDoesNotFailGeneration(t *testing.T) {
	dir := t.TempDir()
	manifestDir := filepath.Join(dir, "manifest")

	// _index.md as a directory: every read of it fails with something other
	// than ErrNotExist, without depending on running as an unprivileged user
	// (chmod-based unreadability is a no-op for root in CI containers).
	if err := os.MkdirAll(filepath.Join(manifestDir, "_index.md"), 0o750); err != nil {
		t.Fatalf("seeding unreadable anchor: %v", err)
	}
	seedDir(t, manifestDir, map[string]string{"keep.go": "package manifest\n"})

	cfg := baseConfig()
	cfg.Output.Dir = dir
	cfg.Generation.Manifest = &config.ManifestConfig{Enabled: new(false)}

	if _, err := manifest.RunStage(makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z")); err != nil {
		t.Fatalf("RunStage failed on an unreadable ownership probe: %v", err)
	}
	assertExists(t, filepath.Join(manifestDir, "keep.go"))
}

// TestCleanStale_EntitiesDirDroppedOnLayoutFlip covers the second removal site:
// a per_entity → single flip drops <markdown_dir>/entities/. It prunes the
// *.json files sqlgen emits there and removes the directory only once empty, so
// anything else a consumer left inside survives.
func TestCleanStale_EntitiesDirDroppedOnLayoutFlip(t *testing.T) {
	tests := []struct {
		name      string
		stray     string
		wantDir   bool
		wantStray bool
	}{
		{name: "only sqlgen json inside, directory goes", wantDir: false},
		{name: "consumer file inside, directory stays", stray: "NOTES.txt", wantDir: true, wantStray: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			entitiesDir := filepath.Join(dir, "manifest", "entities")

			cfg := stageConfig(dir, config.JSONLayoutPerEntity)
			runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))
			assertExists(t, filepath.Join(entitiesDir, "product.json"))

			if tt.stray != "" {
				seedDir(t, entitiesDir, map[string]string{tt.stray: "notes\n"})
			}

			cfg.Generation.Manifest.JSONLayout = config.JSONLayoutSingle
			runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

			assertAbsent(t, filepath.Join(entitiesDir, "product.json"))
			if got := exists(t, entitiesDir); got != tt.wantDir {
				t.Errorf("entities dir exists = %v, want %v", got, tt.wantDir)
			}
			if tt.stray != "" {
				if got := exists(t, filepath.Join(entitiesDir, tt.stray)); got != tt.wantStray {
					t.Errorf("stray %s exists = %v, want %v", tt.stray, got, tt.wantStray)
				}
			}
		})
	}
}

// TestManifestIndexAnchorDrift pins the markdown half of the ownership proof
// against real emitted output. sqlgenOwnsManifestDir reads the literal
// "**Generator:** sqlgen" out of _index.md; templates/_index.md.tmpl renders it
// from Document.Generator. Nothing but this test connects the two, so an edit
// to the template's Generator line would otherwise disown every markdown-only
// manifest directory silently.
func TestManifestIndexAnchorDrift(t *testing.T) {
	const anchor = "**Generator:** sqlgen"

	dir := t.TempDir()
	cfg := baseConfig()
	cfg.Output.Dir = dir
	cfg.Generation.Manifest = markdownOnlyManifest()
	runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

	index := string(readFile(t, filepath.Join(dir, "manifest", "_index.md")))
	if !strings.Contains(index, anchor) {
		t.Errorf("emitted _index.md no longer carries the ownership anchor %q — the disabled-path\ncleanup reads this literal to prove a manifest directory is sqlgen's, so dropping it\nstops manifest.enabled: false from ever removing a markdown-only manifest dir.\nGot:\n%s", anchor, index)
	}
}

// TestCleanStale_BreadcrumbsUnaffectedByDirOwnership pins that the new
// directory gate is scoped to the directory: an unowned manifest/ next to
// sqlgen-owned breadcrumbs must not stop the breadcrumbs from being swept.
func TestCleanStale_BreadcrumbsUnaffectedByDirOwnership(t *testing.T) {
	dir := t.TempDir()

	cfg := stageConfig(dir, config.JSONLayoutSingle)
	runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))
	assertExists(t, filepath.Join(dir, "CLAUDE.md"))

	// Disown the manifest directory, keeping the breadcrumbs sqlgen-owned.
	if err := os.RemoveAll(filepath.Join(dir, "manifest")); err != nil {
		t.Fatalf("clearing manifest dir: %v", err)
	}
	seedDir(t, filepath.Join(dir, "manifest"), map[string]string{"mine.md": "# mine\n"})

	cfg.Generation.Manifest.Enabled = new(false)
	runStage(t, makeStageInput(t, stageSchema(), cfg, "2026-07-09T00:00:00Z"))

	assertExists(t, filepath.Join(dir, "manifest", "mine.md"))
	assertAbsent(t, filepath.Join(dir, "CLAUDE.md"))
	assertAbsent(t, filepath.Join(dir, "AGENTS.md"))
	assertAbsent(t, filepath.Join(dir, "manifest_embed_gen.go"))
}
