package manifest_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/config"
	"github.com/teandresmith/sqlgen/cmd/sqlgen/manifest"
)

// allBreadcrumbs enables every breadcrumb sub-flag (the resolved-config state
// when the manifest is enabled with no overrides).
func allBreadcrumbs() config.BreadcrumbsConfig {
	return config.BreadcrumbsConfig{
		ClaudeMD:   new(true),
		AgentsMD:   new(true),
		PackageDoc: new(true),
	}
}

func modelsInput(dir string, bc config.BreadcrumbsConfig) manifest.BreadcrumbsInput {
	return manifest.BreadcrumbsInput{
		Doc:         newFixtureDocument(),
		Breadcrumbs: bc,
		OutputDir:   dir,
		MarkdownDir: "manifest",
	}
}

// TestEmitBreadcrumbs_Goldens pins the models breadcrumb content and the
// byte-identity of CLAUDE.md / AGENTS.md (single template, two paths), including
// the leading provenance marker.
func TestEmitBreadcrumbs_Goldens(t *testing.T) {
	dir := t.TempDir()
	if _, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs())); err != nil {
		t.Fatalf("EmitBreadcrumbs error: %v", err)
	}

	claude := readFile(t, filepath.Join(dir, "CLAUDE.md"))
	agents := readFile(t, filepath.Join(dir, "AGENTS.md"))
	if !bytes.Equal(claude, agents) {
		t.Errorf("CLAUDE.md and AGENTS.md are not byte-identical")
	}
	if !bytes.HasPrefix(claude, []byte("<!-- Generated by sqlgen")) {
		t.Errorf("breadcrumb missing leading provenance marker; got:\n%s", claude)
	}
	checkGolden(t, filepath.Join("testdata", "golden", "breadcrumbs", "CLAUDE.md"), claude)
}

// TestEmitBreadcrumbs_LayeredGoldens pins the layered graph breadcrumb content
// (three-pointer layout) and its byte-identity across CLAUDE.md / AGENTS.md.
func TestEmitBreadcrumbs_LayeredGoldens(t *testing.T) {
	root := t.TempDir()
	in := manifest.BreadcrumbsInput{
		Doc:         newFixtureDocument(),
		Breadcrumbs: allBreadcrumbs(),
		OutputDir:   filepath.Join(root, "models"),
		MarkdownDir: "manifest",
		GraphDir:    filepath.Join(root, "graph"),
	}
	if _, err := manifest.EmitBreadcrumbs(in); err != nil {
		t.Fatalf("EmitBreadcrumbs error: %v", err)
	}

	claude := readFile(t, filepath.Join(root, "graph", "CLAUDE.md"))
	agents := readFile(t, filepath.Join(root, "graph", "AGENTS.md"))
	if !bytes.Equal(claude, agents) {
		t.Errorf("graph/CLAUDE.md and graph/AGENTS.md are not byte-identical")
	}
	if !bytes.HasPrefix(claude, []byte("<!-- Generated by sqlgen")) {
		t.Errorf("layered breadcrumb missing leading provenance marker; got:\n%s", claude)
	}
	checkGolden(t, filepath.Join("testdata", "golden", "breadcrumbs", "graph_CLAUDE.md"), claude)
}

// TestEmitBreadcrumbs_LayeredRelativePath pins the models-manifest pointer
// computed from the graph dir's perspective. With output.dir=models and a
// top-level sibling graph dir, the pointer is ../models/manifest/_index.md
// (forward slashes, portable). A nested graph dir points inward.
func TestEmitBreadcrumbs_LayeredRelativePath(t *testing.T) {
	tests := []struct {
		name      string
		outputDir string
		graphDir  string
		want      string
	}{
		{name: "top-level sibling graph", outputDir: "models", graphDir: "graph", want: "../models/manifest/_index.md"},
		{name: "nested graph under models", outputDir: "models", graphDir: "models/graph", want: "../manifest/_index.md"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			in := manifest.BreadcrumbsInput{
				Doc:         newFixtureDocument(),
				Breadcrumbs: allBreadcrumbs(),
				OutputDir:   filepath.Join(root, tt.outputDir),
				MarkdownDir: "manifest",
				GraphDir:    filepath.Join(root, tt.graphDir),
			}
			if _, err := manifest.EmitBreadcrumbs(in); err != nil {
				t.Fatalf("EmitBreadcrumbs error: %v", err)
			}
			md := string(readFile(t, filepath.Join(root, tt.graphDir, "CLAUDE.md")))
			if !strings.Contains(md, tt.want) {
				t.Errorf("layered breadcrumb missing pointer %q; got:\n%s", tt.want, md)
			}
		})
	}
}

func TestEmitBreadcrumbs_OptOut(t *testing.T) {
	t.Run("claude_md false omits CLAUDE.md", func(t *testing.T) {
		dir := t.TempDir()
		bc := allBreadcrumbs()
		bc.ClaudeMD = new(false)
		if _, err := manifest.EmitBreadcrumbs(modelsInput(dir, bc)); err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, "CLAUDE.md")); !os.IsNotExist(err) {
			t.Errorf("expected no CLAUDE.md with claude_md: false; stat err = %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); err != nil {
			t.Errorf("expected AGENTS.md to still be written; stat err = %v", err)
		}
	})

	t.Run("agents_md false omits AGENTS.md", func(t *testing.T) {
		dir := t.TempDir()
		bc := allBreadcrumbs()
		bc.AgentsMD = new(false)
		if _, err := manifest.EmitBreadcrumbs(modelsInput(dir, bc)); err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
			t.Errorf("expected no AGENTS.md with agents_md: false; stat err = %v", err)
		}
		if _, err := os.Stat(filepath.Join(dir, "CLAUDE.md")); err != nil {
			t.Errorf("expected CLAUDE.md to still be written; stat err = %v", err)
		}
	})

	// NB: the package_doc sub-flag governs the models_gen.go doc-comment pointer,
	// which is a cmd/sqlgen/gen orchestrate concern. EmitBreadcrumbs does not
	// touch models_gen.go, so its opt-out is exercised in the gen package's
	// orchestrate tests, not here.
}

// plantFile writes content to a target under dir, creating parents.
func plantFile(t *testing.T, target, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(target), 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(target, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", target, err)
	}
}

func TestEmitBreadcrumbs_Ownership(t *testing.T) {
	// A prior sqlgen-authored breadcrumb: marker + stale body. Used by the
	// overwrite and marker-deleted cases.
	freshClaude := func(t *testing.T) []byte {
		t.Helper()
		dir := t.TempDir()
		if _, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs())); err != nil {
			t.Fatalf("render fresh breadcrumb: %v", err)
		}
		return readFile(t, filepath.Join(dir, "CLAUDE.md"))
	}

	t.Run("absent target is written with marker", func(t *testing.T) {
		dir := t.TempDir()
		warns, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs()))
		if err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		if len(warns) != 0 {
			t.Errorf("expected no warnings for absent targets; got %v", warns)
		}
		got := readFile(t, filepath.Join(dir, "CLAUDE.md"))
		if !bytes.Contains(got, []byte("Generated by sqlgen")) {
			t.Errorf("written breadcrumb missing marker; got:\n%s", got)
		}
	})

	t.Run("present with marker is overwritten", func(t *testing.T) {
		dir := t.TempDir()
		fresh := freshClaude(t)
		// Plant an owned-but-stale file (marker present, wrong body).
		stale := "<!-- Generated by sqlgen — manifest breadcrumb. -->\n\nSTALE BODY\n"
		plantFile(t, filepath.Join(dir, "CLAUDE.md"), stale)

		warns, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs()))
		if err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		if len(warns) != 0 {
			t.Errorf("expected no warnings when overwriting an owned file; got %v", warns)
		}
		got := readFile(t, filepath.Join(dir, "CLAUDE.md"))
		if bytes.Contains(got, []byte("STALE BODY")) {
			t.Errorf("owned file was not overwritten; still contains stale body:\n%s", got)
		}
		if !bytes.Equal(got, fresh) {
			t.Errorf("overwritten breadcrumb does not match freshly-rendered content")
		}
	})

	t.Run("present without marker is left untouched and warns", func(t *testing.T) {
		dir := t.TempDir()
		userContent := "# My hand-authored CLAUDE.md\n\nDo not touch.\n"
		target := filepath.Join(dir, "CLAUDE.md")
		plantFile(t, target, userContent)

		warns, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs()))
		if err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		if got := string(readFile(t, target)); got != userContent {
			t.Errorf("user-owned CLAUDE.md was modified; got:\n%s", got)
		}
		if len(warns) != 1 {
			t.Fatalf("expected exactly one warning; got %d: %v", len(warns), warns)
		}
		w := warns[0]
		for _, want := range []string{
			"CLAUDE.md",
			"## Data-access surface (sqlgen)",
			"See ./manifest/_index.md",
			"generation.manifest.breadcrumbs.claude_md: false",
		} {
			if !strings.Contains(w, want) {
				t.Errorf("warning missing %q; got:\n%s", want, w)
			}
		}
	})

	t.Run("marker line deleted becomes user-owned", func(t *testing.T) {
		dir := t.TempDir()
		fresh := string(freshClaude(t))
		// Simulate the user adopting the file by deleting the marker's first
		// line (the one carrying "Generated by sqlgen").
		_, rest, found := strings.Cut(fresh, "\n")
		if !found {
			t.Fatalf("fresh breadcrumb has no newline to strip")
		}
		adopted := rest
		target := filepath.Join(dir, "CLAUDE.md")
		plantFile(t, target, adopted)

		warns, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs()))
		if err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		if got := string(readFile(t, target)); got != adopted {
			t.Errorf("de-marked (user-adopted) breadcrumb was overwritten; got:\n%s", got)
		}
		if len(warns) != 1 {
			t.Errorf("expected a warning for the user-adopted breadcrumb; got %v", warns)
		}
	})
}

// TestEmitBreadcrumbs_MarkerNotInPointerBlock guards the self-clobber path: the
// pasteable pointer block surfaced in the warning must not carry the provenance
// marker, or a consumer who pastes it into their own file would hand it to
// sqlgen.
func TestEmitBreadcrumbs_MarkerNotInPointerBlock(t *testing.T) {
	dir := t.TempDir()
	plantFile(t, filepath.Join(dir, "CLAUDE.md"), "# hand-authored\n")

	warns, err := manifest.EmitBreadcrumbs(modelsInput(dir, allBreadcrumbs()))
	if err != nil {
		t.Fatalf("EmitBreadcrumbs error: %v", err)
	}
	if len(warns) == 0 {
		t.Fatal("expected a warning for the user-owned file")
	}
	// The pasteable block lives between the "add this to" line and the
	// "To silence" line. It must not contain the marker literal.
	w := warns[0]
	start := strings.Index(w, "## Data-access surface")
	end := strings.Index(w, "To silence this warning")
	if start < 0 || end < 0 || start >= end {
		t.Fatalf("could not locate the pointer block in the warning:\n%s", w)
	}
	block := w[start:end]
	if strings.Contains(block, "Generated by sqlgen") {
		t.Errorf("pointer block carries the provenance marker (self-clobber risk):\n%s", block)
	}
}

// TestEmitBreadcrumbs_Determinism asserts byte-identical output across two runs
// for all four artifact files (models + layered).
func TestEmitBreadcrumbs_Determinism(t *testing.T) {
	run := func() map[string][]byte {
		root := t.TempDir()
		in := manifest.BreadcrumbsInput{
			Doc:         newFixtureDocument(),
			Breadcrumbs: allBreadcrumbs(),
			OutputDir:   filepath.Join(root, "models"),
			MarkdownDir: "manifest",
			GraphDir:    filepath.Join(root, "graph"),
		}
		if _, err := manifest.EmitBreadcrumbs(in); err != nil {
			t.Fatalf("EmitBreadcrumbs error: %v", err)
		}
		return map[string][]byte{
			"models/CLAUDE.md": readFile(t, filepath.Join(root, "models", "CLAUDE.md")),
			"models/AGENTS.md": readFile(t, filepath.Join(root, "models", "AGENTS.md")),
			"graph/CLAUDE.md":  readFile(t, filepath.Join(root, "graph", "CLAUDE.md")),
			"graph/AGENTS.md":  readFile(t, filepath.Join(root, "graph", "AGENTS.md")),
		}
	}

	a := run()
	b := run()
	for name, ba := range a {
		if !bytes.Equal(ba, b[name]) {
			t.Errorf("EmitBreadcrumbs %s not byte-deterministic across runs", name)
		}
	}
}
