package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models/graph/model"
)

// CreateBinaryKey is the resolver for the createBinaryKey field.
func (r *mutationResolver) CreateBinaryKey(ctx context.Context, input gqlmodel.CreateBinaryKeyInput) (*models.BinaryKey, error) {
	return r.M.CreateBinaryKey(ctx, translateCreateBinaryKeyInput(input))
}

// CreateBinaryKeys is the resolver for the createBinaryKeys field.
func (r *mutationResolver) CreateBinaryKeys(ctx context.Context, inputs []*gqlmodel.CreateBinaryKeyInput) ([]*models.BinaryKey, error) {
	xs := make([]*models.CreateBinaryKeyInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateBinaryKeyInput(*in))
	}
	return r.M.CreateBinaryKeys(ctx, xs)
}

// UpdateBinaryKey is the resolver for the updateBinaryKey field.
// No numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateBinaryKey(ctx context.Context, id []byte, input gqlmodel.UpdateBinaryKeyInput) (*models.BinaryKey, error) {
	setIn := translateUpdateBinaryKeyInput(input)
	hasSet := hasUpdateBinaryKeySetFields(input)
	return r.M.UpdateBinaryKey(ctx, id, setIn, hasSet)
}

// UpdateBinaryKeys is the resolver for the updateBinaryKeys field.
func (r *mutationResolver) UpdateBinaryKeys(ctx context.Context, filter gqlmodel.BinaryKeyFilter, input gqlmodel.UpdateBinaryKeyInput) ([]*models.BinaryKey, error) {
	return r.M.UpdateBinaryKeys(ctx, translateBinaryKeyFilter(&filter), translateUpdateBinaryKeyInput(input))
}

// UpsertBinaryKey is the resolver for the upsertBinaryKey field.
func (r *mutationResolver) UpsertBinaryKey(ctx context.Context, input gqlmodel.CreateBinaryKeyInput) (*models.BinaryKey, error) {
	return r.M.UpsertBinaryKey(ctx, translateCreateBinaryKeyInput(input))
}

// DeleteBinaryKey is the resolver for the deleteBinaryKey field.
func (r *mutationResolver) DeleteBinaryKey(ctx context.Context, id []byte) (bool, error) {
	return r.M.DeleteBinaryKey(ctx, id)
}

// BinaryKey is the resolver for the binaryKey field.
func (r *queryResolver) BinaryKey(ctx context.Context, id []byte) (*models.BinaryKey, error) {
	return r.Q.BinaryKey(ctx, id)
}

// BinaryKeys is the resolver for the binaryKeys field.
func (r *queryResolver) BinaryKeys(ctx context.Context, filter *gqlmodel.BinaryKeyFilter, first *int, after *string, last *int, before *string) (*models.Connection[models.BinaryKey], error) {
	return r.Q.BinaryKeys(ctx, translateBinaryKeyFilter(filter), first, after, last, before)
}

// BinaryKeyList is the resolver for the binaryKeyList field.
func (r *queryResolver) BinaryKeyList(ctx context.Context, filter *gqlmodel.BinaryKeyFilter, sort []*gqlmodel.BinaryKeySort, limit *int, offset *int) (*models.PaginateResult[models.BinaryKey], error) {
	return r.Q.BinaryKeyList(ctx, translateBinaryKeyFilter(filter), translateBinaryKeySort(sort), limit, offset)
}
