package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models/graph/model"
)

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input gqlmodel.CreateTagInput) (*models.Tag, error) {
	return r.M.CreateTag(ctx, translateCreateTagInput(input))
}

// CreateTags is the resolver for the createTags field.
func (r *mutationResolver) CreateTags(ctx context.Context, inputs []*gqlmodel.CreateTagInput) ([]*models.Tag, error) {
	xs := make([]*models.CreateTagInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateTagInput(*in))
	}
	return r.M.CreateTags(ctx, xs)
}

// UpdateTag is the resolver for the updateTag field.
// No numeric non-PK columns → no IncrementColumn enum, no `_inc`/
// `_dec` operators on the input, and the seed delegates with the reduced
// (set-only) signature exposed by Q/M.
func (r *mutationResolver) UpdateTag(ctx context.Context, id int, input gqlmodel.UpdateTagInput) (*models.Tag, error) {
	setIn := translateUpdateTagInput(input)
	hasSet := hasUpdateTagSetFields(input)
	return r.M.UpdateTag(ctx, id, setIn, hasSet)
}

// UpdateTags is the resolver for the updateTags field.
func (r *mutationResolver) UpdateTags(ctx context.Context, filter gqlmodel.TagFilter, input gqlmodel.UpdateTagInput) ([]*models.Tag, error) {
	return r.M.UpdateTags(ctx, translateTagFilter(&filter), translateUpdateTagInput(input))
}

// UpsertTag is the resolver for the upsertTag field.
func (r *mutationResolver) UpsertTag(ctx context.Context, input gqlmodel.CreateTagInput) (*models.Tag, error) {
	return r.M.UpsertTag(ctx, translateCreateTagInput(input))
}

// HardDeleteTag is the resolver for the hardDeleteTag field.
func (r *mutationResolver) HardDeleteTag(ctx context.Context, id int) (bool, error) {
	return r.M.HardDeleteTag(ctx, id)
}

// SoftDeleteTag is the resolver for the softDeleteTag field.
func (r *mutationResolver) SoftDeleteTag(ctx context.Context, id int) (*models.Tag, error) {
	return r.M.SoftDeleteTag(ctx, id)
}

// RestoreTag is the resolver for the restoreTag field.
func (r *mutationResolver) RestoreTag(ctx context.Context, id int) (*models.Tag, error) {
	return r.M.RestoreTag(ctx, id)
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(ctx context.Context, id int) (*models.Tag, error) {
	return r.Q.Tag(ctx, id)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, filter *gqlmodel.TagFilter, first *int, after *string, last *int, before *string) (*models.Connection[models.Tag], error) {
	return r.Q.Tags(ctx, translateTagFilter(filter), first, after, last, before)
}

// TagList is the resolver for the tagList field.
func (r *queryResolver) TagList(ctx context.Context, filter *gqlmodel.TagFilter, sort []*gqlmodel.TagSort, limit *int, offset *int) (*models.PaginateResult[models.Tag], error) {
	return r.Q.TagList(ctx, translateTagFilter(filter), translateTagSort(sort), limit, offset)
}
