package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models/graph/model"
	"github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/sqlite/models/graph/sqlgenresolver"
)

// CreateWarehouse is the resolver for the createWarehouse field.
func (r *mutationResolver) CreateWarehouse(ctx context.Context, input gqlmodel.CreateWarehouseInput) (*models.Warehouse, error) {
	return r.M.CreateWarehouse(ctx, translateCreateWarehouseInput(input))
}

// CreateWarehouses is the resolver for the createWarehouses field.
func (r *mutationResolver) CreateWarehouses(ctx context.Context, inputs []*gqlmodel.CreateWarehouseInput) ([]*models.Warehouse, error) {
	xs := make([]*models.CreateWarehouseInput, 0, len(inputs))
	for _, in := range inputs {
		if in == nil {
			continue
		}
		xs = append(xs, translateCreateWarehouseInput(*in))
	}
	return r.M.CreateWarehouses(ctx, xs)
}

// UpdateWarehouse is the resolver for the updateWarehouse field.
func (r *mutationResolver) UpdateWarehouse(ctx context.Context, id int, input gqlmodel.UpdateWarehouseInput) (*models.Warehouse, error) {
	if input.Price != nil && input.PriceInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"price\" cannot be both set and incremented in one mutation")
	}
	if input.PriceInc != nil && input.PriceDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"price\" cannot be both incremented and decremented in one mutation")
	}
	if input.NullablePrice != nil && input.NullablePriceInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"nullable_price\" cannot be both set and incremented in one mutation")
	}
	if input.NullablePriceInc != nil && input.NullablePriceDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"nullable_price\" cannot be both incremented and decremented in one mutation")
	}
	setIn := translateUpdateWarehouseInput(input)
	hasSet := hasUpdateWarehouseSetFields(input)
	var incOps []sqlgenresolver.IncrementOp[models.WarehouseIncrementColumn]
	if input.PriceInc != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[models.WarehouseIncrementColumn]{
			Column: models.WarehouseIncrementPrice,
			Amount: int(*input.PriceInc),
		})
	}
	if input.PriceDec != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[models.WarehouseIncrementColumn]{
			Column: models.WarehouseIncrementPrice,
			Amount: -int(*input.PriceDec),
		})
	}
	if input.NullablePriceInc != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[models.WarehouseIncrementColumn]{
			Column: models.WarehouseIncrementNullablePrice,
			Amount: int(*input.NullablePriceInc),
		})
	}
	if input.NullablePriceDec != nil {
		incOps = append(incOps, sqlgenresolver.IncrementOp[models.WarehouseIncrementColumn]{
			Column: models.WarehouseIncrementNullablePrice,
			Amount: -int(*input.NullablePriceDec),
		})
	}
	return r.M.UpdateWarehouse(ctx, id, setIn, hasSet, incOps)
}

// UpdateWarehouses is the resolver for the updateWarehouses field.
func (r *mutationResolver) UpdateWarehouses(ctx context.Context, filter gqlmodel.WarehouseFilter, input gqlmodel.UpdateWarehouseInput) ([]*models.Warehouse, error) {
	if input.Price != nil && input.PriceInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"price\" cannot be both set and incremented in one mutation")
	}
	if input.PriceInc != nil && input.PriceDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"price\" cannot be both incremented and decremented in one mutation")
	}
	if input.NullablePrice != nil && input.NullablePriceInc != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"nullable_price\" cannot be both set and incremented in one mutation")
	}
	if input.NullablePriceInc != nil && input.NullablePriceDec != nil {
		return nil, sqlgenresolver.InvalidInputError("update warehouses: column \"nullable_price\" cannot be both incremented and decremented in one mutation")
	}
	return r.M.UpdateWarehouses(ctx, translateWarehouseFilter(&filter), translateUpdateWarehouseInput(input))
}

// UpsertWarehouse is the resolver for the upsertWarehouse field.
func (r *mutationResolver) UpsertWarehouse(ctx context.Context, input gqlmodel.CreateWarehouseInput) (*models.Warehouse, error) {
	return r.M.UpsertWarehouse(ctx, translateCreateWarehouseInput(input))
}

// DeleteWarehouse is the resolver for the deleteWarehouse field.
func (r *mutationResolver) DeleteWarehouse(ctx context.Context, id int) (bool, error) {
	return r.M.DeleteWarehouse(ctx, id)
}

// Warehouse is the resolver for the warehouse field.
func (r *queryResolver) Warehouse(ctx context.Context, id int) (*models.Warehouse, error) {
	return r.Q.Warehouse(ctx, id)
}

// Warehouses is the resolver for the warehouses field.
func (r *queryResolver) Warehouses(ctx context.Context, filter *gqlmodel.WarehouseFilter, first *int, after *string, last *int, before *string) (*models.Connection[models.Warehouse], error) {
	return r.Q.Warehouses(ctx, translateWarehouseFilter(filter), first, after, last, before)
}

// WarehouseList is the resolver for the warehouseList field.
func (r *queryResolver) WarehouseList(ctx context.Context, filter *gqlmodel.WarehouseFilter, sort []*gqlmodel.WarehouseSort, limit *int, offset *int) (*models.PaginateResult[models.Warehouse], error) {
	return r.Q.WarehouseList(ctx, translateWarehouseFilter(filter), translateWarehouseSort(sort), limit, offset)
}
