// Code generated by sqlgen dev. DO NOT EDIT.
package models

import (
	"database/sql/driver"
	"fmt"
	"io"
	"strings"
)

// OrderStatus — Lifecycle state of a customer order
type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusShipped    OrderStatus = "shipped"
	OrderStatusDelivered  OrderStatus = "delivered"
	OrderStatusCancelled  OrderStatus = "cancelled"
)

// AllOrderStatus contains all valid OrderStatus values.
var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusProcessing,
	OrderStatusShipped,
	OrderStatusDelivered,
	OrderStatusCancelled,
}

// String returns the string representation of the OrderStatus.
func (s OrderStatus) String() string { return string(s) }

// ValidateOrderStatus returns a valid OrderStatus or an error if the input
// is not a known value.
func ValidateOrderStatus(s string) (OrderStatus, error) {
	switch OrderStatus(s) {
	case OrderStatusPending, OrderStatusProcessing, OrderStatusShipped, OrderStatusDelivered, OrderStatusCancelled:
		return OrderStatus(s), nil
	default:
		return "", fmt.Errorf("invalid OrderStatus: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known OrderStatus.
func (s *OrderStatus) UnmarshalText(b []byte) error {
	v, err := ValidateOrderStatus(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s OrderStatus) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *OrderStatus) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = OrderStatus(v)
		return nil
	case []byte:
		*s = OrderStatus(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into OrderStatus", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s OrderStatus) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case OrderStatusPending:
		name = "PENDING"
	case OrderStatusProcessing:
		name = "PROCESSING"
	case OrderStatusShipped:
		name = "SHIPPED"
	case OrderStatusDelivered:
		name = "DELIVERED"
	case OrderStatusCancelled:
		name = "CANCELLED"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for OrderStatus, got %T", v)
	}
	switch str {
	case "PENDING":
		*s = OrderStatusPending
	case "PROCESSING":
		*s = OrderStatusProcessing
	case "SHIPPED":
		*s = OrderStatusShipped
	case "DELIVERED":
		*s = OrderStatusDelivered
	case "CANCELLED":
		*s = OrderStatusCancelled
	default:
		return fmt.Errorf("invalid OrderStatus: %q", str)
	}
	return nil
}

// OrderStatusSlice represents a PostgreSQL array of OrderStatus values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type OrderStatusSlice []OrderStatus

// String returns the PostgreSQL array literal representation.
func (s OrderStatusSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s OrderStatusSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *OrderStatusSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into OrderStatusSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = OrderStatusSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(OrderStatusSlice, len(parts))
	for i, p := range parts {
		result[i] = OrderStatus(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[OrderStatus!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s OrderStatusSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[OrderStatus!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *OrderStatusSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for OrderStatusSlice, got %T", v)
	}
	out := make(OrderStatusSlice, 0, len(raw))
	for i, item := range raw {
		var elem OrderStatus
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("OrderStatusSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}

// UserRole — Access level assigned to a user account
type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleEditor UserRole = "editor"
	UserRoleViewer UserRole = "viewer"
)

// AllUserRole contains all valid UserRole values.
var AllUserRole = []UserRole{
	UserRoleAdmin,
	UserRoleEditor,
	UserRoleViewer,
}

// String returns the string representation of the UserRole.
func (s UserRole) String() string { return string(s) }

// ValidateUserRole returns a valid UserRole or an error if the input
// is not a known value.
func ValidateUserRole(s string) (UserRole, error) {
	switch UserRole(s) {
	case UserRoleAdmin, UserRoleEditor, UserRoleViewer:
		return UserRole(s), nil
	default:
		return "", fmt.Errorf("invalid UserRole: %q", s)
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserRole) MarshalText() ([]byte, error) {
	return []byte(s), nil
}

// UnmarshalText implements encoding.TextUnmarshaler. Returns an error if the
// value is not a known UserRole.
func (s *UserRole) UnmarshalText(b []byte) error {
	v, err := ValidateUserRole(string(b))
	if err != nil {
		return err
	}
	*s = v
	return nil
}

// Value implements driver.Valuer.
func (s UserRole) Value() (driver.Value, error) {
	return string(s), nil
}

// Scan implements sql.Scanner.
func (s *UserRole) Scan(src any) error {
	switch v := src.(type) {
	case string:
		*s = UserRole(v)
		return nil
	case []byte:
		*s = UserRole(v)
		return nil
	default:
		return fmt.Errorf("scanning %T into UserRole", src)
	}
}

// MarshalGQL writes the GraphQL enum identifier (SCREAMING_SNAKE_CASE) for s
// onto w. Implements gqlgen's graphql.Marshaler interface via duck typing so
// the models package can be bound directly as a GraphQL enum through the
// `models:` mapping without importing gqlgen. The wire identifier
// (`ASSETPRIMARY`) is the SCREAMING-cased Go constant suffix; the underlying
// string value (e.g. `"asset.primary"`) stays in the Go variable and lands in
// the database column unchanged.
func (s UserRole) MarshalGQL(w io.Writer) {
	var name string
	switch s {
	case UserRoleAdmin:
		name = "ADMIN"
	case UserRoleEditor:
		name = "EDITOR"
	case UserRoleViewer:
		name = "VIEWER"
	default:
		name = ""
	}
	fmt.Fprintf(w, "%q", name)
}

// UnmarshalGQL parses the GraphQL enum identifier received from a client into
// the typed value. Mirrors MarshalGQL on the inbound path. Returns an error on
// unknown identifier so gqlgen surfaces a typed validation failure rather than
// inserting a zero-value enum into the database.
func (s *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("expected string for UserRole, got %T", v)
	}
	switch str {
	case "ADMIN":
		*s = UserRoleAdmin
	case "EDITOR":
		*s = UserRoleEditor
	case "VIEWER":
		*s = UserRoleViewer
	default:
		return fmt.Errorf("invalid UserRole: %q", str)
	}
	return nil
}

// UserRoleSlice represents a PostgreSQL array of UserRole values.
// It implements driver.Valuer and sql.Scanner using the PostgreSQL array text format
// so that pgx can handle custom enum array OIDs without manual type registration.
type UserRoleSlice []UserRole

// String returns the PostgreSQL array literal representation.
func (s UserRoleSlice) String() string {
	parts := make([]string, len(s))
	for i, v := range s {
		parts[i] = string(v)
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// Value implements driver.Valuer.
func (s UserRoleSlice) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return s.String(), nil
}

// Scan implements sql.Scanner.
func (s *UserRoleSlice) Scan(src any) error {
	if src == nil {
		*s = nil
		return nil
	}
	var str string
	switch v := src.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	default:
		return fmt.Errorf("scanning %T into UserRoleSlice", src)
	}
	str = strings.TrimPrefix(str, "{")
	str = strings.TrimSuffix(str, "}")
	if str == "" {
		*s = UserRoleSlice{}
		return nil
	}
	parts := strings.Split(str, ",")
	result := make(UserRoleSlice, len(parts))
	for i, p := range parts {
		result[i] = UserRole(p)
	}
	*s = result
	return nil
}

// MarshalGQL writes the JSON array of GraphQL enum identifiers to w. Lets
// gqlgen bind the GraphQL list type (`[UserRole!]!`) directly to
// this named slice via the `models:` mapping, avoiding the per-field resolver
// stub gqlgen would otherwise emit for a list-of-bound-scalar shape.
func (s UserRoleSlice) MarshalGQL(w io.Writer) {
	w.Write([]byte("["))
	for i, v := range s {
		if i > 0 {
			w.Write([]byte(","))
		}
		v.MarshalGQL(w)
	}
	w.Write([]byte("]"))
}

// UnmarshalGQL parses a JSON array of GraphQL enum identifiers (the wire form
// gqlgen produces for an inbound `[UserRole!]` argument) into
// the named slice. Each element round-trips through the bare enum's
// UnmarshalGQL so unknown identifiers surface a typed validation error.
func (s *UserRoleSlice) UnmarshalGQL(v any) error {
	raw, ok := v.([]any)
	if !ok {
		return fmt.Errorf("expected []any for UserRoleSlice, got %T", v)
	}
	out := make(UserRoleSlice, 0, len(raw))
	for i, item := range raw {
		var elem UserRole
		if err := elem.UnmarshalGQL(item); err != nil {
			return fmt.Errorf("UserRoleSlice[%d]: %w", i, err)
		}
		out = append(out, elem)
	}
	*s = out
	return nil
}
