// Code generated by sqlgen dev. DO NOT EDIT.
package graph

import (
	"time"

	"github.com/teandresmith/sqlgen/comparator"

	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql_null_wrappers/models/graph/model"
)

// Per-family comparator translators. These are shared across
// the whole project (one impl per family variant, regardless of how many
// tables reference it) and are dispatched into by the per-table filter
// translators in filter_translate_gen.go.
//
// Numeric variants are emitted per Go T parameter (e.g.
// translateNumericComparatorInt32, translateNumericComparatorFloat64). The
// gqlgen-generated NumericComparator carries float64-typed fields (the
// GraphQL `Float` scalar binds to Go `float64`); each variant casts to its
// underlying T so the resulting *comparator.Number[T] matches the model
// filter's column type exactly.
//
// Nullable variants take their own Nullable<X>Comparator input, not the base
// one — GraphQL input types are global, so `isNull` cannot be a conditional
// field on a shared input and nullability has to be a separate type.
// They therefore copy the operands themselves rather than
// delegating to the base translator: the two functions no longer accept the
// same Go type. The operand block is identical text either way because
// comparator.Nullable<X> embeds <X>, so Go promotes the field assignments.
// `isNull` lands in the wrapper's `Null *bool`, giving IS NULL / IS NOT NULL
// a reachable path from the API surface.
//
// The `Custom []sql.Condition` field every family carries is deliberately
// never populated here — it is a raw-SQL escape hatch, and exposing it over
// HTTP would be an injection surface.

// translateDecimalComparator translates a GraphQL DecimalComparator into a
// *comparator.String for the model layer's filter struct.
//
// Decimal columns filter through comparator.String on the canonical string
// form — decimal.Decimal does not satisfy comparator.Numeric — so
// each Decimal-typed operand is rendered with String(). The ordered
// operators stay numerically correct because the parameter is compared
// against a numeric column: the database coerces it, rather than collating
// it as text.
func translateDecimalComparator(in *gqlmodel.DecimalComparator) *comparator.String {
	if in == nil {
		return nil
	}
	out := &comparator.String{}
	if in.Eq != nil {
		v := in.Eq.String()
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq.String()
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt.String()
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte.String()
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt.String()
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte.String()
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]string, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]string, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.Nin = xs
	}
	return out
}

// translateNullableBooleanComparator translates a GraphQL NullableBooleanComparator into a
// *comparator.NullableBool for the model layer's filter struct.
func translateNullableBooleanComparator(in *gqlmodel.NullableBooleanComparator) *comparator.NullableBool {
	if in == nil {
		return nil
	}
	out := &comparator.NullableBool{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableDecimalComparator translates a GraphQL NullableDecimalComparator into a
// *comparator.NullableString for the model layer's filter struct.
//
// Decimal columns filter through comparator.String on the canonical string
// form — decimal.Decimal does not satisfy comparator.Numeric — so
// each Decimal-typed operand is rendered with String(). The ordered
// operators stay numerically correct because the parameter is compared
// against a numeric column: the database coerces it, rather than collating
// it as text.
func translateNullableDecimalComparator(in *gqlmodel.NullableDecimalComparator) *comparator.NullableString {
	if in == nil {
		return nil
	}
	out := &comparator.NullableString{}
	if in.Eq != nil {
		v := in.Eq.String()
		out.Eq = &v
	}
	if in.Neq != nil {
		v := in.Neq.String()
		out.Neq = &v
	}
	if in.Gt != nil {
		v := in.Gt.String()
		out.Gt = &v
	}
	if in.Gte != nil {
		v := in.Gte.String()
		out.Gte = &v
	}
	if in.Lt != nil {
		v := in.Lt.String()
		out.Lt = &v
	}
	if in.Lte != nil {
		v := in.Lte.String()
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]string, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]string, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, v.String())
		}
		out.Nin = xs
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableIDComparator translates a GraphQL NullableIDComparator into a
// *comparator.NullableID for the model layer's filter struct.
func translateNullableIDComparator(in *gqlmodel.NullableIDComparator) *comparator.NullableID {
	if in == nil {
		return nil
	}
	out := &comparator.NullableID{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorFloat64 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[float64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into float64 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorFloat64(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[float64] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[float64]{}
	if in.Eq != nil {
		v := float64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := float64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := float64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := float64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := float64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := float64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]float64, len(in.In))
		for i, v := range in.In {
			xs[i] = float64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]float64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = float64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[float64]{
			Start: float64(in.Between.From),
			End:   float64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[float64]{
			Start: float64(in.Nbetween.From),
			End:   float64(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorInt16 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[int16] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int16 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorInt16(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[int16] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[int16]{}
	if in.Eq != nil {
		v := int16(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int16(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int16(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int16(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int16(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int16(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int16, len(in.In))
		for i, v := range in.In {
			xs[i] = int16(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int16, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int16(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int16]{
			Start: int16(in.Between.From),
			End:   int16(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int16]{
			Start: int16(in.Nbetween.From),
			End:   int16(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorInt32 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[int32] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int32 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorInt32(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[int32] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[int32]{}
	if in.Eq != nil {
		v := int32(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int32(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int32(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int32(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int32(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int32(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int32, len(in.In))
		for i, v := range in.In {
			xs[i] = int32(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int32, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int32(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int32]{
			Start: int32(in.Between.From),
			End:   int32(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int32]{
			Start: int32(in.Nbetween.From),
			End:   int32(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableNumericComparatorInt64 translates a GraphQL NullableNumericComparator into a
// *comparator.NullableNumber[int64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int64 so the
// result matches the model filter's column type exactly.
func translateNullableNumericComparatorInt64(in *gqlmodel.NullableNumericComparator) *comparator.NullableNumber[int64] {
	if in == nil {
		return nil
	}
	out := &comparator.NullableNumber[int64]{}
	if in.Eq != nil {
		v := int64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int64, len(in.In))
		for i, v := range in.In {
			xs[i] = int64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int64]{
			Start: int64(in.Between.From),
			End:   int64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int64]{
			Start: int64(in.Nbetween.From),
			End:   int64(in.Nbetween.To),
		}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableStringComparator translates a GraphQL NullableStringComparator into a
// *comparator.NullableString for the model layer's filter struct.
func translateNullableStringComparator(in *gqlmodel.NullableStringComparator) *comparator.NullableString {
	if in == nil {
		return nil
	}
	out := &comparator.NullableString{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if in.Contains != nil {
		out.Contains = in.Contains
	}
	if in.StartsWith != nil {
		out.StartsWith = in.StartsWith
	}
	if in.EndsWith != nil {
		out.EndsWith = in.EndsWith
	}
	if in.Like != nil {
		out.Like = in.Like
	}
	if in.Nlike != nil {
		out.NLike = in.Nlike
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNullableTimeComparator translates a GraphQL NullableTimeComparator into a
// *comparator.NullableTime for the model layer's filter struct.
func translateNullableTimeComparator(in *gqlmodel.NullableTimeComparator) *comparator.NullableTime {
	if in == nil {
		return nil
	}
	out := &comparator.NullableTime{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]time.Time, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Time, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Time]{Start: in.Between.From, End: in.Between.To}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Time]{Start: in.Nbetween.From, End: in.Nbetween.To}
	}
	if in.IsNull != nil {
		out.Null = in.IsNull
	}
	return out
}

// translateNumericComparatorInt64 translates a GraphQL NumericComparator into a
// *comparator.Number[int64] for the model layer's filter struct.
//
// Each operand casts from the input's float64 into int64 so the
// result matches the model filter's column type exactly.
func translateNumericComparatorInt64(in *gqlmodel.NumericComparator) *comparator.Number[int64] {
	if in == nil {
		return nil
	}
	out := &comparator.Number[int64]{}
	if in.Eq != nil {
		v := int64(*in.Eq)
		out.Eq = &v
	}
	if in.Neq != nil {
		v := int64(*in.Neq)
		out.Neq = &v
	}
	if in.Gt != nil {
		v := int64(*in.Gt)
		out.Gt = &v
	}
	if in.Gte != nil {
		v := int64(*in.Gte)
		out.Gte = &v
	}
	if in.Lt != nil {
		v := int64(*in.Lt)
		out.Lt = &v
	}
	if in.Lte != nil {
		v := int64(*in.Lte)
		out.Lte = &v
	}
	if len(in.In) > 0 {
		xs := make([]int64, len(in.In))
		for i, v := range in.In {
			xs[i] = int64(v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]int64, len(in.Nin))
		for i, v := range in.Nin {
			xs[i] = int64(v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[int64]{
			Start: int64(in.Between.From),
			End:   int64(in.Between.To),
		}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[int64]{
			Start: int64(in.Nbetween.From),
			End:   int64(in.Nbetween.To),
		}
	}
	return out
}

// translateStringComparator translates a GraphQL StringComparator into a
// *comparator.String for the model layer's filter struct.
func translateStringComparator(in *gqlmodel.StringComparator) *comparator.String {
	if in == nil {
		return nil
	}
	out := &comparator.String{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if in.Contains != nil {
		out.Contains = in.Contains
	}
	if in.StartsWith != nil {
		out.StartsWith = in.StartsWith
	}
	if in.EndsWith != nil {
		out.EndsWith = in.EndsWith
	}
	if in.Like != nil {
		out.Like = in.Like
	}
	if in.Nlike != nil {
		out.NLike = in.Nlike
	}
	if len(in.In) > 0 {
		out.In = append([]string(nil), in.In...)
	}
	if len(in.Nin) > 0 {
		out.Nin = append([]string(nil), in.Nin...)
	}
	return out
}

// translateTimeComparator translates a GraphQL TimeComparator into a
// *comparator.Time for the model layer's filter struct.
func translateTimeComparator(in *gqlmodel.TimeComparator) *comparator.Time {
	if in == nil {
		return nil
	}
	out := &comparator.Time{}
	if in.Eq != nil {
		out.Eq = in.Eq
	}
	if in.Neq != nil {
		out.Neq = in.Neq
	}
	if in.Gt != nil {
		out.Gt = in.Gt
	}
	if in.Gte != nil {
		out.Gte = in.Gte
	}
	if in.Lt != nil {
		out.Lt = in.Lt
	}
	if in.Lte != nil {
		out.Lte = in.Lte
	}
	if len(in.In) > 0 {
		xs := make([]time.Time, 0, len(in.In))
		for _, v := range in.In {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.In = xs
	}
	if len(in.Nin) > 0 {
		xs := make([]time.Time, 0, len(in.Nin))
		for _, v := range in.Nin {
			if v == nil {
				continue
			}
			xs = append(xs, *v)
		}
		out.Nin = xs
	}
	if in.Between != nil {
		out.Between = &comparator.Range[time.Time]{Start: in.Between.From, End: in.Between.To}
	}
	if in.Nbetween != nil {
		out.NBetween = &comparator.Range[time.Time]{Start: in.Nbetween.From, End: in.Nbetween.To}
	}
	return out
}
