// Code generated by sqlgen dev. DO NOT EDIT.
package graph

import (
	models "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql_null_wrappers/models"
	gqlmodel "github.com/teandresmith/sqlgen/cmd/sqlgen/testdata/examples/graphql_null_wrappers/models/graph/model"
)

// Per-table GraphQL→model filter translators. Each function
// converts the gqlgen-generated `<Table>Filter` value into the
// consumer's model-side `*<pkg>.<Table>Filter`, dispatching field-level
// translation through the project-wide comparator translators in
// comparator_translate_gen.go.
//
// AND / OR sub-filters recurse into the same translator so deeply-nested
// boolean expressions translate correctly. There is no dedicated
// `includeDeleted` flag in the curated GraphQL surface — the soft-delete
// column itself is exposed in the filter input as a regular comparator
// field, and the runtime's existing soft-delete inject (see
// template/table/get.go.tmpl:184) already short-circuits the auto-injected
// "is not deleted" condition whenever the caller passes ANY non-nil
// comparator on the soft-delete column. To include deleted rows, GraphQL
// callers pass `deletedAt: {}` (or any deletedAt comparator they choose).

// translateAccountFilter converts the gqlgen-generated
// AccountFilter into a *models.AccountFilter.
// Returns nil when the input is nil so the model layer's "nil filter ⇒ no
// where clause" contract is preserved.
func translateAccountFilter(in *gqlmodel.AccountFilter) *models.AccountFilter {
	if in == nil {
		return nil
	}
	out := &models.AccountFilter{}
	if in.Balance != nil {
		out.Balance = translateNullableDecimalComparator(in.Balance)
	}
	if in.BigCount != nil {
		out.BigCount = translateNullableNumericComparatorInt64(in.BigCount)
	}
	if in.CreatedAt != nil {
		out.CreatedAt = translateTimeComparator(in.CreatedAt)
	}
	if in.DeletedAt != nil {
		out.DeletedAt = translateNullableTimeComparator(in.DeletedAt)
	}
	if in.ExternalRef != nil {
		out.ExternalRef = translateNumericComparatorInt64(in.ExternalRef)
	}
	if in.Flag != nil {
		out.Flag = translateNullableBooleanComparator(in.Flag)
	}
	if in.MidCount != nil {
		out.MidCount = translateNullableNumericComparatorInt32(in.MidCount)
	}
	if in.Name != nil {
		out.Name = translateStringComparator(in.Name)
	}
	if in.Nickname != nil {
		out.Nickname = translateNullableStringComparator(in.Nickname)
	}
	if in.ObservedAt != nil {
		out.ObservedAt = translateNullableTimeComparator(in.ObservedAt)
	}
	if in.ParentID != nil {
		out.ParentID = translateNullableNumericComparatorInt64(in.ParentID)
	}
	if in.Ratio != nil {
		out.Ratio = translateNullableNumericComparatorFloat64(in.Ratio)
	}
	if in.SmallCount != nil {
		out.SmallCount = translateNullableNumericComparatorInt16(in.SmallCount)
	}
	if in.TenantRef != nil {
		out.TenantRef = translateNullableIDComparator(in.TenantRef)
	}
	if in.Accounts != nil {
		out.Accounts = translateAccountFilter(in.Accounts)
	}
	if in.Entries != nil {
		out.Entries = translateEntryFilter(in.Entries)
	}
	if len(in.And) > 0 {
		out.And = make([]*models.AccountFilter, 0, len(in.And))
		for _, sub := range in.And {
			if sub == nil {
				continue
			}
			out.And = append(out.And, translateAccountFilter(sub))
		}
	}
	if len(in.Or) > 0 {
		out.Or = make([]*models.AccountFilter, 0, len(in.Or))
		for _, sub := range in.Or {
			if sub == nil {
				continue
			}
			out.Or = append(out.Or, translateAccountFilter(sub))
		}
	}
	return out
}

// translateEntryFilter converts the gqlgen-generated
// EntryFilter into a *models.EntryFilter.
// Returns nil when the input is nil so the model layer's "nil filter ⇒ no
// where clause" contract is preserved.
func translateEntryFilter(in *gqlmodel.EntryFilter) *models.EntryFilter {
	if in == nil {
		return nil
	}
	out := &models.EntryFilter{}
	if in.AccountID != nil {
		out.AccountID = translateNumericComparatorInt64(in.AccountID)
	}
	if in.Amount != nil {
		out.Amount = translateDecimalComparator(in.Amount)
	}
	if in.CreatedAt != nil {
		out.CreatedAt = translateTimeComparator(in.CreatedAt)
	}
	if in.Memo != nil {
		out.Memo = translateNullableStringComparator(in.Memo)
	}
	if in.UpstreamRef != nil {
		out.UpstreamRef = translateNullableStringComparator(in.UpstreamRef)
	}
	if len(in.And) > 0 {
		out.And = make([]*models.EntryFilter, 0, len(in.And))
		for _, sub := range in.And {
			if sub == nil {
				continue
			}
			out.And = append(out.And, translateEntryFilter(sub))
		}
	}
	if len(in.Or) > 0 {
		out.Or = make([]*models.EntryFilter, 0, len(in.Or))
		for _, sub := range in.Or {
			if sub == nil {
				continue
			}
			out.Or = append(out.Or, translateEntryFilter(sub))
		}
	}
	return out
}
