// Code generated by sqlgen dev. DO NOT EDIT.
package models

import (
	"context"
	"errors"
	"io"

	"github.com/teandresmith/sqlgen/database"
	"github.com/teandresmith/sqlgen/event"
	"github.com/teandresmith/sqlgen/hook"
)

// ClientOption configures the unified Client during construction.
type ClientOption func(*clientOptions)

// clientOptions holds configuration set via ClientOption functions.
type clientOptions struct {
	callbackMode   database.CallbackMode
	panicHandler   func(ctx context.Context, r any, table hook.TableName, op string) error
	mutationHooks  []hook.MutationHook
	queryHooks     []hook.QueryHook
	eventPublisher event.Publisher
	eventConfig    event.Config
	cache          *Cache
}

// WithCallbackMode sets the callback execution mode for transactions.
// Default is database.CallbackAsync.
func WithCallbackMode(mode database.CallbackMode) ClientOption {
	return func(o *clientOptions) {
		o.callbackMode = mode
	}
}

// WithPanicHandler sets a custom panic handler for all operations.
// The handler receives the recovered value, table name, and operation,
// and returns the error that the caller will see.
func WithPanicHandler(handler func(ctx context.Context, r any, table hook.TableName, op string) error) ClientOption {
	return func(o *clientOptions) {
		o.panicHandler = handler
	}
}

// WithMutationHook appends a mutation hook to the client's hook chain.
// Hooks execute in registration order (first registered = outermost).
func WithMutationHook(h hook.MutationHook) ClientOption {
	return func(o *clientOptions) {
		o.mutationHooks = append(o.mutationHooks, h)
	}
}

// WithQueryHook appends a query hook to the client's hook chain.
// Hooks execute in registration order (first registered = outermost).
func WithQueryHook(h hook.QueryHook) ClientOption {
	return func(o *clientOptions) {
		o.queryHooks = append(o.queryHooks, h)
	}
}

// WithCache wires a *Cache into the client — shorthand for registering both
// its QueryHook and MutationHook. Cache is the outermost hook in the chain so
// hits short-circuit before any user hook or event hook runs.
func WithCache(c *Cache) ClientOption {
	return func(o *clientOptions) {
		o.cache = c
	}
}

// Client is the unified entry point for all database operations.
// All entity clients share the same querier and configuration.
// The Client is safe for concurrent use after construction.
type Client struct {
	querier           database.Querier
	opts              clientOptions
	article           *articleClient
	asset             *assetClient
	assetDocumentLink *assetDocumentLinkClient
	auditNote         *auditNoteClient
	auditUser         *auditUserClient
	category          *categoryClient
	categoryStat      *categoryStatClient
	counter           *counterClient
	defaultOnlyRow    *defaultOnlyRowClient
	document          *documentClient
	event             *eventClient
	keyOnlyRow        *keyOnlyRowClient
	noteWatcher       *noteWatcherClient
	order             *orderClient
	orderItem         *orderItemClient
	orderTotal        *orderTotalClient
	product           *productClient
	productSummary    *productSummaryClient
	productTagLabel   *productTagLabelClient
	profile           *profileClient
	publicNote        *publicNoteClient
	publicUser        *publicUserClient
	rateLimit         *rateLimitClient
	sluggedRow        *sluggedRowClient
	tag               *tagClient
	userCategory      *userCategoryClient
	warehouse         *warehouseClient
}

// New creates a new Client with the given querier and options.
// All entity clients are constructed internally with the shared querier.
func New(querier database.Querier, opts ...ClientOption) *Client {
	options := clientOptions{
		callbackMode: database.CallbackAsync,
	}
	for _, o := range opts {
		o(&options)
	}

	// Prepend event hooks as outermost hooks (before user hooks)
	if options.eventPublisher != nil {
		eventHooks := buildEventHooks(options.eventPublisher, options.eventConfig)
		options.mutationHooks = append(eventHooks, options.mutationHooks...)
	}

	// Prepend cache hooks as the outermost hooks so a hit short-circuits before
	// any event or user hook runs.
	if options.cache != nil {
		options.mutationHooks = append([]hook.MutationHook{options.cache.MutationHook()}, options.mutationHooks...)
		options.queryHooks = append([]hook.QueryHook{options.cache.QueryHook()}, options.queryHooks...)
	}

	c := &Client{
		querier:           querier,
		opts:              options,
		article:           newArticleClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		asset:             newAssetClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		assetDocumentLink: newAssetDocumentLinkClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		auditNote:         newAuditNoteClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		auditUser:         newAuditUserClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		category:          newCategoryClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		categoryStat:      newCategoryStatClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		counter:           newCounterClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		defaultOnlyRow:    newDefaultOnlyRowClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		document:          newDocumentClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		event:             newEventClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		keyOnlyRow:        newKeyOnlyRowClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		noteWatcher:       newNoteWatcherClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		order:             newOrderClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		orderItem:         newOrderItemClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		orderTotal:        newOrderTotalClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		product:           newProductClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		productSummary:    newProductSummaryClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		productTagLabel:   newProductTagLabelClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		profile:           newProfileClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		publicNote:        newPublicNoteClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		publicUser:        newPublicUserClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		rateLimit:         newRateLimitClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		sluggedRow:        newSluggedRowClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		tag:               newTagClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		userCategory:      newUserCategoryClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
		warehouse:         newWarehouseClient(querier, options.mutationHooks, options.queryHooks, options.panicHandler),
	}

	// Push the configured CallbackMode down to every entity client that can
	// carry a nested-mutation surface: the nested methods open the transaction
	// the whole nested write runs in and pass this mode to it, so
	// deferred events and cache invalidation flush the way the client was
	// configured rather than on NewTransaction's default.
	c.asset.callbackMode = options.callbackMode
	c.category.callbackMode = options.callbackMode
	c.document.callbackMode = options.callbackMode
	c.event.callbackMode = options.callbackMode
	c.order.callbackMode = options.callbackMode
	c.product.callbackMode = options.callbackMode
	c.publicUser.callbackMode = options.callbackMode
	c.warehouse.callbackMode = options.callbackMode

	// Wire up cross-client references for relationship loading and the clients
	// the nested-mutation executors write through
	c.asset.documentClient = c.document
	c.asset.assetDocumentLinkClient = c.assetDocumentLink
	c.category.productClient = c.product
	c.category.publicUserClient = c.publicUser
	c.category.userCategoryClient = c.userCategory
	c.document.assetClient = c.asset
	c.document.assetDocumentLinkClient = c.assetDocumentLink
	c.event.auditNoteClient = c.auditNote
	c.event.publicNoteClient = c.publicNote
	c.order.orderItemClient = c.orderItem
	c.product.orderItemClient = c.orderItem
	c.product.productTagLabelClient = c.productTagLabel
	c.publicUser.auditNoteClient = c.auditNote
	c.publicUser.publicNoteClient = c.publicNote
	c.publicUser.orderClient = c.order
	c.publicUser.categoryClient = c.category
	c.publicUser.noteWatcherClient = c.noteWatcher
	c.publicUser.profileClient = c.profile
	c.publicUser.userCategoryClient = c.userCategory
	c.warehouse.warehouseClient = c.warehouse

	return c
}

// Articles returns the ArticleClient for Article operations.
func (c *Client) Articles() ArticleClient {
	return c.article
}

// Assets returns the AssetClient for Asset operations.
func (c *Client) Assets() AssetClient {
	return c.asset
}

// AssetDocumentLinks returns the AssetDocumentLinkClient for AssetDocumentLink operations.
func (c *Client) AssetDocumentLinks() AssetDocumentLinkClient {
	return c.assetDocumentLink
}

// AuditNotes returns the AuditNoteClient for AuditNote operations.
func (c *Client) AuditNotes() AuditNoteClient {
	return c.auditNote
}

// AuditUsers returns the AuditUserClient for AuditUser operations.
func (c *Client) AuditUsers() AuditUserClient {
	return c.auditUser
}

// Categories returns the CategoryClient for Category operations.
func (c *Client) Categories() CategoryClient {
	return c.category
}

// CategoryStat returns the CategoryStatClient for CategoryStat operations.
func (c *Client) CategoryStat() CategoryStatClient {
	return c.categoryStat
}

// Counters returns the CounterClient for Counter operations.
func (c *Client) Counters() CounterClient {
	return c.counter
}

// DefaultOnlyRows returns the DefaultOnlyRowClient for DefaultOnlyRow operations.
func (c *Client) DefaultOnlyRows() DefaultOnlyRowClient {
	return c.defaultOnlyRow
}

// Documents returns the DocumentClient for Document operations.
func (c *Client) Documents() DocumentClient {
	return c.document
}

// Events returns the EventClient for Event operations.
func (c *Client) Events() EventClient {
	return c.event
}

// KeyOnlyRows returns the KeyOnlyRowClient for KeyOnlyRow operations.
func (c *Client) KeyOnlyRows() KeyOnlyRowClient {
	return c.keyOnlyRow
}

// NoteWatchers returns the NoteWatcherClient for NoteWatcher operations.
func (c *Client) NoteWatchers() NoteWatcherClient {
	return c.noteWatcher
}

// Orders returns the OrderClient for Order operations.
func (c *Client) Orders() OrderClient {
	return c.order
}

// OrderItems returns the OrderItemClient for OrderItem operations.
func (c *Client) OrderItems() OrderItemClient {
	return c.orderItem
}

// OrderTotal returns the OrderTotalClient for OrderTotal operations.
func (c *Client) OrderTotal() OrderTotalClient {
	return c.orderTotal
}

// Products returns the ProductClient for Product operations.
func (c *Client) Products() ProductClient {
	return c.product
}

// ProductSummary returns the ProductSummaryClient for ProductSummary operations.
func (c *Client) ProductSummary() ProductSummaryClient {
	return c.productSummary
}

// ProductTagLabels returns the ProductTagLabelClient for ProductTagLabel operations.
func (c *Client) ProductTagLabels() ProductTagLabelClient {
	return c.productTagLabel
}

// Profiles returns the ProfileClient for Profile operations.
func (c *Client) Profiles() ProfileClient {
	return c.profile
}

// PublicNotes returns the PublicNoteClient for PublicNote operations.
func (c *Client) PublicNotes() PublicNoteClient {
	return c.publicNote
}

// PublicUsers returns the PublicUserClient for PublicUser operations.
func (c *Client) PublicUsers() PublicUserClient {
	return c.publicUser
}

// RateLimits returns the RateLimitClient for RateLimit operations.
func (c *Client) RateLimits() RateLimitClient {
	return c.rateLimit
}

// SluggedRows returns the SluggedRowClient for SluggedRow operations.
func (c *Client) SluggedRows() SluggedRowClient {
	return c.sluggedRow
}

// Tags returns the TagClient for Tag operations.
func (c *Client) Tags() TagClient {
	return c.tag
}

// UserCategories returns the UserCategoryClient for UserCategory operations.
func (c *Client) UserCategories() UserCategoryClient {
	return c.userCategory
}

// Warehouses returns the WarehouseClient for Warehouse operations.
func (c *Client) Warehouses() WarehouseClient {
	return c.warehouse
}

// Begin starts a new transaction with the given name.
// Delegates to database.NewTransaction with the client's querier.
// The client's configured CallbackMode is applied when the caller does not
// specify one explicitly via TxOptions.
func (c *Client) Begin(ctx context.Context, name string, opts ...database.TxOptions) (context.Context, error) {
	return database.NewTransaction(ctx, c.querier, name, c.applyTxDefaults(opts)...)
}

// applyTxDefaults returns opts with the client's configured CallbackMode
// filled in when the caller did not specify one. A caller-supplied mode
// always wins. Length >1 is passed through so NewTransaction returns its
// normal "at most one TxOptions" error.
func (c *Client) applyTxDefaults(opts []database.TxOptions) []database.TxOptions {
	if len(opts) == 0 {
		return []database.TxOptions{{CallbackMode: c.opts.callbackMode}}
	}
	if len(opts) == 1 && opts[0].CallbackMode == "" {
		merged := opts[0]
		merged.CallbackMode = c.opts.callbackMode
		return []database.TxOptions{merged}
	}
	return opts
}

// Commit commits the active transaction in the context.
// Delegates to database.Commit.
func (c *Client) Commit(ctx context.Context) error {
	return database.Commit(ctx)
}

// Rollback rolls back the active transaction in the context.
// Delegates to database.Rollback.
func (c *Client) Rollback(ctx context.Context) error {
	return database.Rollback(ctx)
}

// WithTx executes fn within a transaction. If fn returns nil, the
// transaction is committed; otherwise it is rolled back.
// Delegates to database.WithTransaction with the client's querier.
// The client's configured CallbackMode is applied when the caller does not
// specify one explicitly via TxOptions.
func (c *Client) WithTx(ctx context.Context, name string, fn func(context.Context) error, opts ...database.TxOptions) error {
	return database.WithTransaction(ctx, c.querier, name, fn, c.applyTxDefaults(opts)...)
}

// Querier returns the active transaction from the context if one exists,
// otherwise the original querier. This is an escape hatch that bypasses
// all hooks.
//
// Inside a transaction the returned Querier is the *database.Tx, so every
// statement through it takes the transaction's connection reservation and
// concurrent use is as safe as through the generated methods. What the
// reservation cannot enforce is the one rule that remains the caller's: drain
// or close a result set before issuing the next statement on that txCtx. A
// caller who holds rows open and then issues another statement is waiting on a
// reservation it holds itself, which surfaces as a wait bounded only by ctx or
// TxOptions.Timeout — neither is set by default — rather than as an immediate
// driver error. database.QueryFunc and database.QueryRowFunc are the spellings
// that cannot leak a result set.
func (c *Client) Querier(ctx context.Context) database.Querier {
	return database.Conn(ctx, c.querier)
}

// Raw executes a raw query and passes the result set to fn. The rows are
// closed when fn returns, so fn must finish reading them before it does.
// Raw does not wrap an error returned by fn, though a global hook may.
// Pass nil args when there are none.
// Global hooks (tracing, auth) are applied; entity-specific hooks are not.
// Panic recovery always wraps the call, fn included.
//
// fn runs inside the hook chain, so the result set cannot outlive the call:
// inside a transaction, the rows give the connection back before Raw returns,
// and concurrent Raw calls on one transactional ctx serialize. A query hook
// therefore spans the scan, and cannot intercept the rows. When ctx carries a
// transaction, fn is still bound by the one rule that remains the caller's:
// drain or close a result set before issuing the next statement on that txCtx.
// A statement fn issues on it before the rows are drained waits on the
// connection fn's own rows still hold.
func (c *Client) Raw(ctx context.Context, rawSQL string, args []any, fn func(database.Rows) error) error {
	terminal := func(ctx context.Context, _ *hook.QueryContext) (any, error) {
		return nil, database.QueryFunc(ctx, database.Conn(ctx, c.querier), rawSQL, args, fn)
	}
	chain := hook.BuildQueryChain(c.opts.panicHandler, c.opts.queryHooks, terminal)
	_, err := chain(ctx, &hook.QueryContext{
		Op:    hook.QueryOp("raw_query"),
		Input: args,
	})
	return err
}

// RawExec executes a raw statement and returns the result.
// Global hooks (tracing, auth) are applied; entity-specific hooks are not.
// Panic recovery always wraps the call.
func (c *Client) RawExec(ctx context.Context, rawSQL string, args ...any) (database.Result, error) {
	terminal := func(ctx context.Context, _ *hook.MutationContext) (any, error) {
		return database.Conn(ctx, c.querier).Exec(ctx, rawSQL, args...)
	}
	chain := hook.BuildMutationChain(c.opts.panicHandler, c.opts.mutationHooks, terminal)
	result, err := chain(ctx, &hook.MutationContext{
		Op:    hook.MutationOp("raw_exec"),
		Input: args,
	})
	if err != nil {
		return nil, err
	}
	return result.(database.Result), nil
}

// Ping verifies database connectivity. If the querier implements a native
// Ping(context.Context) error method, it is used directly. Otherwise falls
// back to executing SELECT 1.
func (c *Client) Ping(ctx context.Context) error {
	type pinger interface {
		Ping(ctx context.Context) error
	}
	if p, ok := c.querier.(pinger); ok {
		return p.Ping(ctx)
	}
	row := c.querier.QueryRow(ctx, "SELECT 1")
	var n int
	return row.Scan(&n)
}

// Close closes all closeable dependencies held by the client.
// If a dependency does not implement io.Closer, it is silently skipped.
// All close errors are collected and returned as a joined error.
func (c *Client) Close() error {
	var errs []error
	if closer, ok := c.querier.(io.Closer); ok {
		errs = append(errs, closer.Close())
	}
	return errors.Join(errs...)
}
